apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-victoriametrics-operator
  labels:
    app.kubernetes.io/component: victoriametrics-operator
    app.kubernetes.io/managed-by: monitoring-operator
    app.kubernetes.io/part-of: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-victoriametrics-operator
subjects:
  - kind: ServiceAccount
    name: monitoring-victoriametrics-operator
