apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-controller-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: kube-controller-manager
    kubernetes.io/service-name: kube-controller-manager
addressType: IPv4
ports:
  - name: "https-metrics"
    port: 10257
    protocol: TCP
