apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubelet
  namespace: monitoring
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    k8s-app: kubelet
    kubernetes.io/service-name: kubelet
addressType: IPv4
ports:
  - name: "https-metrics"
    port: 10250
    protocol: TCP
  - name: "http-metrics"
    port: 10255
    protocol: TCP
  - name: "cadvisor"
    port: 4194
    protocol: TCP
