apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: monitoring-victoriametrics-operator
# Permissions to create downstream custom resources
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - events
      - secrets
      - secrets/finalizers
      - services
      - services/finalizers
      - configmaps
      - configmaps/finalizers
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - patch
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - statefulsets
      - statefulsets/finalizers
      - statefulsets/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - operator.victoriametrics.com
    resources:
      - vlagents
      - vlagents/finalizers
      - vlagents/status
      - vlclusters
      - vlclusters/finalizers
      - vlclusters/status
      - vlogs
      - vlogs/finalizers
      - vlogs/status
      - vlsingles
      - vlsingles/finalizers
      - vlsingles/status
      - vmagents
      - vmagents/finalizers
      - vmagents/status
      - vmalertmanagers
      - vmalertmanagers/finalizers
      - vmalertmanagers/status
      - vmalertmanagerconfigs
      - vmalertmanagerconfigs/finalizers
      - vmalerts
      - vmalerts/finalizers
      - vmalerts/status
      - vmanomalies
      - vmanomalies/finalizers
      - vmanomalies/status
      - vmauths
      - vmauths/finalizers
      - vmauths/status
      - vmclusters
      - vmclusters/finalizers
      - vmclusters/status
      - vmpodscrapes
      - vmprobscrapes/finalizers
      - vmrules
      - vmrules/finalizers
      - vmservicescrapes
      - vmservicescrapes/finalizers
      - vmprobes
      - vmprobes/finalizers
      - vmsingles
      - vmsingles/finalizers
      - vmsingles/status
      - vmnodescrapes
      - vmnodescrapes/finalizers
      - vmstaticscrapes
      - vmstaticscrapes/finalizers
      - vmscrapeconfigs
      - vmscrapeconfigs/finalizers
      - vmscrapeconfigs/status
      - vmusers
      - vmusers/finalizers
      - vmusers/status
      - vtclusters
      - vtclusters/finalizers
      - vtclusters/status
      - vtsingles
      - vtsingles/finalizers
      - vtsingles/status