apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: platform-monitoring-victoriametrics-operator
  labels:
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
priority: 0
users: []
groups: []
readOnlyRootFilesystem: true
allowPrivilegeEscalation: false
defaultAllowPrivilegeEscalation: false
requiredDropCapabilities:
- ALL
defaultAddCapabilities: []
allowedCapabilities: []
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles:
- runtime/default
allowPrivilegedContainer: false
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostIPC: false
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
