apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-victoriametrics-operator
  labels:
    app.kubernetes.io/component: victoriametrics-operator
    app.kubernetes.io/managed-by: monitoring-operator
    app.kubernetes.io/part-of: monitoring
