{{- if and .Values.install .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goldpinger.serviceAccountName" . }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" (include "goldpinger.serviceAccountName" .) "component" "goldpinger-exporter") | nindent 4 }}
{{- end }}
