{{- if and .Values.install .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "goldpinger.labels" . | nindent 4 }}
    app.kubernetes.io/processed-by-operator: victoriametrics-operator
    {{- range $key, $value := .Values.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  jobLabel: {{ .Values.name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "goldpinger.name" . }}
{{- end -}}
