{{- if and .Values.cleanup.deleteCRs .Values.global.privilegedRights -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vm.cleanup.rbac.fullname" . }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" (include "vm.cleanup.rbac.fullname" .)) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
{{- end -}}
