{{- if and .Values.install .Values.serviceAccount.install }}
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.serviceAccount.name "component" "promitor-agent-resource-discovery") | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
      {{ toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
      {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end -}}
