{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" ) ( .Values.install ) ( .Values.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "promitor-agent-resource-discovery" "processedByOperator" "prometheus-operator") | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
      {{ toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.timeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.timeout }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 6 }}
    {{- end }}
  jobLabel: {{ .Values.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
{{- end }}
