{{- if and .Values.install .Values.global.privilegedRights .Values.enableResourceMetrics .Values.APIService .Values.APIService.resourceMetrics }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app.kubernetes.io/name: v1beta1.metrics.k8s.io
    app.kubernetes.io/instance: v1beta1.metrics.k8s.io
    {{- include "prometheusAdapter.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  service:
    name: prometheus-adapter
    namespace: {{ .Release.Namespace }}
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
{{- end }}
