{{- if and .Values.install .Values.clusterRoleBinding.install .Values.global.privilegedRights }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "prometheusAdapter.rbac.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "prometheusAdapter.rbac.fullname" .) "component" "prometheus-adapter" "managedByOperator" "prometheus-adapter-operator") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheusAdapter.rbac.fullname" . }}
{{- end }}
