{{- if .Values.install }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Values.name }}
{{- end }}
