{{- if .Values.install }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: prometheus-adapter-operator
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" "prometheus-adapter-operator" "component" "prometheus-adapter" "managedByOperator" "prometheus-adapter-operator") | nindent 4 }}
rules:
  # Permissions for leader election
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - services
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - verbs:
      - create
      - get
      - update
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete

  - apiGroups:
      - monitoring.netcracker.com
    resources:
      - customscalemetricrules
      - customscalemetricrules/status
      - customscalemetricrules/finalizers
      - prometheusadapters
      - prometheusadapters/status
      - prometheusadapters/finalizers
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - create
{{- end }}
