{{- if and .Values.install .Values.auth }}
{{- if and .Values.auth.basicAuth .Values.auth.basicAuth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-adapter-client-basic-auth
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "prometheus-adapter-client-basic-auth") | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.basicAuth.createSecret.username }}
  password: {{ .Values.auth.basicAuth.createSecret.password }}
{{- end }}
{{- end }}
