{{- if .Values.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-adapter-operator
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" "prometheus-adapter-operator" "component" "prometheus-adapter" "managedByOperator" "prometheus-adapter-operator") | nindent 4 }}
{{- end }}
