kind: Service
apiVersion: v1
metadata:
  name: etcd
  namespace: kube-system
  labels:
    k8s-app: etcd
    app.kubernetes.io/component: etcd
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 2379
      targetPort: 2379
    - name: etcd-metrics
      protocol: TCP
      port: 9979
      targetPort: 9979
  selector:
    component: etcd
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
