sonar.sources=.
sonar.exclusions=**/*_test.go,test/robot-tests/**,tools/crd-update/test_*.py,api/v1/zz_generated.deepcopy.go,charts/qubership-monitoring-operator/crds/**,charts/qubership-monitoring-operator/charts/*/crds/**,charts/qubership-monitoring-crds/crds/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,tools/crd-update/test_*.py
sonar.coverage.exclusions=tools/crd-update/**,api/v1/zz_generated.deepcopy.go,charts/qubership-monitoring-operator/crds/**,charts/qubership-monitoring-operator/charts/*/crds/**,charts/qubership-monitoring-crds/crds/**
sonar.language=go
sonar.sourceEncoding=UTF-8
