{{- if and .Values.install .Values.global.privilegedRights .Values.rbac.createClusterRole }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "cloudEventsExporter.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "cloudEventsExporter.fullname" .) "component" "cloud-events-exporter") | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}