{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "cloud-events-exporter") | nindent 4 }}
data:
{{- if .Values.filtering }}
  filtering.yaml: |-
    sinks:
      - name: "metrics"
        {{- toYaml .Values.filtering | nindent 8 }}
{{- else }}
  filtering.yaml: ""
{{- end }}
{{- end }}
