{{- if .Values.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" (include "cloudEventsExporter.fullname" .)) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: health
      protocol: TCP
      name: health
    - name: metrics
      port: {{ .Values.port | default 9999 }}
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ template "cloudEventsExporter.fullname" . }}
{{- end }}
