{{- if .Values.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "cloud-events-exporter") | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{ toYaml .Values.serviceAccount.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}