apiVersion: v1
kind: Secret
metadata:
  name: grafana-ldap-config
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" "grafana-ldap-config" "component" "grafana" "managedByOperator" "monitoring-operator") | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.ldapConfig }}
  ldap.toml: |-
    {{ .Values.ldapConfig | nindent 4}}
{{- else }}
  ldap.toml: ""
{{- end }}
