{{- if eq .Values.publicCloudName "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.etcdCertsJob.rbac.clusterRoleName }}
  labels:
    app.kubernetes.io/name: {{ .Values.etcdCertsJob.rbac.clusterRoleName }}
    app.kubernetes.io/component: monitoring-etcd-certs-to-secret
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "monitoring.operator.version" . }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - "etcd-metric-client"
      - "etcd-client"
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - "etcd-metric-serving-ca"
      - "etcd-serving-ca"
  - verbs:
      - get
      - list
      - watch
      - update
      - create
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
{{- end }}
