{{- if eq .Values.publicCloudName "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.etcdCertsJob.rbac.serviceAccountName }}
  labels:
    app.kubernetes.io/name: {{ .Values.etcdCertsJob.rbac.serviceAccountName }}
    app.kubernetes.io/component: monitoring-etcd-certs-to-secret
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/instance: {{ template "monitoring.instance" . }}
    app.kubernetes.io/version: {{ template "monitoring.operator.version" . }}
{{- end -}}
