{{- if and .Values.role.install .Values.global.privilegedRights }}
{{- $operatorClusterRoleName := include "monitoring.operator.rbac.fullname" . -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ $operatorClusterRoleName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" $operatorClusterRoleName) | nindent 4 }}
rules:
  ############################################### Kubernetes API Groups ################################################

  # nonResourceURLs
  # This is needed for metrics endpoint access
  - nonResourceURLs:
      - /metrics
      - /metrics/resources
      - /metrics/slis
    verbs:
      - get
      - watch
      - list

  # core
  # This is needed for handling Deployments, DaemonSets, StatefulSets, and ReplicaSets
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/finalizers
      - configmaps/status
      - endpoints
      - events
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
      - pods
      - pods/eviction
      - secrets
      - secrets/finalizers
      - serviceaccounts
      - serviceaccounts/finalizers
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpointslices
      - limitranges
      - namespaces
      - nodes
      - nodes/metrics
      - nodes/proxy
      - persistentvolumes
      - pods
      - replicationcontrollers
      - resourcequotas
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

  # rbac.authorization.k8s.io
  # This is needed for role and rolebinding creation
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterrolebindings/finalizers
      - clusterroles
      - clusterroles/finalizers
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # apps
  # This is needed for deployment, daemonset and statefulset creation
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets/finalizers
      - daemonsets/status
      - deployments/finalizers
      - deployments/status
      - statefulsets/finalizers
      - statefulsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # TODO: Is it still actually needed?
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - list
      - watch

  # TODO: Is it still actually needed?
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # authentication.k8s.io
  # This is needed for token review creation
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create

  # apiextensions.k8s.io
  # This is needed for custom resource definition creation
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # certificates.k8s.io
  # This is needed for certificate signing request creation
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - list
      - watch

  # policy
  # This is needed for pod disruption budget creation
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # batch
  # This is needed for cronjob and job creation
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - watch

  # storage.k8s.io
  # This is needed for storage class and volume attachment creation
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - list
      - watch

  # autoscaling
  # This is needed for horizontal pod autoscaler creation
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # discovery.k8s.io
  # This is needed for endpoints slice discovery
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

  # networking.k8s.io
  # Permissions to handle Ingresses
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
      - ingresses/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  # Permissions to handle Ingresses finalizers
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingresses/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  # admissionregistration.k8s.io
  # This is needed for validating and mutating webhook configurations
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - list
      - watch

  # coordination.k8s.io
  # This is needed for lease creation
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update

  # Security for Kubernetes < 1.25
  {{- if $.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - create
      - get
      - list
      - watch
  {{- end }}
  {{- if $.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - node-exporter
    verbs:
      - delete
      - update
      - use
      - patch
  {{- end }}
  {{- if $.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - victoriametrics-operator
    verbs:
      - use
      - update
      - patch
  {{- end }}

  ################################################ OpenShift API Groups ################################################

  # route.openshift.io
  # This is needed for managing routes
  # TODO: Maybe need to remove this because we stop using OpenShift specific objects
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - update
      - watch

  # config.openshift.io
  # This is needed for managing cluster versions
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get

  # image.openshift.io
  # This is needed for managing image streams
  - apiGroups:
      - route.openshift.io
      - image.openshift.io
    resources:
      - routers/metrics
      - registry/metrics
    verbs:
      - get

  - apiGroups:
    - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - create
      - get
      - list
      - watch

  # OpenShift SCCs
  {{- if $.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - node-exporter
    verbs:
      - delete
      - update
      - use
  {{- end }}
  {{- if $.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" }}
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - victoriametrics-operator
    verbs:
      - use
      - update
  {{- end }}

  ################################################## CRDs permissions ##################################################

  # monitoring.netcracker.com
  # This is needed for managing PlatformMonitoring custom resources
  - apiGroups:
      - monitoring.netcracker.com
    resources:
      - platformmonitorings
      - platformmonitorings/finalizers
      - platformmonitorings/status
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # integreatly.org
  # This is needed for managing Grafana custom resources
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanadashboards/status
      - grafanadatasources
      - grafanadatasources/status
      - grafanafolders
      - grafanafolders/status
      - grafananotificationchannels
      - grafananotificationchannels/status
      - grafanas
      - grafanas/finalizers
      - grafanas/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  # monitoring.coreos.com
  # This is needed for Prometheus Operator custom resources
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagerconfigs
      - alertmanagerconfigs/finalizers
      - alertmanagerconfigs/status
      - alertmanagers
      - alertmanagers/finalizers
      - alertmanagers/status
      - podmonitors
      - podmonitors/finalizers
      - podmonitors/status
      - probes
      - probes/finalizers
      - probes/status
      - prometheusagents
      - prometheusagents/finalizers
      - prometheusagents/status
      - prometheuses
      - prometheuses/finalizers
      - prometheuses/status
      - prometheusrules
      - prometheusrules/finalizers
      - prometheusrules/status
      - scrapeconfigs
      - scrapeconfigs/finalizers
      - scrapeconfigs/status
      - servicemonitors
      - servicemonitors/finalizers
      - servicemonitors/status
      - thanosrulers
      - thanosrulers/finalizers
      - thanosrulers/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # operator.victoriametrics.com
  # This is needed for managing VictoriaMetrics custom resources
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vmalertmanagerconfigs
      - vmnodescrapes
      - vmpodscrapes
      - vmprobes
      - vmrules
      - vmscrapeconfigs
      - vmservicescrapes
      - vmstaticscrapes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vlagents
      - vlclusters
      - vlogs
      - vlsingles
      - vmagents
      - vmalertmanagers
      - vmalerts
      - vmanomalies
      - vmauths
      - vmclusters
      - vmdistributed
      - vmsingles
      - vmusers
      - vtclusters
      - vtsingles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vlagents/finalizers
      - vlagents/status
      - vlclusters/finalizers
      - vlclusters/finalizers
      - vlclusters/status
      - vlclusters/status
      - vlogs/finalizers
      - vlogs/status
      - vlsingles/finalizers
      - vlsingles/status
      - vmagents/finalizers
      - vmagents/status
      - vmalertmanagerconfigs/finalizers
      - vmalertmanagerconfigs/status
      - vmalertmanagers/finalizers
      - vmalertmanagers/status
      - vmalerts/finalizers
      - vmalerts/status
      - vmanomalies/finalizers
      - vmanomalies/status
      - vmauths/finalizers
      - vmauths/status
      - vmclusters/finalizers
      - vmclusters/status
      - vmdistributed/finalizers
      - vmdistributed/status
      - vmnodescrapes/finalizers
      - vmnodescrapes/status
      - vmpodscrapes/finalizers
      - vmpodscrapes/status
      - vmprobes/finalizers
      - vmprobes/status
      - vmrules/finalizers
      - vmrules/status
      - vmscrapeconfigs/finalizers
      - vmscrapeconfigs/status
      - vmservicescrapes/finalizers
      - vmservicescrapes/status
      - vmsingles/finalizers
      - vmsingles/status
      - vmstaticscrapes/finalizers
      - vmstaticscrapes/status
      - vmusers/finalizers
      - vmusers/status
      - vtclusters/finalizers
      - vtclusters/status
      - vtsingles/finalizers
      - vtsingles/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
{{- end }}
