{{- $values := .Values | toJson | fromJson -}}
{{- $cleanupHook := dig "victoriametrics" "cleanup" "hook" (dict) $values -}}
{{- if or .Values.grafana.install .Values.commonDashboards.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: monitoring-grafana-cleanup-hook
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "monitoring-grafana-cleanup-hook") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
    "helm.sh/resource-policy": keep
spec:
  {{- if (get $cleanupHook "ttlSecondsAfterFinished" | default 180) }}
  ttlSecondsAfterFinished: {{ get $cleanupHook "ttlSecondsAfterFinished" | default 180 }}
  {{- end }}
  template:
    metadata:
      name: monitoring-grafana-cleanup-hook
      labels:
        {{- include "monitoring.labels" (dict "ctx" . "name" "monitoring-grafana-cleanup-hook") | nindent 8 }}
    spec:
      serviceAccountName: monitoring-grafana-cleanup-hook
      restartPolicy: OnFailure
      securityContext:
        {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
        runAsUser: 2000
        fsGroup: 2000
        {{- else }}
        {}
        {{- end }}
      containers:
        - name: kubectl
          image: {{ get $cleanupHook "image" | default "docker.io/rancher/kuberlr-kubectl:v8.0.0" }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
            - >
              set -eu;
              kubectl scale deployment --replicas=0 --selector app.kubernetes.io/component=qubership-monitoring-operator;
              sleep {{ get $cleanupHook "timeout" | default "10" }};
              kubectl delete grafanadashboards.grafana.integreatly.org
              --selector=app.kubernetes.io/managed-by-operator=monitoring-operator,app.kubernetes.io/component=grafana-operator
              --ignore-not-found=true --wait=true
              --timeout={{ get $cleanupHook "deleteTimeout" | default "5m" }};
              {{- if .Values.commonDashboards.install }}
              kubectl delete grafanadashboards.grafana.integreatly.org backup-daemon kafka-java-clients
              --ignore-not-found=true --wait=true
              --timeout={{ get $cleanupHook "deleteTimeout" | default "5m" }};
              {{- end }}
              {{- if .Values.grafana.install }}
              kubectl delete grafanadatasources.grafana.integreatly.org
              --selector=app.kubernetes.io/managed-by-operator=monitoring-operator
              --ignore-not-found=true --wait=true
              --timeout={{ get $cleanupHook "deleteTimeout" | default "5m" }};
              kubectl delete grafanas.grafana.integreatly.org
              --selector=app.kubernetes.io/managed-by-operator=monitoring-operator
              --ignore-not-found=true --wait=true
              --timeout={{ get $cleanupHook "deleteTimeout" | default "5m" }};
              {{- end }}
{{- end }}
