{{- if .Values.role.install }}
{{- if not .Values.global.privilegedRights }}
{{- $operatorRoleName := include "monitoring.operator.fullname" . -}}
kind: RoleBinding
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ $operatorRoleName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" $operatorRoleName) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.monitoringOperator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "monitoring.operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
