{{- if .Values.role.install }}
{{- if not .Values.global.privilegedRights }}
{{- $operatorRoleName := include "monitoring.operator.fullname" . -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ $operatorRoleName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" $operatorRoleName) | nindent 4 }}
rules:
  ############################################### Kubernetes API Groups ################################################

  # core
  # This is needed for handling core Kubernetes resources
  - apiGroups:
      - ""
    resources:
      - limitranges
      - replicationcontrollers
      - resourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - configmaps/finalizers
      - configmaps/status
      - endpoints
      - events
      - persistentvolumeclaims
      - persistentvolumeclaims/finalizers
      - pods
      - secrets
      - secrets/finalizers
      - serviceaccounts
      - serviceaccounts/finalizers
      - services
      - services/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

  # apps
  # This is needed for handling Deployments, DaemonSets, StatefulSets, and ReplicaSets
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - daemonsets/finalizers
      - deployments
      - deployments/finalizers
      - replicasets
      - statefulsets
      - statefulsets/finalizers
      - statefulsets/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch

  # batch
  # This is needed for handling CronJobs and Jobs
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - watch

  # rbac.authorization.k8s.io
  # This is needed for role and rolebinding creation
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # policy
  # This is needed for handling PodDisruptionBudgets
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch

  # autoscaling
  # This is needed for handling HorizontalPodAutoscalers and VerticalPodAutoscalers
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - watch

  # networking.k8s.io
  # This is needed for handling Ingresses
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
      - ingresses/finalizers
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch

  # coordination.k8s.io
  # This is needed for lease creation
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update

  ################################################ OpenShift API Groups ################################################

  # config.openshift.io
  # This is needed for handling ClusterVersion resources
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - get

  # route.openshift.io
  # This is needed for handling Routes
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  ################################################## CRDs permissions ##################################################

  # netcracker.com
  # This is needed for managing PlatformMonitoring custom resources
  - apiGroups:
      - netcracker.com
    resources:
      - platformmonitorings
      - platformmonitorings/finalizers
      - platformmonitorings/status
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch

  # integreatly.org
  # This is needed for managing Grafana custom resources
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanadashboards/status
      - grafanadatasources
      - grafanadatasources/status
      - grafanafolders
      - grafanafolders/status
      - grafananotificationchannels
      - grafananotificationchannels/status
      - grafanas
      - grafanas/finalizers
      - grafanas/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # monitoring.coreos.com
  # This is needed for Prometheus Operator custom resources
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagerconfigs
      - alertmanagerconfigs/finalizers
      - alertmanagerconfigs/status
      - alertmanagers
      - alertmanagers/finalizers
      - alertmanagers/status
      - podmonitors
      - podmonitors/finalizers
      - podmonitors/status
      - probes
      - probes/finalizers
      - probes/status
      - prometheusagents
      - prometheusagents/finalizers
      - prometheusagents/status
      - prometheuses
      - prometheuses/finalizers
      - prometheuses/status
      - prometheusrules
      - prometheusrules/finalizers
      - prometheusrules/status
      - scrapeconfigs
      - scrapeconfigs/finalizers
      - scrapeconfigs/status
      - servicemonitors
      - servicemonitors/finalizers
      - servicemonitors/status
      - thanosrulers
      - thanosrulers/finalizers
      - thanosrulers/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # operator.victoriametrics.com
  # This is needed for managing VictoriaMetrics custom resources
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vmalertmanagerconfigs
      - vmnodescrapes
      - vmpodscrapes
      - vmprobes
      - vmrules
      - vmscrapeconfigs
      - vmservicescrapes
      - vmstaticscrapes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vlagents
      - vlclusters
      - vlogs
      - vlsingles
      - vmagents
      - vmalertmanagers
      - vmalerts
      - vmauths
      - vmclusters
      - vmdistributed
      - vmsingles
      - vmusers
      - vtclusters
      - vtsingles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.victoriametrics.com
    resources:
      - vlagents/finalizers
      - vlagents/status
      - vlclusters/finalizers
      - vlclusters/status
      - vlogs/finalizers
      - vlogs/status
      - vlsingles/finalizers
      - vlsingles/status
      - vmagents/finalizers
      - vmagents/status
      - vmalertmanagerconfigs/finalizers
      - vmalertmanagerconfigs/status
      - vmalertmanagers/finalizers
      - vmalertmanagers/status
      - vmalerts/finalizers
      - vmalerts/status
      - vmanomalies
      - vmanomalies/finalizers
      - vmanomalies/status
      - vmauths/finalizers
      - vmauths/status
      - vmclusters/finalizers
      - vmclusters/status
      - vmdistributed/finalizers
      - vmdistributed/status
      - vmnodescrapes/finalizers
      - vmnodescrapes/status
      - vmpodscrapes/finalizers
      - vmpodscrapes/status
      - vmprobes/finalizers
      - vmprobes/status
      - vmrules/finalizers
      - vmrules/status
      - vmscrapeconfigs/finalizers
      - vmscrapeconfigs/status
      - vmservicescrapes/finalizers
      - vmservicescrapes/status
      - vmsingles/finalizers
      - vmsingles/status
      - vmstaticscrapes/finalizers
      - vmstaticscrapes/status
      - vmusers/finalizers
      - vmusers/status
      - vtclusters/finalizers
      - vtclusters/status
      - vtsingles/finalizers
      - vtsingles/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

{{- end }}
{{- end }}
