{{- if .Values.role.install }}
{{- if not .Values.global.privilegedRights }}
kind: RoleBinding
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ template "monitoring.operator.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "monitoring.operator.fullname" .) "component" "monitoring-operator") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.monitoringOperator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "monitoring.operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
