{{- if .Values.monitoringOperator.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoringOperator.serviceAccount.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.monitoringOperator.serviceAccount.name "component" "monitoring-operator") | nindent 4 }}
{{- end }}
