{{- if .Values.monitoringOperator.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.monitoringOperator.serviceAccount.name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" .Values.monitoringOperator.serviceAccount.name) | nindent 4 }}
{{- end }}
