{{- if .Values.install }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "promxy") | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: web
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
{{- end }}
