{{- if and .Values.install .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ssl-exporter.name" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
    app: {{ include "ssl-exporter.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ssl-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ssl-exporter.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }} 