{{- if .Values.install }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ssl-exporter.name" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssl-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ssl-exporter.labels" . | nindent 8 }}
        {{- include "ssl-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "ssl-exporter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "ssl-exporter.name" . }}
          image: {{ include "ssl-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config.file=/etc/ssl-exporter/ssl-exporter.yaml
          ports:
            - name: {{ .Values.service.name | default "http" }}
              containerPort: {{ .Values.service.targetPort | default 9219 }}
              protocol: {{ .Values.service.protocol | default "TCP" }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/ssl-exporter
              readOnly: true
          {{- if .Values.additionalHostPathVolumes }}
            {{- range .Values.additionalHostPathVolumes }}
            - name: {{ .volumeName }}
              mountPath: {{ .volumePath }}
              readOnly: true
            {{- end }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ssl-exporter.name" . }}-config
      {{- if .Values.additionalHostPathVolumes }}
        {{- range .Values.additionalHostPathVolumes }}
        - name: {{ .volumeName }}
          hostPath:
            path: {{ .volumePath }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
