apiVersion: v1
kind: Secret
metadata:
  name: additional-alertrelabel-configs
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "additional-alertrelabel-configs") | nindent 4 }}
type: Opaque
{{- if .Values.additionalAlertRelabel }}
stringData:
  alertrelabel-additional.yaml: |-
    {{- toYaml .Values.additionalAlertRelabel | nindent 4 }}
{{- else }}
data:
  alertrelabel-additional.yaml: ""
{{- end }}
