{{- if .Values.tlsConfig }}
{{- if .Values.tlsConfig.createSecret}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ default "prometheus-tls" .Values.tlsConfig.createSecret.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" (default "prometheus-tls" .Values.tlsConfig.createSecret.name) "component" "prometheus") | nindent 4 }}
data: {}
stringData:
  {{- if .Values.tlsConfig.createSecret.ca }}
  ca.crt:
    {{- toYaml .Values.tlsConfig.createSecret.ca | nindent 4 }}
  {{- end }}
  {{- if .Values.tlsConfig.createSecret.cert }}
  tls.crt:
    {{- toYaml .Values.tlsConfig.createSecret.cert | nindent 4 }}
  {{- end }}
  {{- if .Values.tlsConfig.createSecret.key }}
  tls.key:
    {{- toYaml .Values.tlsConfig.createSecret.key | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
