apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" "additional-scrape-configs" "component" "prometheus") | nindent 4 }}
type: Opaque
{{- if .Values.additionalScrape }}
stringData:
  prometheus-additional.yaml: |-
    {{- toYaml .Values.additionalScrape | nindent 4 }}
{{- else }}
data:
  prometheus-additional.yaml: ""
{{- end }}
