{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "json-exporter") | nindent 4 }}
data:
  allow-snippet-annotations: "false"
  {{- if .Values.config }}
  config.yml: |
    {{ .Values.config | nindent 4 }}
  {{- else }}
  config.yml: ""
  {{- end }}
{{- end }}
