{{- if .Values.security }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials-temp
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" "grafana-admin-credentials-temp" "component" "grafana" "managedByOperator" "monitoring-operator") | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.security.admin_user }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.security.admin_password }}
{{- end }}
