{{- if .Values.imageRenderer.install }}
{{- $name := .Values.imageRenderer.name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" $name "component" "grafana") | nindent 4 }}
    {{- if .Values.imageRenderer.labels }}
      {{- toYaml .Values.imageRenderer.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.imageRenderer.annotations }}
  annotations:
    {{- toYaml .Values.imageRenderer.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.imageRenderer.port }}
      targetPort: web
  selector:
    app.kubernetes.io/name: {{ .Values.imageRenderer.name }}
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None
{{- end }}
