{{- if .Values.grafana }}
{{- if .Values.grafana.install }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-extra-vars-secret
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" "grafana-extra-vars-secret" "component" "grafana") | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.auth}}
{{- if .Values.auth.clientId}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .Values.auth.clientId }}
{{- end}}
{{- if .Values.auth.clientSecret}}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.auth.clientSecret }}
{{- end}}
{{- end}}
{{- if .Values.grafana.extraVarsSecret }}
  {{- range $key, $val := .Values.grafana.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
{{- end}}
{{- end}}
{{- end}}
{{- end}}
