{{- if and .Values.grafana .Values.grafana.install .Values.auth .Values.auth.clientSecret }}
{{- $grafanaNamespace := .Release.Namespace }}
{{- if .Values.grafana.namespace }}
{{- $grafanaNamespace = .Values.grafana.namespace }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-client-secret
  namespace: {{ $grafanaNamespace }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "grafana-oauth-client-secret" "component" "grafana") | nindent 4 }}
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.auth.clientSecret | quote }}
{{- end }}
