apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: qubership-alert-rules
spec:
  groups:
{{- range $groupName, $group := .Values.alerts }}
    - name: {{ $groupName }}
      labels:
{{- range $labelName, $labelValue := $group.labels }}
        {{ $labelName }}: {{ $labelValue }}
{{- end }}
      {{- if $group.interval }} 
      interval: {{ $group.interval }} 
      {{- end }}
      {{- if $group.concurrency }} 
      concurrency: {{ $group.concurrency }} 
      {{- end }}
      rules:
{{- range $ruleName, $rule := $group.rules }}
        - alert: {{ $ruleName }}
          expr: {{ printf "%s" $rule.expr | trimAll "\n" | nindent 12 }}
          {{- if $rule.for }} 
          for: {{ $rule.for }}
          {{- end }}
          labels:
{{- range $labelName, $labelValue := $rule.labels }}
            {{ $labelName }}: {{ $labelValue }}
{{- end }}
          annotations:
{{- range $annotationName, $annotationValue := $rule.annotations }}
            {{ $annotationName }}: {{ printf "%s" $annotationValue | toJson | nindent 14 }}
{{- end }}
{{- end }}
{{- end }}