{{- if and .Values.install .Values.global.privilegedRights }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "version-exporter.rbac.fullname" . }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" (include "version-exporter.rbac.fullname" .) "component" "version-exporter") | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}