{{- if and .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "version-exporter") | nindent 4 }}
data:
  {{- if .Values.exporterConfig }}
  exporterConfig.yaml: |-
    {{- toYaml .Values.exporterConfig | nindent 4 }}
  {{- else }}
  exporterConfig.yaml: ""
  {{- end }}
{{- end }}
