{{- if and .Values.install .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "monitoring" "processedByOperator" "prometheus-operator") | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval | default "5m" }}
      scrapeTimeout: {{ .Values.serviceMonitor.timeout | default "30s" }}
      port: http
      path: {{ .Values.serviceMonitor.telemetryPath | default "/metrics" }}
      scheme: http
  jobLabel: {{ .Values.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
{{- end }}