apiVersion: v1
kind: Secret
metadata:
  name: additional-alertmanager-configs
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "additional-alertmanager-configs") | nindent 4 }}
type: Opaque
{{- if .Values.additionalAlertManager }}
stringData:
  alertmanager-additional.yaml: |-
    {{- toYaml .Values.additionalAlertManager | nindent 4 }}
{{- else }}
data:
  alertmanager-additional.yaml: ""
{{- end }}
