{{- if and .Values.integrationTests.install .Values.global.privilegedRights }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "integrationTests.rbac.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "integrationTests.rbac.fullname" .) "component" "platform-monitoring-tests") | nindent 4 }}
rules:
  - apiGroups:
      - "integreatly.org"
    resources:
      - grafanadashboards
      - grafanadashboards/status
      - grafanas
      - grafanas/status
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
      - "create"
  - apiGroups:
      - "custom.metrics.k8s.io"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
{{- end }}
