{{- if .Values.integrationTests.install }}
{{- if eq (.Values.integrationTests.statusWriting.enabled | toString) "true" }}
{{- $writeStatusRole := printf "%s-write-status" .Values.integrationTests.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $writeStatusRole }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" $writeStatusRole "component" "platform-monitoring-tests") | nindent 4 }}
rules:
- apiGroups:
  - {{ template "integrationTests.apigroup_custom_resource" . }}
  resources:
  - {{ template "integrationTests.plural_custom_resource" . }}/status
  verbs:
  - get
  - patch
{{- end }}
{{- end }}
