{{- if .Values.integrationTests.install }}
{{- $intTestsRole := printf "%s-int-tests" .Values.integrationTests.name -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $intTestsRole }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" $intTestsRole "component" "platform-monitoring-tests") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.integrationTests.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $intTestsRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
