{{- if .Values.integrationTests.install }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.integrationTests.name }}-int-tests
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (printf "%s-int-tests" .Values.integrationTests.name) "component" "platform-monitoring-tests") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.integrationTests.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.integrationTests.name }}-int-tests
  apiGroup: rbac.authorization.k8s.io
{{- end }}
