{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integrationTests.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.integrationTests.name "component" "platform-monitoring-tests") | nindent 4 }}
{{- end }}
