{{- if .Values.integrationTests.install -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tests-config
  labels:
    app: monitoring-tests
#data:
#  {{- if include "monitoring.monitoredImages" . }}
#  dd_images: {{ include "monitoring.monitoredImages" . }}
#  {{ else }}
#  dd_images: ""
#  {{ end }}
{{ end }}