{{- define "monitoredImages.wrapper" -}}
  {{- block "monitoring.monitoredImages" . }}DEFAULT{{- end -}}
{{- end -}}
{{- if .Values.integrationTests.install -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tests-config
  labels:
    app: monitoring-tests
data:
  {{- if ne (include "monitoredImages.wrapper" .) "DEFAULT" }}
    dd_images: {{ include "monitoring.monitoredImages" . | indent 2 | quote }}
  {{ else }}
  dd_images: ""
  {{ end }}
{{ end }}
