{
 "title": "Alertmanager Overview",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debugging.",
 "tags": [
  "alertmanager",
  "self-monitor"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(alertmanager_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alertmanager_build_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "instance",
    "label": "pod",
    "query": {
     "query": "label_values(alertmanager_build_info{cluster=\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of instances",
   "type": "stat",
   "description": "Number of Alertmanager instances",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "stat",
   "description": "Number of peers in the Alertmanager cluster.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_cluster_members{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Instance versions and up time",
   "type": "table",
   "description": "Table containing list of Alertmanager instances showing it's version, up time, last reload time and if it was successful.",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "time() - (alertmanager_build_info{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"} * on (instance, cluster) group_left process_start_time_seconds{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "time() - alertmanager_config_last_reload_success_timestamp_seconds{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "alertmanager_config_last_reload_successful{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of active alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"active\", pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of suppressed alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_alerts{state=\"suppressed\", pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of active silences",
   "type": "stat",
   "description": "Current number of active silences.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(alertmanager_silences{state=\"active\", pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notifications sent from $instance",
     "type": "timeseries",
     "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_notifications_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (integration)",
       "legendFormat": "{{ integration}}"
      },
      {
       "expr": "sum(increase(alertmanager_notifications_failed_total{ipod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (integration)",
       "legendFormat": "Failed {{ integration }}"
      }
     ]
    },
    {
     "title": "Notification durations per integration on $instance",
     "type": "timeseries",
     "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]))) by (integration)",
       "legendFormat": "0.9q {{ integration }}"
      },
      {
       "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]))) by (integration)",
       "legendFormat": "0.99q  {{ integration }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active alerts in $instance",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for $instance",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster health score for $instance",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Cluster members count on $instance",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_members{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on $instance",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 169 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 249 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Sucessful reconnections"
      },
      {
       "expr": "increase(alertmanager_cluster_reconnections_failed_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Failed reconnections"
      }
     ]
    },
    {
     "title": "Cluster messages count on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 329 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on $instance",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update`  or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 409 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on $instance",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 489 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Pruned messaged"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Count of oversized gossip messages on $instance",
     "type": "timeseries",
     "description": "Number of oversized gossip message sent by $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_dropped_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "dropped {{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Number of  propagated gossip messages on $instance",
     "type": "timeseries",
     "description": "Number of  propagated gossip messages on $instance",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "silences"
      },
      {
       "expr": "increase(alertmanager_nflog_gossip_messages_propagated_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "nf_log"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on $instance",
     "type": "timeseries",
     "description": "Duration of oversized gossip message requests on $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "{{key}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Nf log queries count for $instance",
     "type": "timeseries",
     "description": "Number of log queries for $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Nf log query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Nf log query errors"
      }
     ]
    },
    {
     "title": "Nf log query duration for $instance",
     "type": "timeseries",
     "description": "Nf log query duration for $instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "Nf log query duration"
      }
     ]
    },
    {
     "title": "Nf log snapshot size for $instance",
     "type": "timeseries",
     "description": "Snapshot size for NF log on $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    },
    {
     "title": "Nf log Go GC time for $instance",
     "type": "timeseries",
     "description": "Duration of the last notification log garbage collection cycle for $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 167 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_nflog_gc_duration_seconds{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Cluster joined peers"
      }
     ]
    },
    {
     "title": "Nf log snapshot duration for $instance",
     "type": "timeseries",
     "description": "The duration of creating snapshoot fo NF log on  $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 221 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]) / rate(alertmanager_nflog_snapshot_duration_seconds_sum{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Nf log snapshot size"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Silences count by state on $instance",
     "type": "timeseries",
     "description": "Number of silences by state on $instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alertmanager_silences{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on $instance",
     "type": "timeseries",
     "description": "Number of silences queries and errors on $instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Silecnces query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "Silecnces query fails"
      }
     ]
    },
    {
     "title": "Silences query duration on $instance",
     "type": "timeseries",
     "description": "Silences query duration on $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}[5m]))",
       "legendFormat": "Silecnces query duration"
      }
     ]
    },
    {
     "title": "Silences snapshot size on $instance",
     "type": "timeseries",
     "description": "Size of the silence snapshot in bytes on $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Silecnces snapshot size"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on $instance",
     "type": "timeseries",
     "description": "Duration of the silence snapshot on $instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_duration_seconds{quantile=\"0.99\", pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Silecnces snapshot duration"
      }
     ]
    },
    {
     "title": "Silences GC duraton on $instance",
     "type": "timeseries",
     "description": "Duration of the silence garbage collection cycle\n on $instance",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "alertmanager_silences_gc_duration_seconds{pod=~\"$instance\", cluster=\"$cluster\", namespace=~\"$namespace\"}",
       "legendFormat": "Silecnces GC  duration"
      }
     ]
    }
   ]
  }
 ]
}