{
 "title": "Grafana Overview",
 "description": "Dashboards shows extended statistics about Grafana, including time of searching, saving and getting dashboards.",
 "tags": [
  "self-monitor",
  "grafana"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(grafana_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(grafana_build_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "instance",
    "label": "pod",
    "query": {
     "query": "label_values(grafana_build_info{cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(grafana_build_info{cluster=\"$cluster\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Dashboards count",
   "type": "stat",
   "description": "Shows total amount of dashboards ",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(grafana_stat_totals_dashboard{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Organisation count",
   "type": "stat",
   "description": "Shows total amount of organisations",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_orgs{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Users count",
   "type": "stat",
   "description": "Shows total amount of users",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_total_users{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "description": "Shows total amount of firing alerts",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_result_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Build Info",
   "type": "table",
   "description": "Shows statistics  about version and build of Grafana",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "time() - (grafana_build_info{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"} * on (instance, cluster) group_left process_start_time_seconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responce Codes and Logins for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Response Statuses",
     "type": "timeseries",
     "description": "Shoms total amount of http response status grouped by code and type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafana_api_response_status_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "API {{ code }}"
      },
      {
       "expr": "grafana_page_response_status_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "Page {{ code }}"
      },
      {
       "expr": "grafana_proxy_response_status_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "Proxy {{ code }}"
      }
     ]
    },
    {
     "title": "Login Counts",
     "type": "timeseries",
     "description": "Shows api login counters",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafana_api_login_post_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "POST"
      },
      {
       "expr": "grafana_api_login_oauth_total{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "OAuth"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "description": "Shows requests per second grouped by status code",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (status_code) (irate(grafana_http_request_duration_seconds_count{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[1m])) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "description": "Shows requests latency include percentile ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(grafana_http_request_duration_seconds_bucket{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "sum(irate(grafana_http_request_duration_seconds_sum{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])) * 1 / sum(irate(grafana_http_request_duration_seconds_count{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Get Stats for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Get Duration Quantiles",
     "type": "timeseries",
     "description": "summary for dashboard get duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "grafana_api_dashboard_get_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_get_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Get Duration Avg [5 min]",
     "type": "timeseries",
     "description": "average dashboard get duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[5m]) / rate(grafana_api_dashboard_get_milliseconds_count{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Save Stats for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Save Duration Quantiles",
     "type": "timeseries",
     "description": "Shows summary for dashboard save duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "grafana_api_dashboard_save_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_save_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Save Duration Avg [5 min]",
     "type": "timeseries",
     "description": "Shows average dashboard save duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_save_milliseconds_sum{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\",}[5m]) / rate(grafana_api_dashboard_save_milliseconds_count{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\",}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Search Stats for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dashboard Search Duration Quantiles",
     "type": "timeseries",
     "description": "Shows summary for dashboard search duration",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "grafana_api_dashboard_search_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.5\"}",
       "legendFormat": "0.5"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.9\"}",
       "legendFormat": "0.9"
      },
      {
       "expr": "grafana_api_dashboard_search_milliseconds{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\", quantile=\"0.99\"}",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Dashboard Search Duration Avg [5 min]",
     "type": "timeseries",
     "description": "Shows average dashboard search duration over 5 minutes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\",}[5m]) / rate(grafana_api_dashboard_search_milliseconds_count{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\",}[5m])",
       "legendFormat": "0.5"
      }
     ]
    }
   ]
  },
  {
   "title": "Datasource Stats for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Total  Requests To Datasource",
     "type": "timeseries",
     "description": "Show number of requests by code per datasource",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "grafana_datasource_request_total{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$instance\"}",
       "legendFormat": "{{code}}-{{datasource}}"
      }
     ]
    },
    {
     "title": "Datasource Request Duration Avg [5 min]",
     "type": "timeseries",
     "description": "Average datasource request duration over 5 minutes by code per datasource",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(grafana_datasource_request_duration_seconds_sum{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$instance\"}[5m]) / rate(grafana_datasource_request_duration_seconds_count{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{code}}-{{datasource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Plugins on $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana plugins",
     "type": "table",
     "description": "Shows installed plugins",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "grafana_plugin_build_info{cluster=\"$cluster\", pod=~\"$instance\", job=~\"$job\", namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}