{
 "title": "Home Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "prometheus_instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   },
   {
    "name": "alertmanager_instance",
    "query": {
     "query": "label_values(alertmanager_build_info, instance)"
    }
   },
   { "name": "interval", "query": "5m" },
   {
    "name": "prometheus_namespace",
    "query": {
     "query": "label_values(prometheus_build_info, namespace)"
    }
   },
   {
    "name": "kuber_dashboard",
    "query": {
     "query": "label_values(kube_ingress_path{ingress=~\"kubernetes-dashboard\"}, host)"
    }
   },
   {
    "name": "prometheus_UI",
    "query": {
     "query": "label_values(kube_ingress_path{exported_namespace=\"$prometheus_namespace\",service_port=\"9090\"}, host)"
    }
   },
   {
    "name": "alertmanager_UI",
    "query": {
     "query": "label_values(kube_ingress_path{exported_namespace=\"$prometheus_namespace\",service_port=\"9093\"}, host)"
    }
   },
   {
    "name": "monitoring_ns",
    "query": {
     "query": "label_values(kube_pod_container_status_ready{container=~\"vmagent\"},namespace)"
    }
   },
   {
    "name": "logging_ns",
    "query": {
     "query": "label_values(kube_pod_container_status_ready{container=~\"vlselect\"},namespace)"
    }
   },
   {
    "name": "tracing_ns",
    "query": {
     "query": "label_values(kube_pod_container_status_ready{container=~\"query-frontend\"},namespace)"
    }
   },
   {
    "name": "profiling_ns",
    "query": {
     "query": "label_values(kube_pod_container_status_ready{container=~\"pyroscope\"},namespace)"
    }
   },
   { "name": "monitoring_url", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Monitoring",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((min by (namespace) (kube_pod_container_status_running{namespace=\"$monitoring_ns\"})) * (sum by (namespace) (increase(kube_pod_container_status_restarts_total{namespace=\"$monitoring_ns\"}[5m]))<= bool 0) * (min by (namespace) (kube_deployment_spec_replicas{namespace=\"$monitoring_ns\"})) * (min by (namespace) (kube_statefulset_replicas{namespace=\"$monitoring_ns\"}))  * (max(increase(kube_events_warning_total{event_namespace=\"$monitoring_ns\"}[5m]))<= bool 0)) * on(namespace) group_left(namespace, host) kube_ingress_path{namespace=\"$monitoring_ns\",kube_namespace=~\"$monitoring_ns\", service_name=\"vmauth-k8s\", ingress=~\".*vmauth-k8s\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logging",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_running{namespace=\"$logging_ns\"}) * (sum(increase(kube_pod_container_status_restarts_total{namespace=\"$logging_ns\"}[5m])) <= bool 0 ) * (min(kube_deployment_spec_replicas{namespace=\"$logging_ns\"})) * (min(kube_statefulset_replicas{namespace=\"$logging_ns\"})) * (max(increase(kube_events_warning_total{event_namespace=\"$logging_ns\"}[5m])) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_running{namespace=\"$tracing_ns\"}) * (sum(increase(kube_pod_container_status_restarts_total{namespace=\"$tracing_ns\"}[5m])) <= bool 0 ) * (min(kube_deployment_spec_replicas{namespace=\"$tracing_ns\"})) * (min(kube_statefulset_replicas{namespace=\"$tracing_ns\"})) * (max(increase(kube_events_warning_total{event_namespace=\"$tracing_ns\"}[5m])) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Profiling",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_running{namespace=\"$profiling_ns\"}) * (sum(increase(kube_pod_container_status_restarts_total{namespace=\"$profiling_ns\"}[5m])) <= bool 0 ) * (min(kube_statefulset_replicas{namespace=\"$profiling_ns\"})) * (max(increase(kube_events_warning_total{event_namespace=\"$profiling_ns\"}[5m])) <= bool 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Quick Start Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 }
  },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 }
  },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 }
  },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 }
  },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 }
  },
  {
   "type": "dashlist",
   "description": "Check these first to get up and running",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 }
  },
  {
   "title": "Dashboards by Category (Browse by Topic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  { "title": "Platform", "type": "dashlist", "description": "Platform dashboards", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 } },
  { "title": "Middleware and DB", "type": "dashlist", "description": "Middleware and DB dashboards", "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 } },
  { "title": "Process", "type": "dashlist", "description": "Process dashboards", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 } }
 ]
}