{
 "title": "Kubernetes / Top Resources",
 "description": "Show first N (can be selected) resources by CPU, Memory, Disk usage",
 "tags": [
  "k8s",
  "top",
  "nodes",
  "pods",
  "namespaces"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   { "name": "topN", "query": "1,5,10,20,100" },
   {
    "name": "top_cpu_pods",
    "query": {
     "query": "query_result(topk($topN, sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", cluster=\"$cluster\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "top_mem_pods",
    "query": {
     "query": "query_result(topk($topN, sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (pod)))"
    }
   },
   {
    "name": "top_disk_read_pods",
    "query": {
     "query": "query_result(topk($topN, sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[${__range_s}s])) by (pod)))"
    }
   },
   {
    "name": "top_disk_write_pods",
    "query": {
     "query": "query_result(topk($topN, sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[${__range_s}s])) by (pod)))"
    }
   },
   {
    "name": "top_cpu_namespaces",
    "query": {
     "query": "query_result(topk($topN, sum by (namespace) (rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", cluster=\"$cluster\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "top_mem_namespaces",
    "query": {
     "query": "query_result(topk($topN, sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (namespace)))"
    }
   },
   {
    "name": "top_disk_read_namespaces",
    "query": {
     "query": "query_result(topk($topN, sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[${__range_s}s])) by (namespace)))"
    }
   },
   {
    "name": "top_disk_write_namespaces",
    "query": {
     "query": "query_result(topk($topN, sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[${__range_s}s])) by (namespace)))"
    }
   },
   {
    "name": "top_throttled_pods",
    "query": {
     "query": "query_result(topk($topN, rate(container_cpu_cfs_throttled_seconds_total[${__range_s}s])))"
    }
   },
   {
    "name": "top_cpu_nodes",
    "query": {
     "query": "query_result(topk($topN, (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\"}[${__range_s}s])) by (instance)) * 100))"
    }
   },
   {
    "name": "top_memory_nodes",
    "query": {
     "query": "query_result(topk($topN, (1 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\"})))) * 100))"
    }
   },
   {
    "name": "top_disk_read_nodes",
    "query": {
     "query": "query_result(topk($topN, max(irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[${__range_s}s])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (instance)))"
    }
   },
   {
    "name": "top_disk_write_nodes",
    "query": {
     "query": "query_result(topk($topN, max((irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[${__range_s}s])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"})) by (instance)))"
    }
   },
   { "name": "exclude_annotations", "label": "Exclude Annotations" }
  ]
 },
 "panels": [
  {
   "title": "Top pods by CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by CPU usage",
     "type": "timeseries",
     "description": "Show first $topN pods by CPU consumption.\nShow CPU usage in millicores, where `1000 millicores = 1 core`. In legend pods show as `namespace/pod`.",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", cluster=\"$cluster\", pod=~\"$top_cpu_pods\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{ namespace }}/{{ pod }}"
      }
     ]
    },
    {
     "title": "Top $topN by CPU usage",
     "type": "table",
     "description": "Show first $topN namespaces by CPU consumption.\nShow CPU usage as:\n* CPU usage in millicores per pods\n* CPU requests per pods\n* CPU limits per pods",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "sum(sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\", container!~\"^(.*POD.*|)$\", pod=~\"$top_cpu_pods\"}[$__rate_interval]))) by (namespace, pod) * 1000",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "sum(label_replace(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", pod=~\"$top_cpu_pods\", resource=\"cpu\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\"), \"pod\", \"$1\", \"pod\",\"(.*)\")) by (namespace, pod) * 1000",
       "legendFormat": "CPU Requests"
      },
      {
       "expr": "sum(label_replace(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", pod=~\"$top_cpu_pods\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\"), \"pod\", \"$1\", \"pod\",\"(.*)\")) by (namespace, pod) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Top pods by Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by Memory usage",
     "type": "timeseries",
     "description": "Show first $topN pods by Memory consumption.\nIn legend pods show as `namespace/pod`",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_mem_pods\"}) by (namespace, pod)",
       "legendFormat": "{{ namespace }}/{{ pod }}"
      }
     ]
    },
    {
     "title": "Top $topN by Memory usage",
     "type": "table",
     "description": "Show first $topN pods by Memory consumption.\nShow Memory usage as:\n* Memory usage per pod\n* Memory requests per pod\n* Memory limits per pod",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_mem_pods\"}) by (namespace, pod)",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "sum(label_replace(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", pod=~\"$top_mem_pods\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\"), \"pod\", \"$1\", \"pod\",\"(.*)\")) by (namespace, pod)",
       "legendFormat": "Memory Requests"
      },
      {
       "expr": "sum(label_replace(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", pod=~\"$top_mem_pods\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\"), \"pod\", \"$1\", \"pod\",\"(.*)\")) by (namespace, pod)",
       "legendFormat": "Memory Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Top pods by Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by Disk usage (Reads and Writes)",
     "type": "timeseries",
     "description": "Show first $topN pods by Disk consumption. In legend pods show as `namespace/pod`",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_disk_read_pods\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "{{ namespace }}/{{ pod }} - reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_disk_write_pods\"}[$__rate_interval])) by (namespace, pod) * -1",
       "legendFormat": "{{ namespace }}/{{ pod }} - writes"
      }
     ]
    },
    {
     "title": "Top $topN by Disk usage (Reads and Writes)",
     "type": "table",
     "description": "Show first $topN pods by Disk writes/reads consumption.\nShow Disk usage as:\n\n* Disk reads per seconds\n* Disk writes per seconds",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_disk_read_pods\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "Disk Reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", pod=~\"$top_disk_write_pods\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "Disk Writes"
      }
     ]
    }
   ]
  },
  { "title": "Top throttled pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top $topN throttled pods, rate by seconds",
   "type": "timeseries",
   "description": "Show first $topN pods which were throttled by CPU limits.\n\nShow as rate by `container_cpu_cfs_throttled_seconds_total`. It means that this graph should show how many time pod spend in throttling per second.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$top_throttled_pods\"}[$__range]))",
     "legendFormat": "{{ namespace }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Top namespaces by CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by CPU usage",
     "type": "timeseries",
     "description": "Show first $topN namespace by CPU consumption.\nShow CPU usage in millicores, where `1000 millicores = 1 core`.",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", cluster=\"$cluster\", namespace=~\"$top_cpu_namespaces\"}[$__rate_interval])) * 1000",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top $topN by CPU usage",
     "type": "table",
     "description": "Show first $topN namespaces by CPU consumption.\nShow CPU usage as:\n* Sum of CPU usage in millicores in specified namespace\n* Sum of CPU requests for all pods in specified namespace\n* Sum of CPU limits for all pods in specified namespace",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 41 },
     "targets": [
      {
       "expr": "sum(sum by (namespace) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_cpu_namespaces\"}[$__rate_interval]))) by (namespace) * 1000",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"$top_cpu_namespaces\", resource=\"cpu\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace) * 1000",
       "legendFormat": "CPU Requests"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=~\"$top_cpu_namespaces\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Top namespace by Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by Memory usage",
     "type": "timeseries",
     "description": "Show first $topN namespace by Memory consumption.",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_mem_namespaces\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top $topN by Memory usage",
     "type": "table",
     "description": "Show first $topN namespaces by Memory consumption.\nShow Memory usage as:\n* Sum of Memory usage in millicores in specified namespace\n* Sum of Memory requests for all pods in specified namespace\n* Sum of Memory limits for all pods in specified namespace",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_mem_namespaces\"}) by (namespace)",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=~\"$top_mem_namespaces\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)",
       "legendFormat": "Memory Requests"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", namespace=~\"$top_mem_namespaces\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)",
       "legendFormat": "Memory Limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Top namespaces by Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by Disk usage (Reads and Writes)",
     "type": "timeseries",
     "description": "Show first $topN namespaces by Disk consumption",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_disk_read_namespaces\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} - reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_disk_write_namespaces\"}[$__rate_interval])) by (namespace) * -1",
       "legendFormat": "{{ namespace }} - writes"
      }
     ]
    },
    {
     "title": "Top $topN by Disk usage (Reads and Writes)",
     "type": "table",
     "description": "Show first $topN namespaces by Disk writes/reads consumption.\nShow Disk usage as:\n\n* Disk reads per seconds\n* Disk writes per seconds",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_disk_read_namespaces\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Disk Reads"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\", namespace=~\"$top_disk_write_namespaces\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "Disk Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "Top nodes by CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by CPU usage, %",
     "type": "timeseries",
     "description": "Show first $topN Kubernetes/OpenShift nodes by CPU consumption.\nShow CPU usage as CPU total usage percent (CPU usage / CPU cores). \n\nBecause there are a lot CPU spaces this metric calculate as:\n\n`(1 - idle usage) * 100`\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\", instance=~\"$top_cpu_nodes\"}[$__rate_interval]) * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (node)) * 100",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Top $topN nodes by CPU usage",
     "type": "table",
     "description": "Show first $topN Kubernetes/OpenShift nodes by CPU consumption.\nShow CPU usage as:\n* CPU cores per nodes\n* CPU Load Average to last 5 minutes\n* CPU total usage percent (CPU usage / CPU cores)\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 128 },
     "targets": [
      {
       "expr": "(node_uname_info{cluster=\"$cluster\",instance=~\"$top_cpu_nodes\"} -0) * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}",
       "legendFormat": "Labels"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode='system',cluster=\"$cluster\",instance=~\"$top_cpu_nodes\"} * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (instance)",
       "legendFormat": "CPU"
      },
      {
       "expr": "node_load5{cluster=\"$cluster\",instance=~\"$top_cpu_nodes\"} * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}",
       "legendFormat": "CPU Last 5m Load"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\",instance=~\"$top_cpu_nodes\"}[$__rate_interval])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (instance)) * 100",
       "legendFormat": "CPU Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Top nodes by Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN nodes by Memory usage, %",
     "type": "timeseries",
     "description": "Show first $topN Kubernetes/OpenShift nodes by Memory consumption.\nShow Memory usage in percents from total node memory.\n\nAs base metrics use `node_memory_MemAvailable_bytes` to show used bytes per node\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"})* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}))) * 100",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Top $topN nodes by Memory usage",
     "type": "table",
     "description": "Show first $topN Kubernetes/OpenShift nodes by Memory consumption.\nShow Memory usage as:\n\n* Memory on node\n* Memory usage percent\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 129 },
     "targets": [
      {
       "expr": "(node_uname_info{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"} -0) * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}",
       "legendFormat": "Labels"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"} - 0) * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}",
       "legendFormat": "Memory"
      },
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$top_memory_nodes\"})* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}))) * 100",
       "legendFormat": "Memory Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Top nodes by Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topN by Disk usage (Reads and Writes)",
     "type": "timeseries",
     "description": "Show first $topN Kubernetes/OpenShift nodes by Disk consumption\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(irate(node_disk_read_bytes_total{cluster=\"$cluster\", instance=~\"$top_disk_read_nodes\"}[$__rate_interval])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (node)",
       "legendFormat": "{{ node }} - reads / sec"
      },
      {
       "expr": "max((irate(node_disk_written_bytes_total{cluster=\"$cluster\", instance=~\"$top_disk_write_nodes\"}[$__rate_interval])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"})) by (node) * -1",
       "legendFormat": "{{ node }} - writes / sec"
      }
     ]
    },
    {
     "title": "Top $topN nodes by Disk usage",
     "type": "table",
     "description": "Show first $topN Kubernetes/OpenShift nodes by Disk writes/reads consumption.\nShow Disk usage as:\n\n* Disk reads per seconds\n* Disk writes per seconds\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 130 },
     "targets": [
      {
       "expr": "(node_uname_info{cluster=\"$cluster\", instance=~\"($top_disk_read_nodes|$top_disk_write_nodes)\"} -0) * on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}",
       "legendFormat": "Labels"
      },
      {
       "expr": "max(irate(node_disk_read_bytes_total{cluster=\"$cluster\", instance=~\"$top_disk_read_nodes\"}[$__rate_interval])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"}) by (instance)",
       "legendFormat": "Disk Reads / sec"
      },
      {
       "expr": "max((irate(node_disk_written_bytes_total{cluster=\"$cluster\", instance=~\"$top_disk_write_nodes\"}[$__rate_interval])* on(node) group_left(label_kubernetes_io_hostname) kube_node_labels{label_kubernetes_io_hostname=~\".*\"})) by (instance)",
       "legendFormat": "Disk Writes / sec"
      }
     ]
    }
   ]
  }
 ]
}