{
 "title": "Kubernetes / API Server",
 "tags": [
  "k8s",
  "apiserver"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kubernetes / API Server Help",
     "type": "text",
     "description": "Describes some specific use cases for panels",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Most of the panels don't work in OpenShift v3.11\n\nThis is because API server metrics for Kubernetes change from version to version.\n\nIn this case, some panels can be fixed by replacing the names of the metrics with older ones. For example:\n\n`apiserver_request_total` -> `apiserver_request_count`"
     }
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API server status",
   "type": "stat",
   "description": "Shows API server status depending on the number of endpoints exposing metrics",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "API Servers",
   "type": "stat",
   "description": "Shows the number of running API servers  depending on the number of endpoints exposing metrics",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "Current Error Rate",
   "type": "stat",
   "description": "Show the current API server error rate: percentage of requests with errors out of the total number of requests",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(apiserver_request_total{cluster=\"$cluster\", code=~\"5..\", job=\"kube-apiserver\"}[$__rate_interval])) / sum(rate(apiserver_request_total{cluster=\"$cluster\", job=\"kube-apiserver\"}[$__rate_interval])))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Average API Server Latency",
   "type": "stat",
   "description": "Shows the average duration of request to API server",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{cluster=\"$cluster\", job=\"kube-apiserver\", verb!=\"WATCH\"}[$__rate_interval])) / sum(rate(apiserver_request_duration_seconds_count{cluster=\"$cluster\", job=\"kube-apiserver\", verb!=\"WATCH\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Average Etcd Requests Latency",
   "type": "stat",
   "description": "Shows the average duration of requests to Etcd",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_sum{cluster=\"$cluster\", job=\"kube-apiserver\"}[$__rate_interval])) / sum(rate(etcd_request_duration_seconds_count{cluster=\"$cluster\", job=\"kube-apiserver\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current Controller work queue Depth",
   "type": "stat",
   "description": "Show the current depth of controller work queue",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"$cluster\", job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "API server nodes status",
   "type": "status-history",
   "description": "Shows API server nodes status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(\r\n    up{job=\"kube-apiserver\", cluster=\"$cluster\"},\r\n    \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:.*)*\") \r\n* on(host_ip) group_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", host_network=\"true\"})\r\nor on (instance)\r\n(\r\nlabel_replace(\r\n    up{job=\"kube-apiserver\", cluster=\"$cluster\"},\r\n    \"pod\", \"$1\", \"instance\", \"(.+)\"\r\n    )\r\n)\r\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Shows the number of requests per second by each API server instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum by(instance)(\r\n        rate(apiserver_request_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])),\r\n    \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:.*)*\") \r\n* on(host_ip) group_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\n(\r\nlabel_replace(\r\n    sum by(instance)(rate(apiserver_request_total{job=\"kube-apiserver\", cluster=\"$cluster\", host_network=\"true\"}[$__rate_interval])),\r\n    \"pod\", \"$1\", \"instance\", \"(.+)\"\r\n    )\r\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request rate by verbs",
     "type": "timeseries",
     "description": "Shows the number of requests per second by verb",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(verb)(rate(apiserver_request_total{cluster=\"$cluster\", job=\"kube-apiserver\"}[$__rate_interval]))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Request Rate by resource and group",
     "type": "timeseries",
     "description": "Shows the number of requests per second by resource and its API group in format: API/resource",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(group, resource) (rate(apiserver_request_total{cluster=\"$cluster\", job=\"kube-apiserver\"}[$__rate_interval]))",
       "legendFormat": "{{group}}/{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request duration 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-apiserver\", verb!=\"WATCH\"}[$__rate_interval])))",
       "legendFormat": "Request duration 0.99 quantile"
      }
     ]
    },
    {
     "title": "Request duration by verb 0.99  quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile by verb: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-apiserver\", verb!=\"WATCH\"}[$__rate_interval])) by (verb, le))\r",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "Request duration by resource and group 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile by resource type and its API group: 99% of requests  . Format: API/resource\n",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (resource, group, le) (rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", job=\"kube-apiserver\", verb!=\"WATCH\"}[$__rate_interval])) )\r",
       "legendFormat": "{{group}}/{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API Server error percentage",
     "type": "timeseries",
     "description": "Shows the percentage of requests failed with 5xx error by each API server instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\r\n  label_replace(\r\n    sum by (instance) (rate(apiserver_request_total{code=~\"[4,5]..\",job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n    /\r\n    sum by (instance) (rate(apiserver_request_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n  * 100,\r\n  \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:.*)*\"\r\n  )\r\n)\r\n* on(host_ip) group_left(pod, node)\r\n  kube_pod_info{pod=~\"kube-apiserver.*\", host_network=\"true\"}\r\n  or on (instance)\r\n  (\r\n    label_replace(\r\n      sum by (instance) (rate(apiserver_request_total{code=~\"[4,5]..\",job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n      /\r\n      sum by (instance) (rate(apiserver_request_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n    * 100,\r\n    \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n    )\r\n  )",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error request rate by verb",
     "type": "timeseries",
     "description": "Show the number of requests per second failed with 5xx or 4xx code grouped by verb",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"[4,5]..\", job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Error request rate by code",
     "type": "timeseries",
     "description": "Show the number of requests per second failed with 5xx or 4xx code grouped by code",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (code) (rate(apiserver_request_total{code=~\"[4,5]..\", job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Adds to work queue per second",
     "type": "timeseries",
     "description": "Shows the number of adds to controller work queue per second",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (name)(rate(workqueue_adds_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Work queue depth",
     "type": "timeseries",
     "description": "Shows the current depth of controller work queue. It should be near 0",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name)(workqueue_depth{job=\"kube-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Item processing time 0.99  quantile",
     "type": "timeseries",
     "description": "Shows 0.99 duration quantile of the item processed from work queue: 99% of items has equal or less processing time",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(workqueue_work_duration_seconds_bucket{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "Processing time 0.99  quantile"
      }
     ]
    },
    {
     "title": "Item queue time 0.99 quantile",
     "type": "timeseries",
     "description": "Shows 0.99 duration quantile of the item stay work queue: 99% of items has equal or less staying time",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(workqueue_queue_duration_seconds_bucket{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "Queue time 0.99  quantile"
      }
     ]
    },
    {
     "title": "Unfinished work time",
     "type": "timeseries",
     "description": "Show time of unfinished item processing.  Large values indicate stuck threads",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (workqueue_unfinished_work_seconds{job=\"kube-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "Unfinished work time"
      }
     ]
    },
    {
     "title": "Longest running processor time",
     "type": "timeseries",
     "description": "Show longest time of item processing",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (workqueue_longest_running_processor_seconds{job=\"kube-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "Longest running processor time"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Etcd request rate",
     "type": "timeseries",
     "description": "Shows the number of requests per second sent to Etcd",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type)(rate(etcd_request_duration_seconds_count{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Etcd request duration 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(etcd_request_duration_seconds_bucket{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "Request duration 0.99 quantile"
      }
     ]
    },
    {
     "title": "Request duration 0.99 quantile by operation",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile by operation: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(etcd_request_duration_seconds_bucket{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request duration 0.99 quantile by object type",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile by object type: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (type, le) (rate(etcd_request_duration_seconds_bucket{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Objects stored in etcd",
     "type": "timeseries",
     "description": "Shows the number of objects stored in Etcd",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (resource)((apiserver_storage_objects{job=\"kube-apiserver\", cluster=\"$cluster\"}))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Shows the CPU usage by each API server instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace((sum by(instance)(rate(process_cpu_seconds_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n), \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\r\n)\r\n* on(host_ip) group_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\nlabel_replace((sum by(instance)(rate(process_cpu_seconds_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))\r\n), \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Shows the number of goroutines by each API server instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(\r\n\tgo_goroutines{job=\"kube-apiserver\", cluster=\"$cluster\"}, \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\r\n) * on(host_ip) \r\ngroup_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\nlabel_replace(\r\n\tgo_goroutines{job=\"kube-apiserver\", cluster=\"$cluster\"}, \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "description": "Show the resident memory usage by each API server instance",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n\tprocess_resident_memory_bytes{job=\"kube-apiserver\", cluster=\"$cluster\"}, \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\r\n) * on(host_ip) \r\ngroup_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\nlabel_replace(\r\n\tprocess_resident_memory_bytes{job=\"kube-apiserver\", cluster=\"$cluster\"}, \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Allocated memory",
     "type": "timeseries",
     "description": "Shows the allocated  memory  by each API server instance",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n\tsum by (instance) (go_memstats_alloc_bytes{job=\"kube-apiserver\", cluster=\"$cluster\"}), \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\r\n) * on(host_ip) \r\ngroup_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\nlabel_replace(\r\n\tsum by (instance) (go_memstats_alloc_bytes{job=\"kube-apiserver\", cluster=\"$cluster\"}), \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Allocations per second",
     "type": "timeseries",
     "description": "Shows the memory allocations per second by each instance",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace(\r\n\tsum by(instance)(rate(go_memstats_alloc_bytes_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])), \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\r\n) * on(host_ip) \r\ngroup_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", cluster=\"$cluster\", host_network=\"true\"})\r\nor on (instance)\r\nlabel_replace(\r\n\tsum by(instance)(rate(go_memstats_alloc_bytes_total{job=\"kube-apiserver\", cluster=\"$cluster\"}[$__rate_interval])), \"pod\", \"$1\", \"instance\", \"(.*)\"\r\n)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}