{
 "title": "Kubernetes / Nodes Resources",
 "tags": [
  "k8s",
  "nodes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_uname_info, cluster)"
    }
   },
   {
    "name": "node_label",
    "query": {
     "query": "kube_node_labels{cluster=\"$cluster\"}"
    }
   },
   {
    "name": "node_label_value",
    "query": {
     "query": "label_values(kube_node_labels{cluster=\"$cluster\"}, label_$node_label)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "query_result(node_uname_info{cluster=\"$cluster\"} * on(node) group_left(label_${node_label}) kube_node_labels{cluster=\"$cluster\", label_${node_label}=~\"$node_label_value\"})"
    }
   },
   {
    "name": "mount",
    "label": "mount",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*|.*runs.*\",cluster=\"$cluster\", node=~\"$node\"}, mountpoint)"
    }
   },
   {
    "name": "interface",
    "label": "network interface",
    "query": {
     "query": "label_values(node_network_info{cluster=\"$cluster\", node=~\"$node\", device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*|cali.*'},device)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"}, job)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Overview",
     "type": "table",
     "description": "Shows cluster nodes overview: \n  * Node Uptime\n  * Total available CPU and RAM on node\n  * Overall resources usage on node\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(node_uname_info{cluster=\"$cluster\"} -0) * on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}",
       "legendFormat": "Labels"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{cluster=\"$cluster\"} * on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance) ",
       "legendFormat": "Uptime"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - 0) * on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}",
       "legendFormat": "Memory"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode='system',cluster=\"$cluster\"} * on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance)",
       "legendFormat": "CPU"
      },
      {
       "expr": "node_load5{cluster=\"$cluster\"} * on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}",
       "legendFormat": "CPU Last 5m Load"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\"}[$__rate_interval])* on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance)) * 100",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\"})* on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}))) * 100",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}) * 100 / (node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"} + (node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"} - node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}))* on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance)",
       "legendFormat": "Disk Space Usage"
      },
      {
       "expr": "max(irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval])* on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance)",
       "legendFormat": "Disk Reads / sec"
      },
      {
       "expr": "max((irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[$__rate_interval])* on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"})) by (instance)",
       "legendFormat": "Disk Writes / sec"
      }
     ]
    },
    {
     "title": "Overall CPU Load And Usage",
     "type": "timeseries",
     "description": "Shows overall CPU average load on all nodes and CPU usage against total number of CPU cores\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{cluster=\"$cluster\",job=\"node-exporter\", mode='system'} *on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) ",
       "legendFormat": "CPU Cores"
      },
      {
       "expr": "avg(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[$__range]) *on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (instance)) * 100",
       "legendFormat": "Overall CPU Usage"
      },
      {
       "expr": "sum(node_load5{cluster=\"$cluster\",job=\"node-exporter\"} *on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"})",
       "legendFormat": "Total 5m load"
      }
     ]
    },
    {
     "title": "Overall Memory Usage",
     "type": "timeseries",
     "description": "Shows overall RAM usage for all nodes against total available RAM on all nodes\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",job=\"node-exporter\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "(sum((node_memory_MemTotal_bytes{cluster=\"$cluster\",job=\"node-exporter\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\",job=\"node-exporter\"})*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",job=\"node-exporter\"} *on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"})) * 100",
       "legendFormat": "Memory Usage"
      }
     ]
    },
    {
     "title": "Overall Disk Usage",
     "type": "timeseries",
     "description": "Shows overall disk space usage for all nodes  against total available disk space on all nodes\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(avg(node_filesystem_size_bytes{cluster=\"$cluster\", job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance))",
       "legendFormat": "Total"
      },
      {
       "expr": "(sum(avg(node_filesystem_size_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance)) - sum(avg(node_filesystem_free_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance))) * 100 / (sum(avg(node_filesystem_avail_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance)) + (sum(avg(node_filesystem_size_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance)) - sum(avg(node_filesystem_free_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (device,instance))))",
       "legendFormat": "Disk Space Usage"
      }
     ]
    },
    {
     "title": "Disk I/O utilization  per node",
     "type": "timeseries",
     "description": "Shows data read/write per node\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[])*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (node)",
       "legendFormat": "{{ node}} - reads bytes"
      },
      {
       "expr": "sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[])*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (node)",
       "legendFormat": "{{ node}} -  written bytes"
      }
     ]
    },
    {
     "title": "IOps per node",
     "type": "timeseries",
     "description": "Count of writes/reads completed\n  * Can be grouped by node_label\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (node)",
       "legendFormat": "{{ node}} reading"
      },
      {
       "expr": "sum (rate(container_fs_writes_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])*on(node) group_left(label_$node_label) kube_node_labels{label_$node_label=~\"$node_label_value\"}) by (node)",
       "legendFormat": "{{ node}} writing"
      }
     ]
    }
   ]
  },
  { "title": "Node: $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Show the node uptime",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{cluster=\"$cluster\", node=\"${node:raw}\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Quota",
   "type": "stat",
   "description": "Shows total available CPU cores on the node",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cluster=\"$cluster\",mode='system',node=\"${node:raw}\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Shows brief info about resources usage on the node: \n* CPU\n* RAM\n* Disk Space\n* Swap",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\", node=\"${node:raw}\"}[$__rate_interval])) * 100)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\", node=\"${node:raw}\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\", node=\"${node:raw}\"})))* 100",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "((node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint=\"/\",node=\"${node:raw}\"} - node_filesystem_free_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint=\"/\",node=\"${node:raw}\"}) / node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint=\"/\",node=\"${node:raw}\"}) * 100 ",
     "legendFormat": "Used Disk Space"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} + 1) / (node_memory_SwapTotal_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT?/XFS)",
   "type": "table",
   "description": "Shows the node disk info: \n* Space usage\n* Available disk space,\n* Disk usage rate\n\nThe data is coming from the 'df' command. The 'Used' column algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\", node=\"${node:raw}\"} ) - 0",
     "legendFormat": "Disk Size"
    },
    {
     "expr": "(node_filesystem_avail_bytes {cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\", node=\"${node:raw}\"} ) - 0",
     "legendFormat": "Disk Free"
    },
    {
     "expr": "(node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\", node=\"${node:raw}\"} - node_filesystem_free_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\", node=\"${node:raw}\"}) * 100 / (node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint !~\".*pod.*\", node=\"${node:raw}\"}) ",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "description": "Shows the node CPU iowait as a percentage of total available CPU on the node",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\", node=\"${node:raw}\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "stat",
   "description": "Shows total available RAM on the node",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", node=\"${node:raw}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used PIDs / Threads",
   "type": "stat",
   "description": "Shows the node PIDs and threads current used count",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processes_pids{cluster=\"$cluster\", node=\"${node:raw}\"}",
     "legendFormat": "PIDs"
    },
    {
     "expr": "node_processes_threads{cluster=\"$cluster\", node=\"${node:raw}\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Max PIDs / Threads",
   "type": "stat",
   "description": "Shows the node PIDs and threads limits per node",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processes_max_processes{cluster=\"$cluster\"} * on(instance) group_left(nodename) (node_uname_info{cluster=\"$cluster\",nodename=\"${node:raw}\"})",
     "legendFormat": "PIDs"
    },
    {
     "expr": "node_processes_max_threads{cluster=\"$cluster\"} * on(instance) group_left(nodename) (node_uname_info{cluster=\"$cluster\",nodename=\"${node:raw}\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "Shows detailed information about Disk Space usage on the node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint=\"/\",node=\"${node:raw}\"} - node_filesystem_free_bytes{cluster=\"$cluster\",fstype=~\"ext.*|xfs\", mountpoint=\"/\",node=\"${node:raw}\"}",
     "legendFormat": "Disk Space usage"
    }
   ]
  },
  {
   "title": "Count of Volumes",
   "type": "table",
   "description": "Shows count of volumes by state and type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "volume_manager_total_volumes{cluster=\"$cluster\",node=\"${node:raw}\", state=\"desired_state_of_world\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "volume_manager_total_volumes{cluster=\"$cluster\", node=\"${node:raw}\", state=\"actual_state_of_world\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows detailed information about CPU usage on the node",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"system\",node=\"${node:raw}\"}[$__rate_interval])) * 100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"user\",node=\"${node:raw}\"}[$__rate_interval])) * 100",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\",node=\"${node:raw}\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\",node=\"${node:raw}\"}[$__rate_interval])))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Stalled",
   "type": "timeseries",
   "description": "Shows CPU stall in seconds on the node",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__range]))",
     "legendFormat": "${node:raw}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows detailed information about memory usage on the node",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=\"${node:raw}\"}) ",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=\"${node:raw}\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\",node=\"${node:raw}\"}))) * 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Memory Stalled",
   "type": "timeseries",
   "description": "Shows memory stall in seconds on the node",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_memory_stalled_seconds_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__range]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "Shows average system load for 1m, 5m, 15m on the node",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{cluster=\"$cluster\",mode='system',node=\"${node:raw}\"}) by (cpu, instance)) ",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Internet Traffic Per  For $interface",
   "type": "timeseries",
   "description": "Shows incoming and outcoming internet traffic in bytes on the node grouped by the time specified in the 'Interval' variable.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{cluster=\"$cluster\",device=~\"$interface\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "Receive: {{device}}"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{cluster=\"$cluster\",device=~\"$interface\",node=\"${node:raw}\"}[$__rate_interval])",
     "legendFormat": "Transmit: {{device}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth Per Second For $interface",
   "type": "timeseries",
   "description": "Shows network outcoming and incoming traffic in bytes per seconds on the node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{cluster=\"$cluster\",device=~\"$interface\",node=\"${node:raw}\"}[$__rate_interval])  * 8",
     "legendFormat": "Receive: {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{cluster=\"$cluster\",device=~\"$interface\",node=\"${node:raw}\"}[$__rate_interval]) * 8",
     "legendFormat": "Transmit: {{device}}"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "timeseries",
   "description": "Shows sockets information on the node:\n\n* Sockets_used - sockets currently in use\n* CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n* TCP_alloc - Allocated sockets\n* TCP_tw - Sockets wating close\n* UDP_inuse - Udp sockets currently in use\n* RetransSegs - TCP retransmission packets\n* OutSegs - Number of packets sent by TCP\n* InSegs - Number of packets received by TCP",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{cluster=\"$cluster\",node=\"${node:raw}\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Sockets Used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "description": "Shows disk space usage by the mounts selected in the 'Mount' variable on the node",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cluster=\"$cluster\", node=\"${node:raw}\",fstype=~\"ext.*|xfs\",mountpoint!~\".*pods.*|.*run.*\"} - node_filesystem_free_bytes{cluster=\"$cluster\", node=\"${node:raw}\",fstype=~\"ext.*|xfs\",mountpoint!~\".*pods.*|.*run.*\"}) / (node_filesystem_size_bytes{cluster=\"$cluster\", node=\"${node:raw}\",fstype=~\"ext.*|xfs\",mountpoint!~\".*pods.*|.*run.*\"}) ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data (bytes / sec)",
   "type": "timeseries",
   "description": "Shows per second disk read / write bytes on the node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval])",
     "legendFormat": "Write: {{device}}"
    }
   ]
  },
  {
   "title": "Open  File Descriptor / Context switches",
   "type": "timeseries",
   "description": "Shows current amount of opened filed descriptors and context switches for the node",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{cluster=\"$cluster\",node=\"${node:raw}\"}",
     "legendFormat": "Used Descriptors"
    },
    {
     "expr": "irate(node_context_switches_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval])",
     "legendFormat": "Switches"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "Shows time spent on I/O in the natural time of each second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "IO Time: {{device}}"
    }
   ]
  },
  {
   "title": "Disk stalled time, sec",
   "type": "timeseries",
   "description": "Shows node time spent stalled on disk",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_io_stalled_seconds_total{cluster=\"$cluster\",node=\"${node:raw}\"}[$__range]))",
     "legendFormat": "IO Time: {{device}}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "description": "Shows amount of physical IOs (reads and writes) on different devices.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=~\"$diskdevices\",node=\"${node:raw}\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=~\"$diskdevices\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "description": "Shows the volume of disks operations (read and write)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"$diskdevices\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"$diskdevices\",node=\"${node:raw}\"}[$__rate_interval]) ",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "timeseries",
   "description": "Total seconds spent doing I/Os",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=~\"$diskdevices\",node=\"${node:raw}\"} [$__rate_interval]) ",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  },
  {
   "title": "PIDs Number and Limit",
   "type": "timeseries",
   "description": "Shows amount of used processes (PIDs) and process limit on node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_pids{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Number of PIDs"
    },
    {
     "expr": "node_processes_max_processes{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "PIDs limit"
    }
   ]
  },
  {
   "title": "Threads Number and Limit",
   "type": "timeseries",
   "description": "Shows amount of used threads and threads limit on node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_threads{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Allocated threads"
    },
    {
     "expr": "node_processes_max_threads{cluster=\"$cluster\",node=\"${node:raw}\"} ",
     "legendFormat": "Threads limit"
    }
   ]
  }
 ]
}