{
 "title": "Kubernetes / Pods Distribution By Zones",
 "description": "This dashboard shows extended statistics about distribution pods by zone",
 "tags": [
  "k8s",
  "pods",
  "zones"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_state_metrics_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "label_type",
    "label": "Label Type",
    "query": "any : [^\"\\,=]*, zone : zone"
   },
   {
    "name": "label",
    "label": "Node Label",
    "query": {
     "query": "kube_node_labels{cluster=\"$cluster\"}"
    }
   },
   { "name": "zone", "label": "Zone/Label values", "query": { "query": "label_values(label_${label})" } },
   {
    "name": "threshold",
    "label": "Number of Zones",
    "query": {
     "query": "query_result(count(count by (label_${label}) (kube_node_labels{cluster=\"$cluster\"})))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview for zone:  $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "zone" },
  {
   "title": "Number of nodes $zone",
   "type": "stat",
   "description": "Shows number of nodes for $zone",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition)\r\n(\r\n(kube_node_status_condition{cluster=\"$cluster\", status=\"true\"} == 1) * on (cluster, node) group_left()\r\nkube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}\r\n)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Number of CPUs $zone",
   "type": "stat",
   "description": "Shows number of  CPU for $zone",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\r\n(\r\n(count by (cluster, node) (node_cpu_seconds_total{mode=\"idle\", node!=\"\", job=\"node-exporter\"})) * on (cluster, node) group_left()\r\nkube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM $zone",
   "type": "stat",
   "description": "Shows amount of memory for $zone",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\r\n(\r\n(node_memory_MemTotal_bytes{node!=\"\", job=\"node-exporter\"}) * on (cluster, node) group_left()\r\nkube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used RAM $zone",
   "type": "stat",
   "description": "Shows  amount of used memory for $zone",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum\r\n(\r\n(node_memory_MemTotal_bytes{node!=\"\", job=\"node-exporter\"} - node_memory_MemFree_bytes{node!=\"\", job=\"node-exporter\"}) * on (cluster, node) group_left()\r\nkube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of pods $zone",
   "type": "stat",
   "description": "Shows number of pods for $zone",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase)\r\n(\r\n(kube_pod_info{cluster=\"$cluster\"} * on (cluster, namespace, pod) group_left(phase) (kube_pod_status_phase{cluster=\"$cluster\"} == 1))\r\n * on (cluster, node) group_left()\r\nkube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}\r\n)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pods distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ready Deployment Pods distribution per zones",
     "type": "table",
     "description": "Shows number of pods with ready=true status per Zones for kind: Deployment",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "label_join(\r\n  sum by (deployment, namespace, zone)\r\n  (\r\n    (\r\n      (\r\n        label_replace(kube_pod_owner{owner_kind=\"ReplicaSet\", cluster=\"$cluster\", namespace=~\"$namespace\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\")\r\n        * on (cluster, namespace, replicaset) group_left(deployment)\r\n        label_replace(kube_replicaset_owner{cluster=\"$cluster\", namespace=~\"$namespace\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")\r\n      ) * on (cluster, namespace, pod) group_left()\r\n      (\r\n        kube_pod_status_ready{cluster=\"$cluster\", namespace=~\"$namespace\", condition=\"true\"}==1\r\n      )\r\n    ) * on (cluster, namespace, pod) group_left(node, zone)\r\n    (\r\n      kube_pod_info * on (cluster, node) group_left(zone)\r\n      label_replace(kube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}, \"zone\", \"$1\", \"label_${label}\", \"(.*)\")\r\n    )\r\n  )\r\n  , \"Microservice\", \"\\t|\\t\", \"namespace\", \"deployment\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ready StatefulSet Pods distribution per zones",
     "type": "table",
     "description": "Shows number of pods with ready=true status per Zones for Kind: StatefulSet",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "label_join(\r\n  sum by (statefulset, namespace, zone)\r\n  (\r\n    (\r\n      (\r\n        label_replace(kube_pod_owner{owner_kind=\"StatefulSet\", cluster=\"$cluster\", namespace=~\"$namespace\"}, \"statefulset\", \"$1\", \"owner_name\", \"(.*)\")\r\n      ) * on (cluster, namespace, pod) group_left()\r\n      (\r\n        kube_pod_status_ready{cluster=\"$cluster\", namespace=~\"$namespace\", condition=\"true\"}==1\r\n      )\r\n    ) * on (cluster, namespace, pod) group_left(node, zone)\r\n    (\r\n      kube_pod_info * on (cluster, node) group_left(zone)\r\n      label_replace(kube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}, \"zone\", \"$1\", \"label_${label}\", \"(.*)\")\r\n    )\r\n  )\r\n  , \"Microservice\", \"\\t|\\t\", \"namespace\", \"statefulset\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ready DaemonSet Pods distribution per zones",
     "type": "table",
     "description": "Shows number of pods with ready=true status per Zones for Kind: DaemonSet",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "label_join(\r\n  sum by (daemonset, namespace, zone)\r\n  (\r\n    (\r\n      (\r\n        label_replace(kube_pod_owner{owner_kind=\"DaemonSet\", cluster=\"$cluster\", namespace=~\"$namespace\"}, \"daemonset\", \"$1\", \"owner_name\", \"(.*)\")\r\n      ) * on (cluster, namespace, pod) group_left()\r\n      (\r\n        kube_pod_status_ready{cluster=\"$cluster\", namespace=~\"$namespace\", condition=\"true\"}==1\r\n      )\r\n    ) * on (cluster, namespace, pod) group_left(node, zone)\r\n    (\r\n      kube_pod_info * on (cluster, node) group_left(zone)\r\n      label_replace(kube_node_labels{cluster=\"$cluster\", label_${label}=~\"$zone\"}, \"zone\", \"$1\", \"label_${label}\", \"(.*)\")\r\n    )\r\n  )\r\n  , \"Microservice\", \"\\t|\\t\", \"namespace\", \"daemonset\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}