{
 "title": "Kubernetes / Pods Distribution By Node",
 "tags": [
  "k8s",
  "nodes",
  "pods"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of pods",
   "type": "stat",
   "description": "Shows the number of pods running on the node",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum by (node,pod) (kube_pod_info{cluster=\"$cluster\", node=~\"$node\"})) "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Shows CPU usage on the node",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (\rrate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", node=~\"$node\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows memory usage on the node",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", container!~\"^(.*POD.*|)$\", image!=\"\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\", node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"})",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows detailed CPU usage per pod on the node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (\r\nrate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "description": "Shows CPU usage, requests and limits per pod on the node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(sum by (namespace, pod, container) (\r\nrate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])\r\n)) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])\r\n              )) by (pod) / sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", node=~\"$node\", resource=\"cpu\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(sum by (namespace, pod, container) (\r\nrate(container_cpu_usage_seconds_total{luster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))) by (pod) / sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(sum by (namespace, pod, container) (\r\nrate(container_cpu_usage_seconds_total{cluster=\"$cluster\", node=~\"$node\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])\r\n)) by (namespace, pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows detailed memory usage per pod on the node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\", container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "description": "Shows memory usage, requests and limits per pod on the node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod) / sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod) / sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", node=~\"$node\"},\"pod\",\"$1\",\"pod\",\"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", node=~\"$node\",container!~\"^(.*POD.*|)$\", image!=\"\"}) by (namespace, pod)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Receive Bytes By Pods",
     "type": "timeseries",
     "description": "Shows received bytes by pods in current namespace",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bytes By Pods",
     "type": "timeseries",
     "description": "Shows transmitted bytes by pods in current namespace",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Packets / Drops By Pods",
     "type": "timeseries",
     "description": "Shows received packets and received packets drops by pods in current namespace",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Drops: {{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Packets / Drops By Pods",
     "type": "timeseries",
     "description": "Shows transmitted packets and transmitted packets drops by pods in current namespace",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Transmit: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Drops: {{pod}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth",
     "type": "timeseries",
     "description": "Shows overall network receive/transmit bytes in current node",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Received: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "Transmitted: {{pod}}"
      }
     ]
    },
    {
     "title": "Network By Pod",
     "type": "table",
     "description": "Shows general information about the network on the current node",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (namespace, pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)"
      }
     ]
    },
    {
     "title": "Open Sockets By Pod",
     "type": "timeseries",
     "description": "Number of open sockets for the pod.\nNOTE: Panel shows information about open sockets only for Kubernetes v1.21+ and Openshift v4.x. Openshift v3.11 and less doesn't support metrics about sockets.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (container_sockets{cluster=\"$cluster\", node=~\"$node\", pod!=\"\"}) by (pod)",
       "legendFormat": "pod: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Read Bytes Per Pods",
     "type": "timeseries",
     "description": "Shows the average filesystem reads in bytes for the current node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Written Bytes Per Pods",
     "type": "timeseries",
     "description": "Shows the average filesystem writes in bytes for the current node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Reads Per Pods",
     "type": "timeseries",
     "description": "Shows the average successful reads operation for the current node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Writes Per Pods",
     "type": "timeseries",
     "description": "Shows the average successful writes operation for the current node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk By Pod",
     "type": "table",
     "description": "Shows general information about the disk on the current node",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (namespace, pod)"
      },
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (namespace, pod)"
      },
      {
       "expr": "sum(irate(container_fs_reads_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (namespace, pod)"
      },
      {
       "expr": "sum(irate(container_fs_writes_total{cluster=\"$cluster\", node=\"$node\", name!=\"\"}[$__rate_interval])) by (namespace, pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Help",
     "type": "text",
     "description": "Information about panels on this row",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "options": {
      "content": "# Help\n\n`CSI PVs space usage` panel displays space usage per node by Persistent Volumes based on CSI storage classes.\nThis panel **doesn't show info about Local, Host Path or NFS storages**.\nThe panel shows connections between PVCs, PVs and pod volumes.\n\n`Space Info` panel shows information about space consumtion per node by devices.\nWorks only for `xfs` or `ext.*` file systems."
     }
    },
    {
     "title": "CSI PVs space usage",
     "type": "table",
     "description": "Shows information about space consumption for persistent volumes powered by CSI drivers (except NFS storages)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum(\r\n  kubelet_volume_stats_used_bytes{cluster=\"$cluster\", node=\"$node\"}\r\n) \r\nby (namespace, node, persistentvolumeclaim)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\r\n  kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", node=\"$node\"}\r\n) \r\nby (namespace, node, persistentvolumeclaim)",
       "legendFormat": "__auto"
      },
      {
       "expr": "group(kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=\"$cluster\"}) by (namespace, pod, persistentvolumeclaim, volume, uid)",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_replace(\r\n  group(\r\n    kube_persistentvolumeclaim_info{cluster=\"$cluster\"}\r\n  ) \r\n  by (namespace, persistentvolumeclaim, volumename)\r\n, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\") \r\n* \r\non(persistentvolume) \r\ngroup_left(nfs_server) \r\n(\r\n  group(\r\n    kube_persistentvolume_info{cluster=\"$cluster\"}\r\n  ) \r\n  by (persistentvolume, nfs_server)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Space Info",
     "type": "timeseries",
     "description": "Shows the filesystem usage for each device and mountpoint",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{node=\"$node\", fstype=~\"(xfs|ext.*)\"} - node_filesystem_free_bytes{node=\"$node\", fstype=~\"(xfs|ext.*)\"}",
       "legendFormat": "Usage {{device}} : {{mountpoint}}"
      },
      {
       "expr": "node_filesystem_size_bytes{node=\"$node\", fstype=~\"(xfs|ext.*)\"}",
       "legendFormat": "Total {{device}} : {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "💡Help",
     "type": "text",
     "description": "Show information about panels in current section",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
     "options": {
      "content": "# File Descriptors and Threads\n\nPanels in this section show information about FDs and Threads only for Kubernetes v1.21+ and Openshift v4.x. Openshift v3.11 and less doesn't support metrics about FDs and Threads. \n"
     }
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors for the pod. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(container_file_descriptors{cluster=\"$cluster\",node=~\"$node\", pod!=\"\"}) by (pod)",
       "legendFormat": "pod: {{pod}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Number of threads running inside the pod.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(container_threads{cluster=\"$cluster\",node=~\"$node\", pod!=\"\"}) by (pod)",
       "legendFormat": "pod: {{pod}}"
      }
     ]
    },
    {
     "title": "File Descriptors Quota",
     "type": "table",
     "description": "Shows file descriptors, threads and limits per pod and container on the node.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{cluster=\"$cluster\",node=~\"$node\", pod!=\"\", container!~\"^(.*POD.*|)$\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "container_threads{cluster=\"$cluster\",node=~\"$node\", pod!=\"\", container!~\"^(.*POD.*|)$\"}"
      },
      {
       "expr": "container_ulimits_soft{cluster=\"$cluster\",node=~\"$node\", container!~\"^(.*POD.*|)$\"}"
      },
      {
       "expr": "container_threads_max{cluster=\"$cluster\",node=~\"$node\", container!~\"^(.*POD.*|)$\"}"
      }
     ]
    }
   ]
  }
 ]
}