{
 "title": "Kubernetes / Pod Resources",
 "tags": [
  "k8s",
  "pods"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "controller",
    "label": "controller",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"},created_by_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\", created_by_name=~\"$controller\"},pod)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview (Namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods, per Namespace",
     "type": "stat",
     "description": "Show the number of pods running in the namespace",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{cluster=\"$cluster\",namespace=~\"$namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Container status, per Namespace",
     "type": "stat",
     "description": "Show the count of containers in  Waiting, and Terminated statuses.",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by(namespace)(kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", namespace=\"$namespace\"} == 1)  OR on() vector(0)",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum by(namespace)(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason!=\"Completed\"} == 1)  OR on() vector(0)",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "Last Restart Time",
     "type": "stat",
     "description": "Shows the time of the last restart of the pod in the selected time range",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max_over_time(timestamp(rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) > 0)[7d:]) * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Last Deployment Time",
     "type": "stat",
     "description": "Shows the last time of pod deployed",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_created{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"} * 1000",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pod Status",
     "type": "state-timeline",
     "description": "Shows pod states",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(\n(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", phase=\"Failed\"} * 2)\nor (kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", phase=\"Pending\"} * 4)\nor (kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", phase=\"Running\"} * 8)\nor (kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", phase=\"Succeeded\"} * 16)\nor (kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", phase=\"Unknown\"} * 32)\n) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Container Restarts, per Namespace",
     "type": "timeseries",
     "description": "Shows restarts of each container in the namespace",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "{{pod}} : {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container status, per Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Not healthy pods, per Namespace",
     "type": "table",
     "description": "Show information about the reason the container is currently in waiting or terminated state",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{cluster=~\"$cluster\",namespace=\"$namespace\"} == 1",
       "legendFormat": "__auto"
      },
      {
       "expr": "kube_pod_container_status_terminated_reason{cluster=~\"$cluster\",namespace=\"$namespace\",reason!=\"Completed\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last terminated status, per Namespace",
     "type": "table",
     "description": "Show information about the last reason the container was in terminated state",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason!=\"Completed\"} == 1",
       "legendFormat": "{{pod}}-{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage $pod",
     "type": "timeseries",
     "description": "Shows CPU usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(\r\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])\r\n) by (namespace, pod, container)) by (pod,container)",
       "legendFormat": "usage: {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\"}) by (pod,container)\n",
       "legendFormat": "requests: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\"}) by (pod,container)\n",
       "legendFormat": "limits: {{ container }}"
      }
     ]
    },
    {
     "title": "CPU Throttled, Stalled in seconds $pod",
     "type": "timeseries",
     "description": "Shows CPU Throttled, Stalled in seconds\n\nShow as rate by `container_cpu_cfs_throttled_seconds_total`. It means that this graph should show how many time pod spend in throttling per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "Throttled {{ pod }}"
      },
      {
       "expr": "sum by (pod)(rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "Stalled {{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Usage over requests, limits. Stalled, Throttled time $pod",
     "type": "table",
     "description": "Shows CPU Usage over requests, limits. Stalled, Throttled time by pod",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "sum(sum by (namespace, container, name) (\r\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])\r\n)) by (container)\r\n/\r\nsum(kube_pod_container_resource_requests{cluster=\"$cluster\",  namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", resource=\"cpu\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", resource=\"cpu\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum by (namespace, container, name) (\r\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])\r\n)) by (container)\r\n/\r\nsum(kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", resource=\"cpu\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum by (namespace, container, image) (\r\n    rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])\r\n)) by (container, image)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(sum by (namespace, container, image) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause\", name!=\"\"}[$__rate_interval]))) by (container, image)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage $pod",
     "type": "timeseries",
     "description": "Shows memory usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", container!~\"POD|pause|\", image!=\"\"}) by (container)",
       "legendFormat": "usage: {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by(container)\n",
       "legendFormat": "requests: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by(container)\n",
       "legendFormat": "limits: {{ container }}"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!=\"POD\", container!=\"\", image=~\".*\"}) by (container)\n",
       "legendFormat": "rss: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory Stalled in seconds $pod",
     "type": "timeseries",
     "description": "Shows Memory Stalled in seconds\n\nShow as rate by `container_cpu_cfs_throttled_seconds_total`. It means that this graph should show how many time pod spend in throttling per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_pressure_memory_stalled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage over requests, limits. stalled time  $pod",
     "type": "table",
     "description": "Shows Memory Usage over requests, limits. stalled time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", container!~\"POD|pause|\", image!=\"\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"POD|pause|\", pod=~\"$pod\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"POD|pause|\", pod=~\"$pod\", container!~\"POD|pause|\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=~\"$pod\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_cache{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container != \"\", container != \"POD\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", container!~\"POD|pause|\", image!=\"\"}) by (image, container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (container)(rate(container_pressure_memory_stalled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O utilization $pod",
     "type": "timeseries",
     "description": "Shows data read/write per container",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": "{{ container }}: {{ device }} reads"
      },
      {
       "expr": "rate(container_fs_writes_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": "{{ container }}: {{ device }} write"
      }
     ]
    },
    {
     "title": "Container IOps $pod",
     "type": "timeseries",
     "description": "Count of writes/reads completed",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": " {{ container}} : {{ device }} reading"
      },
      {
       "expr": "rate(container_fs_writes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": "{{ container}} : {{ device }} writing"
      }
     ]
    },
    {
     "title": "Container Disk Stalled $pod",
     "type": "timeseries",
     "description": "Show disk stall time in seconds",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod)(rate(container_pressure_memory_stalled_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\", name!=\"\"}[$__rate_interval]))",
       "legendFormat": "{{ container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive/Transmit Bandwidth",
     "type": "timeseries",
     "description": "Shows network traffic in bytes per second for the pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets",
     "type": "timeseries",
     "description": "Shows network packets for pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "received: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)    ",
       "legendFormat": "transmitted: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets Dropped",
     "type": "timeseries",
     "description": "Shows dropped packets for pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Open Sockets",
     "type": "timeseries",
     "description": "Number of open sockets for the container.\nNOTE: Panel shows information about open sockets only for Kubernetes v1.21+ and Openshift v4.x. Openshift v3.11 and less doesn't support metrics about sockets.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_sockets{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "💡Help",
     "type": "text",
     "description": "Show information about panels in current section",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 76 },
     "options": {
      "content": "# File Descriptors and Threads\n\nPanels in this section show information about FDs and Threads only for Kubernetes v1.21+ and Openshift v4.x. Openshift v3.11 and less doesn't support metrics about FDs and Threads. \n"
     }
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors for the container. ",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_file_descriptors{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    },
    {
     "title": "Rate of File Descriptors",
     "type": "timeseries",
     "description": "Rate of open file descriptors for the container. ",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_file_descriptors{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": "container: {{container}}"
      }
     ]
    },
    {
     "title": "Ulimit Root Process",
     "type": "stat",
     "description": "Soft ulimit values for the container root process. Unlimited if -1.",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_ulimits_soft{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "description": "Number of threads running inside the container.",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_threads{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    },
    {
     "title": "Rate of Threads",
     "type": "timeseries",
     "description": "Rate of threads running inside the container.",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(container_threads{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}[$__rate_interval])",
       "legendFormat": "container: {{container}}"
      }
     ]
    },
    {
     "title": "Maximum Threads",
     "type": "stat",
     "description": "Maximum number of threads allowed inside the container, infinity if value is zero.",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_threads_max{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", container!~\"POD|pause|\"}",
       "legendFormat": "container: {{container}}"
      }
     ]
    }
   ]
  }
 ]
}