{
 "title": "Kubernetes / Cluster Overview",
 "tags": [
  "k8s",
  "cluster"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Servers",
   "type": "stat",
   "description": "Shows the number of running API servers depending on the number of endpoints exposing metrics",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-apiserver\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ETCD Servers",
   "type": "stat",
   "description": "Shows number of active ETCD servers. May contain no data for PaaS clouds.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"etcd\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "kubelet Nodes",
   "type": "stat",
   "description": "Shows number of active kubelet servers",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kubelet\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ingress Pods",
   "type": "stat",
   "description": "Shows count of running monitoring pods\n\nNote: Metrics may not be collected from Openshift cluster",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\".*nginx-ingress-pod-monitor\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Status",
   "type": "stat",
   "description": "Show the count of containers in Running, Waiting, and Terminated statuses\n\nNote: Terminated pods not include \"Completed\" status",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{cluster=~\"$cluster\"} == 1) OR on() vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{cluster=~\"$cluster\"} == 1) OR on() vector(0)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{cluster=~\"$cluster\",reason!=\"Completed\"} == 1) OR on() vector(0)",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", reason=\"Completed\"} == 1) OR vector(0)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "stat",
   "description": "Shows count of running and not running nodes in the cluster. May contain no data for PaaS clouds.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_status_condition{cluster=~\"$cluster\", condition=\"Ready\", status=\"true\"} == 1) OR on() vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(kube_node_status_condition{cluster=~\"$cluster\", condition=\"Ready\", status=\"true\"} == 0) OR on() vector(0)",
     "legendFormat": "Not running"
    }
   ]
  },
  {
   "title": "Nodes Transition Status",
   "type": "state-timeline",
   "description": "Shows transition status of each node in the cluster\n\n1 - OK, 0 - Problem\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum (kube_node_status_condition{cluster=~\"$cluster\", condition=\"Ready\", status=\"true\"} * 1) by (node) + sum (kube_node_status_condition{cluster=~\"$cluster\", condition=\"MemoryPressure\", status=\"true\"} * 2) by (node) + sum (kube_node_status_condition{cluster=~\"$cluster\", condition=\"DiskPressure\", status=\"true\"} * 3) by (node) + sum (kube_node_status_condition{cluster=~\"$cluster\", condition=\"PIDPressure\", status=\"true\"} * 4) by (node)",
     "legendFormat": "{{node}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Persistent Volumes Status",
   "type": "stat",
   "description": "Shows persistent volumes count grouped by statuses",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{cluster=~\"$cluster\", phase=\"Bound\"})",
     "legendFormat": "Bound"
    },
    {
     "expr": "sum(kube_persistentvolume_status_phase{cluster=~\"$cluster\", phase!=\"Bound\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "description": "Shows CPU usage and allocation for the whole cluster\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"\",namespace!=\"\"}[$__rate_interval])) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) ",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "CPU Limits Commitment"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "bargauge",
   "description": "Shows usage disk space for all mounted volumes to nodes in the cluster",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max by(instance,device)(node_filesystem_size_bytes{cluster=\"$cluster\", fstype!=\"tmpfs\"} - node_filesystem_free_bytes{cluster=\"$cluster\", fstype!=\"tmpfs\"})) / sum (max by(instance,device) (node_filesystem_size_bytes{cluster=\"$cluster\", fstype!=\"tmpfs\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPU Usage, Requests, Limits Over Allocatable by Node",
   "type": "table",
   "description": "Shows CPU usage, Requests and Limits over allocatable per node.\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"\",namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"\",namespace!=\"\"}[$__rate_interval])) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"}) ",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "CPU Limits Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\"})",
     "legendFormat": "CPU Limits Commitment"
    }
   ]
  },
  {
   "title": "Not Healthy Pods",
   "type": "table",
   "description": "Show information about the reason the container is currently in waiting or terminated state",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{cluster=~\"$cluster\"} == 1"
    },
    {
     "expr": "kube_pod_container_status_terminated_reason{cluster=~\"$cluster\",reason!=\"Completed\"} == 1"
    },
    {
     "expr": "label_replace(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Pending\"}, \"reason\", \"$1\", \"phase\", \"(.*)\") == 1"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "description": "Shows memory utilization and allocation for the whole cluster\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "Memory Requests Commitment"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "Memory Limits Commitment"
    }
   ]
  },
  {
   "title": "Memory Usage, Requests, Limits Over Allocatable by Node",
   "type": "table",
   "description": "Shows Memory usage, Requests and Limits over allocatable per node.\n\n! This panel doesn't work in restricted mode if kube-state-metrics doesn't have permission to scrape the following resources: nodes",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"}",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(container_memory_rss{cluster=\"$cluster\",container=\"\",namespace!=\"\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(container_memory_rss{cluster=\"$cluster\",container=\"\",namespace!=\"\"}) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"}) ",
     "legendFormat": "CPU Requests Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"})",
     "legendFormat": "CPU Limits Commitment"
    },
    {
     "expr": "sum by (node)(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}) / sum by (node)(kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\"})",
     "legendFormat": "CPU Limits Commitment"
    }
   ]
  },
  {
   "title": "Last Terminated Status",
   "type": "table",
   "description": "Show information about the last reason the container was in terminated state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\",reason!=\"Completed\"} == 1",
     "legendFormat": "{{pod}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daemon Sets",
     "type": "stat",
     "description": "Shows the counts of running/all daemon sets in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_daemonset_status_number_unavailable{cluster=\"$cluster\"} > 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_daemonset_status_number_available{cluster=\"$cluster\"} > 0) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Stateful Sets",
     "type": "stat",
     "description": "Shows the counts of running/all stateful sets in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_statefulset_status_replicas_ready{cluster=\"$cluster\"} == 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_statefulset_status_replicas_ready{cluster=\"$cluster\"} == 1) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "stat",
     "description": "Shows the counts of running/all deployments in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_status_replicas_unavailable{cluster=\"$cluster\"} > 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_deployment_status_replicas_available{cluster=\"$cluster\"} > 0) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "stat",
     "description": "Shows the counts of running/all jobs in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_failed{cluster=\"$cluster\", condition=\"true\"} == 1) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_job_status_active{cluster=\"$cluster\"} == 1) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "description": "Shows the counts of running/all pods in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{cluster=\"$cluster\", condition=\"false\"})",
       "legendFormat": "Not Running"
      },
      {
       "expr": "sum(kube_pod_status_ready{cluster=\"$cluster\", condition=\"true\"})",
       "legendFormat": "Running"
      },
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Succeeded\"} == 1) or vector(0)",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Replica Sets",
     "type": "stat",
     "description": "Shows the counts of running/all replica sets in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_replicaset_status_replicas{cluster=\"$cluster\"} != kube_replicaset_status_ready_replicas{cluster=\"$cluster\"}) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_replicaset_status_replicas{cluster=\"$cluster\"} == kube_replicaset_status_ready_replicas{cluster=\"$cluster\"}) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Replication Controllers",
     "type": "stat",
     "description": "Shows the counts of running/all replication controllers in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_replicationcontroller_spec_replicas{cluster=~\"$cluster\"} != kube_replicationcontroller_status_available_replicas{cluster=~\"$cluster\"}) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_replicationcontroller_created{cluster=~\"$cluster\"}) - count(kube_replicationcontroller_spec_replicas{cluster=~\"$cluster\"} != kube_replicationcontroller_status_available_replicas{cluster=~\"$cluster\"}) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Cron Jobs",
     "type": "stat",
     "description": "Shows the counts of running/all cron jobs in the cluster",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_cronjob_info{cluster=\"$cluster\"}) or vector(0)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Request Volume",
     "type": "stat",
     "description": "Shows number of operation per second\n\nNote: Metrics may not be collected from Openshift cluster",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Ingress Request Volume",
     "type": "timeseries",
     "description": "Show the total number of client requests by ingress\n\nNote: Metrics may not be collected from Openshift cluster",
     "gridPos": { "h": 10, "w": 19, "x": 5, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[$__rate_interval])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Ingress Controller Success Rate",
     "type": "stat",
     "description": "Shows the percentage of successful requests with status codes 2xx-3xx\n\nNote: Metrics may not be collected from Openshift cluster",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\",status=~\"[2-3].*\"}[$__rate_interval])) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Successful percentage"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Certificates from files",
     "type": "stat",
     "description": "Shows count of total, expiring in 30 days and expired certificates from files.\nTo get the information about certificates cert-exporter must be running.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cert_exporter_cert_not_after_timestamp{cluster=~\"$cluster\"}) OR on() vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "count(0 < cert_exporter_cert_expires_in_seconds{cluster=~\"$cluster\"} <= 86400 * 30) OR on() vector(0)",
       "legendFormat": "Expiring soon"
      },
      {
       "expr": "count(cert_exporter_cert_expires_in_seconds{cluster=~\"$cluster\"} <= 0) OR on() vector(0)",
       "legendFormat": "Expired"
      }
     ]
    },
    {
     "title": "Certificates from kubeconfig",
     "type": "stat",
     "description": "Shows count of total, expiring in 30 days and expired certificates from kubeconfig. To get the information about certificates cert-exporter must be running.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(min(cert_exporter_kubeconfig_not_after_timestamp{cluster=~\"$cluster\"}) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "count(min(0 < cert_exporter_kubeconfig_expires_in_seconds{cluster=~\"$cluster\"} <= 86400 * 30) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Expiring soon"
      },
      {
       "expr": "count(min(cert_exporter_kubeconfig_expires_in_seconds{cluster=~\"$cluster\"} <= 0) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Expired"
      }
     ]
    },
    {
     "title": "Certificates from secrets",
     "type": "stat",
     "description": "Shows count of total, expiring in 30 days and expired certificates from secrets. To get the information about certificates cert-exporter must be running.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(min(cert_exporter_secret_not_after_timestamp{cluster=~\"$cluster\"}) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "count(min(0 < cert_exporter_secret_expires_in_seconds{cluster=~\"$cluster\"} <= 86400 * 30) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Expiring soon"
      },
      {
       "expr": "count(min(cert_exporter_secret_expires_in_seconds{cluster=~\"$cluster\"} <= 0) without (instance,pod)) OR on() vector(0)",
       "legendFormat": "Expired"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Shows CPU usage by each namespace in the cluster",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace) (\r\nrate(container_cpu_usage_seconds_total{image!=\"\", container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range])) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Throttled, Stalled",
     "type": "timeseries",
     "description": "Shows CPU throttled, stalled by each namespace in the cluster",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_pressure_cpu_stalled_seconds_total{image!=\"\",container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "Stalled {{namespace}}"
      },
      {
       "expr": "sum by (namespace)(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\",container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "Throttled {{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Usage over requests, limits, throttled, stalled time",
     "type": "table",
     "description": "Shows CPU usage over requests and limits, throttled, stalled time  per namespace in the cluster",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(kube_pod_owner{cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))) by (namespace)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum( sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))) by (namespace) / sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"},\"namespace\",\"$1\",\"exported_namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum( sum by (namespace, pod, container) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))) by (namespace) / sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"},\"namespace\",\"$1\",\"exported_namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum by (namespace) (rate(container_pressure_cpu_stalled_seconds_total{image!=\"\", container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range])) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace)(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\",container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Shows memory usage by namespace in the cluster",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Stalled",
     "type": "timeseries",
     "description": "Shows memory stall in seconds by namespace in the cluster",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (namespace) (rate(container_pressure_memory_stalled_seconds_total{image!=\"\", container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range])) ",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory usage over requests, limits, throttled, stalled time",
     "type": "table",
     "description": "Shows memory usage over requests and limits, stalled time  per namespace in the cluster",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(label_replace(kube_pod_owner{cluster=\"$cluster\"},\"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "count(avg(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (namespace)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace) "
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (namespace) / sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}) by (namespace) / sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}, \"namespace\", \"$1\", \"namespace\",\"(.*)\")) by (namespace)"
      },
      {
       "expr": "sum by (namespace) (rate(container_pressure_memory_stalled_seconds_total{image!=\"\", container!~\"^(.*POD.*|)$\", cluster=\"$cluster\"}[$__range])) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O utilization  per namspaces",
     "type": "timeseries",
     "description": "Shows data read/write per namespace",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} - reads bytes"
      },
      {
       "expr": "sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} -  written bytes"
      }
     ]
    },
    {
     "title": "IOps per namespace",
     "type": "timeseries",
     "description": "Count of writes/reads completed",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} reading"
      },
      {
       "expr": "sum (rate(container_fs_writes_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{ namespace }} writing"
      }
     ]
    },
    {
     "title": "Disk stall in seconds per namespace",
     "type": "timeseries",
     "description": "Disk stall in seconds per namespace",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(container_pressure_io_stalled_seconds_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__range])) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Disk I/O utilization per node",
     "type": "timeseries",
     "description": "Shows data read/write per node",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{ node}} - reads bytes"
      },
      {
       "expr": "sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{ node}} -  written bytes"
      }
     ]
    },
    {
     "title": "IOps per node",
     "type": "timeseries",
     "description": "Count of writes/reads completed",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{ node}} reading"
      },
      {
       "expr": "sum (rate(container_fs_writes_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (node)",
       "legendFormat": "{{ node}} writing"
      }
     ]
    },
    {
     "title": "Disk stall in seconds per node",
     "type": "timeseries",
     "description": "Disk stall in seconds per node",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (rate(node_pressure_io_stalled_seconds_total{cluster=\"$cluster\"}[$__range])) by (node)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Device storage usage",
     "type": "timeseries",
     "description": "Shows the amounts of total and used device storage in the cluster",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(device, fstype)(node_filesystem_size_bytes{cluster=~\"$cluster\"}) - sum by(device, fstype)(node_filesystem_free_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Used storage {{device}}"
      },
      {
       "expr": "sum by(device, fstype)(node_filesystem_size_bytes{cluster=~\"$cluster\"})",
       "legendFormat": "Total storage {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count PVC",
     "type": "stat",
     "description": "Show the number of pvc in the cluster",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\"})",
       "legendFormat": "Count PV"
      }
     ]
    },
    {
     "title": "Error: Persistent Volumes Not Bound",
     "type": "table",
     "description": "Show the number of PV with status != \"Bound\" in the cluster",
     "gridPos": { "h": 8, "w": 9, "x": 3, "y": 70 },
     "targets": [
      {
       "expr": "kube_persistentvolume_status_phase{cluster=~\"$cluster\", phase!=\"Bound\"} == 1"
      }
     ]
    },
    {
     "title": "Error: Persistent Volumes Claim Not Bound",
     "type": "table",
     "description": "Show the number of pvc with status != \"Bound\" in the cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_status_phase{cluster=~\"$cluster\", phase!=\"Bound\"} == 1"
      }
     ]
    },
    {
     "title": "Count PV",
     "type": "stat",
     "description": "Show the number of pv in the cluster",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_persistentvolume_info{cluster=\"$cluster\"})",
       "legendFormat": "Count PV"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "description": "Shows network usage details per namespace in the cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)"
      }
     ]
    },
    {
     "title": "Network RX/TX Total",
     "type": "timeseries",
     "description": "Shows overall network input and output traffic",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval]))",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval]))",
       "legendFormat": "transmit"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth",
     "type": "timeseries",
     "description": "Shows network traffic per namespace in the cluster",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} transmit"
      }
     ]
    },
    {
     "title": "Average Container Bandwidth by Namespace: Received/Transmitted",
     "type": "timeseries",
     "description": "Shows network traffic per container in the cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} received"
      },
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} transmitted"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets",
     "type": "timeseries",
     "description": "Shows average packets rate per namespace in the cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} received"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} transmitted"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets Dropped",
     "type": "timeseries",
     "description": "Shows dropped packets per namespaces in the cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 219 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} received"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\".+\"}[$__rate_interval])) by (namespace)",
       "legendFormat": "{{namespace}} transmitted"
      }
     ]
    }
   ]
  }
 ]
}