{
 "title": "Kubernetes / Kubelet",
 "tags": [
  "k8s",
  "kubelet"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Nodes",
   "type": "stat",
   "description": "Shows the number of alive nodes in the cluster by running kubelet instances",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=~\"$cluster\", job=\"kubelet\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Shows the total number of running pods on selected nodes",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pod_count{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "description": "Shows the total number of running containers on selected nodes",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "stat",
   "description": "Shows the total number of volumes in Volume Manager for selected nodes.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\", state=\"actual_state_of_world\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "stat",
   "description": "Show the desired number of volumes in Volume Manager for selected nodes.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\",state=\"desired_state_of_world\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Config Error Count",
   "type": "stat",
   "description": "Shows the number of configuration-related errors for selected nodes",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_node_config_error{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "timeseries",
   "description": "Shows a total count of runtime operations of each type for selected nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (operation_type, node)",
     "legendFormat": "{{node}} {{operation_type}}"
    },
    {
     "expr": "sum(rate(kubelet_runtime_operations{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (operation_type, node)",
     "legendFormat": "{{node}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation Error Rate",
   "type": "timeseries",
   "description": "Shows a count of errors in the operations for selected nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, operation_type)",
     "legendFormat": "{{node}} {{operation_type}}"
    },
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, operation_type)",
     "legendFormat": "{{node}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation duration 99th quantile",
   "type": "timeseries",
   "description": "Shows duration of the operations summary for selected nodes.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, operation_type, le))",
     "legendFormat": "{{node}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "timeseries",
   "description": "Shos number of pod start operations for selected nodes.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_start_duration_seconds_count{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_duration_seconds_count{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} worker"
    }
   ]
  },
  {
   "title": "Pod Start Duration",
   "type": "timeseries",
   "description": "Shows pod start time summary for selected nodes.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_count{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, le))",
     "legendFormat": "{{node}} pod"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, le))",
     "legendFormat": "{{node}} worker"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "timeseries",
   "description": "Shows storage operation duration for selected nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, operation_name, volume_plugin)",
     "legendFormat": "{{node}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Error Rate",
   "type": "timeseries",
   "description": "Shows the number of storage operations errors for selected nodes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])) by (node, operation_name, volume_plugin)",
     "legendFormat": "{{node}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "timeseries",
   "description": "Shows storage operations duration summary per opeartion for selected nodes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"}[$__rate_interval])) by (node, operation_name, volume_plugin, le))",
     "legendFormat": "{{node}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows memory usage by kubelet on selected nodes",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows CPU usage by kubelet on selected nodes",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows number of gorutines in kubelet on selected nodes",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{cluster=~\"$cluster\",job=\"kubelet\",node=~\"$instance\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "timeseries",
   "description": "Shows duration in seconds for cgroup manager operations.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"}[$__rate_interval])) by (node, operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup manager 99th quantile",
   "type": "timeseries",
   "description": "Duration in seconds for cgroup manager operations.\n\n**NOTE**:  This metric is available only in Kubernetes > 1.12 (Openshift > 4.1)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{cluster=~\"$cluster\", job=\"kubelet\", node=~\"$instance\"}[$__rate_interval])) by (node, operation_type, le))",
     "legendFormat": "{{node}} {{operation_type}}"
    }
   ]
  }
 ]
}