{
 "title": "Kubernetes / Namespace Resources",
 "tags": [
  "k8s",
  "namespaces"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, persistentvolumeclaim)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Count",
     "type": "stat",
     "description": "Shows the total number of pods in the namespace",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\"} == 1)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Not Running Pods Count",
     "type": "stat",
     "description": "Shows the number of pods in Failed, Pending, and Unknown state in the namespace",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "scalar(sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Failed\"} == 1 ) or vector(0)) + scalar(sum(kube_pod_status_ready{cluster=\"$cluster\", namespace=\"$namespace\", condition=\"false\"}) or vector(0)) -\nscalar(sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Succeeded\"} == 1) OR vector(0))",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Pending\"} == 1) OR vector(0)",
       "legendFormat": "Pending"
      },
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Unknown\"} == 1) OR vector(0)",
       "legendFormat": "Unknown"
      },
      {
       "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", phase=\"Succeeded\"} == 1) OR vector(0)",
       "legendFormat": "Succeeded"
      }
     ]
    },
    {
     "title": "Containers Count",
     "type": "stat",
     "description": "Shows the total number of containers in the namespace",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{namespace=\"$namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Container Status",
     "type": "stat",
     "description": "Show the count of containers in Running, Waiting, and Terminated statuses\n\nNote: Terminated not include \"Completed\" status",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{cluster=~\"$cluster\", namespace=\"$namespace\"} == 1) OR vector(0)",
       "legendFormat": "Running"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting{cluster=~\"$cluster\", namespace=\"$namespace\"} == 1) OR vector(0)",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason!=\"Completed\"} == 1) OR vector(0)",
       "legendFormat": "Terminated"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason=\"Completed\"} == 1) OR vector(0)",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Last Terminated Status",
     "type": "table",
     "description": "Show information about the last reason the container was in terminated state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason!=\"Completed\"} == 1"
      }
     ]
    },
    {
     "title": "Not Healthy Pods",
     "type": "table",
     "description": "Show information about the reason the container is currently in waiting or terminated state",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", namespace=\"$namespace\"} == 1",
       "legendFormat": "123"
      },
      {
       "expr": "kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", namespace=\"$namespace\", reason!=\"Completed\"} == 1",
       "legendFormat": "asd"
      },
      {
       "expr": "label_replace(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Pending\"}, \"reason\", \"$1\", \"phase\", \"(.*)\") == 1"
      }
     ]
    },
    {
     "title": "CPU Resources Summary",
     "type": "timeseries",
     "description": "Shows a general summary of CPU resources",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\", resource=\"cpu\"})",
       "legendFormat": "CPU request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster\"}) ",
       "legendFormat": "CPU limits"
      },
      {
       "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", resource=\"cpu\"})",
       "legendFormat": "CPU total"
      }
     ]
    },
    {
     "title": "Memory Resources Summary",
     "type": "timeseries",
     "description": "Shows a general summary of Memory resources",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster\"})",
       "legendFormat": "Memory request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster\"}) ",
       "legendFormat": "Memory limits"
      },
      {
       "expr": "sum(kube_node_status_capacity{cluster=~\"$cluster\", resource=\"memory\"})",
       "legendFormat": "Memory total"
      }
     ]
    }
   ]
  },
  {
   "title": "Counts Of Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cron Jobs",
     "type": "stat",
     "description": "Shows the counts of running/all cron jobs in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_cronjob_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daemon Sets",
     "type": "stat",
     "description": "Shows the counts of running/all daemon sets in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_daemonset_status_number_unavailable{cluster=\"$cluster\", namespace=\"$namespace\"} > 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_daemonset_status_number_available{cluster=\"$cluster\", namespace=\"$namespace\"} > 0) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "stat",
     "description": "Shows the counts of running/all deployments in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_status_replicas_unavailable{cluster=\"$cluster\", namespace=\"$namespace\"} > 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_deployment_status_replicas_available{cluster=\"$cluster\", namespace=\"$namespace\"} > 0) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "stat",
     "description": "Shows the counts of running/all jobs in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 144 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_job_failed{cluster=\"$cluster\", namespace=\"$namespace\", condition=\"true\"} == 1) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_job_status_active{cluster=\"$cluster\", namespace=\"$namespace\"} == 1) or vector(0)",
       "legendFormat": "Runing"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "description": "Shows the counts of running/all pods in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{cluster=\"$cluster\", namespace=\"$namespace\", condition=\"false\"}) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "sum(kube_pod_status_ready{cluster=\"$cluster\", namespace=\"$namespace\", condition=\"true\"}) or vector(0)",
       "legendFormat": "Running"
      },
      {
       "expr": "count(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", phase=\"Succeeded\"} == 1) or vector(0)",
       "legendFormat": "Completed"
      }
     ]
    },
    {
     "title": "Replica Sets",
     "type": "stat",
     "description": "Shows the counts of running/all replica sets in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_replicaset_status_replicas{cluster=\"$cluster\", namespace=\"$namespace\"} != kube_replicaset_status_ready_replicas{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_replicaset_status_replicas{cluster=\"$cluster\", namespace=\"$namespace\"} == kube_replicaset_status_ready_replicas{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Replication Controllers",
     "type": "stat",
     "description": "Shows the counts of running/all replication controllers in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_replicationcontroller_spec_replicas{namespace=\"$namespace\"} != kube_replicationcontroller_status_available_replicas{namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_replicationcontroller_created{namespace=\"$namespace\"}) - count(kube_replicationcontroller_spec_replicas{namespace=\"$namespace\"} != kube_replicationcontroller_status_available_replicas{namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Stateful Sets",
     "type": "stat",
     "description": "Shows the counts of running/all stateful sets in the current namespace",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\"} == 0) or vector(0)",
       "legendFormat": "Not Running"
      },
      {
       "expr": "count(kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\"} == 1) or vector(0)",
       "legendFormat": "Running"
      }
     ]
    },
    {
     "title": "Config And Storage",
     "type": "stat",
     "description": "Shows the counts of configs and storages in the current namespace",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 154 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_configmap_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Config Maps"
      },
      {
       "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "PVC"
      },
      {
       "expr": "count(kube_secret_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Secrets"
      }
     ]
    },
    {
     "title": "Service",
     "type": "stat",
     "description": "Shows the counts of services in the current namespace\n\nNote: Do not show the routes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 154 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_ingress_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Ingresses"
      },
      {
       "expr": "count(kube_service_info{cluster=\"$cluster\", namespace=\"$namespace\"}) or vector(0)",
       "legendFormat": "Services"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU And Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Limits Quota Allocated",
     "type": "gauge",
     "description": "Shows percentage of allocated CPU Limits Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.cpu\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.cpu\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Requests Quota Allocated",
     "type": "gauge",
     "description": "Shows percentage of allocated CPU Requests Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.cpu\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.cpu\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Limits Quota Actual Usage",
     "type": "gauge",
     "description": "Shows percentage of CPU usage against CPU Limits Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",container!~\"^(.*POD.*|)$\",name!=\"\"}[$__rate_interval])) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.cpu\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "CPU Requests Quota Actual Usage",
     "type": "gauge",
     "description": "Shows percentage of CPU usage against CPU Requests Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",container!~\"^(.*POD.*|)$\",name!=\"\"}[$__rate_interval])) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.cpu\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Limits Quota Allocated",
     "type": "gauge",
     "description": "Shows percentage of allocated Memory Limits Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.memory\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.memory\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Requests Quota Allocated",
     "type": "gauge",
     "description": "Shows percentage of allocated Memory Requests Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.memory\",type=\"used\",namespace=~\"$namespace\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.memory\",type=\"hard\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Limits Quota Actual Usage",
     "type": "gauge",
     "description": "Shows percentage of memory usage against Memory Limits Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",image!=\"\", namespace=\"$namespace\",container!~\"^(.*POD.*|)$\",name!=\"\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"limits.memory\",type=\"hard\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Requests Quota Actual Usage",
     "type": "gauge",
     "description": "Shows percentage of memory usage against Memory Requests Resource Quota in the namespace\n\nShows N/A if the quota is not specified",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",image!=\"\", namespace=\"$namespace\",container!~\"^(.*POD.*|)$\",name!=\"\"}) / sum(kube_resourcequota{cluster=\"$cluster\",resource=\"requests.memory\",type=\"hard\", namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows CPU usage by pods in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container!~\"^(.*POD.*|)$\", namespace=\"$namespace\",name!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "CPU Quota Requests"
    }
   ]
  },
  {
   "title": "CPU Resources",
   "type": "timeseries",
   "description": "Shows CPU usage in the namespace against CPU quota in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",container!~\"^(.*POD.*|)$\",name!=\"\"}[$__rate_interval]))",
     "legendFormat": "CPU Quota Usage"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"limits.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Limits"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"hard\"}",
     "legendFormat": "CPU Quota Requests"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"limits.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"requests.cpu\", type=\"used\"}",
     "legendFormat": "CPU Allocated Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",namespace=~\"$namespace\"}) ",
     "legendFormat": "CPU Allocated Limits"
    }
   ]
  },
  {
   "title": "CPU Throttled, Stalled",
   "type": "timeseries",
   "description": "Shows CPU throttled, stalled in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Stalled {{namespace}}"
    },
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Throttled {{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage By Pods",
   "type": "table",
   "description": "Shows detailed information about CPU usage by pods in the namespace\n\nClick on the pod name to go to the dashboard with the pod detailed information",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",image!=\"\", container!~\"^(.*POD.*|)$\", name!=\"\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"cpu\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",namespace=~\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",image!=\"\", container!~\"^(.*POD.*|)$\", name!=\"\", namespace=\"$namespace\"}[$__rate_interval])) by (pod) / sum(label_replace(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",namespace=~\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum (rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows memory usage by pods in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", container!~\"^(.*POD.*|)$\", name!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "Memory Quota Requests"
    }
   ]
  },
  {
   "title": "Memory Resources",
   "type": "timeseries",
   "description": "Shows memory usage in the namespace against memory quota in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",image!=\"\",container!~\"^(.*POD.*|)$\", namespace=\"$namespace\"})",
     "legendFormat": "Memory Quota Usage"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"limits.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Limits"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"requests.memory\", type=\"hard\"}",
     "legendFormat": "Memory Quota Requests"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"limits.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Limits"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=~\"$namespace\", resource=\"requests.memory\", type=\"used\"}",
     "legendFormat": "Memory Allocated Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\",namespace=~\"$namespace\"})",
     "legendFormat": "Memory Allocated Limits"
    }
   ]
  },
  {
   "title": "Memory Stalled",
   "type": "timeseries",
   "description": "Shows memory stalled in seconds in the namespace",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage By Pods",
   "type": "table",
   "description": "Shows detailed information about memory usage by pods in the namespace\n\nClick on the pod name to go to the dashboard with the pod detailed information",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",container!~\"^(.*POD.*|)$\", name!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\",namespace=~\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\",namespace=~\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",container!~\"^(.*POD.*|)$\", name!=\"\", image!=\"\"}) by (pod) / sum(label_replace(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\",namespace=~\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum (rate(container_pressure_cpu_stalled_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive/Transmit Bandwidth",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth Usage By Pods",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second by pods",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth Usage By Pods",
     "type": "table",
     "description": "Shows the overall incoming and outgoing network traffic in bytes per second by pods\n\nClick on the pod name to go to the dashboard with the pod detailed information",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing packets per second for the namespace",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Received Drops"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Transmitted Drops"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted Packets By Pods",
     "type": "timeseries",
     "description": "Shows the overall incoming and outgoing packets per second by pods for the namespace",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "receive: {{pod}}"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
       "legendFormat": "transmit: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received/Transmitted/Drops Packets By Pods",
     "type": "table",
     "description": "Shows overall incoming and outgoing network traffic in bytes per second by pods\n\nClick on the pod name to go to the dashboard with the pod detailed information",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Shows data read/write in bytes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum (rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization By Pods",
   "type": "timeseries",
   "description": "Shows data read/write in bytes by pods",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "reads: {{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "writes: {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Stalled",
   "type": "timeseries",
   "description": "Shows disk stalled by namespace",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(container_pressure_io_stalled_seconds_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__range])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization By Pods",
   "type": "table",
   "description": "Shows data read/write in bytes by pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__range])) by (pod)"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__range])) by (pod)"
    }
   ]
  },
  {
   "title": "Disk Stalled By Pods",
   "type": "table",
   "description": "Shows data read/write in bytes by pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__range])) by (pod)"
    },
    {
     "expr": "sum (rate(container_pressure_io_stalled_seconds_total{cluster=\"$cluster\", namespace=~\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__range])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOps",
   "type": "timeseries",
   "description": "Count of writes/reads completed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) ",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "IOps By Pods",
   "type": "timeseries",
   "description": "Count of writes/reads completed by pods",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "reads: {{pod}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "writes: {{pod}}"
    }
   ]
  },
  {
   "title": "IOps By Pods",
   "type": "table",
   "description": "Count of writes/reads completed by pods",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{cluster=\"$cluster\", namespace=\"$namespace\", container!~\"^(.*POD.*|)$\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Writing"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Used",
     "type": "timeseries",
     "description": "Show information about used volumes space. Cinder plugin doesn't provide \"kubelet_volume_stats_*\" metrics if Kubernetes version < 1.19v ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"} ",
       "legendFormat": "{{node}} - {{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volume Available",
     "type": "timeseries",
     "description": "Show information about available volumes space. Cinder plugin doesn't provide \"kubelet_volume_stats_*\" metrics if Kubernetes version < 1.19v ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "{{node}} - {{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Volumes Info",
     "type": "table",
     "description": "Show common information about volumes. Cinder plugin doesn't provide \"kubelet_volume_stats_*\" metrics if Kubernetes version < 1.19v",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "(kubelet_volume_stats_available_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) - 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"} ) /  kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", persistentvolumeclaim=~\"$pvc\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}