{
 "title": "Openshift / API Server",
 "description": "Dashboard shows extended statistics about Openshift API server",
 "tags": [
  "apiserver",
  "openshift"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openshift / API server",
     "type": "text",
     "description": "Describes some specific use cases for panels",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# This dashboard is designed for Openshift 4.5 and higher\n\n* Platform monitoring is adapted to collect metrics from Openshift 4.5 and higher.\n* Please note, panels don't work in OpenShift v3.11.\n* Please make sure that openshift API server pods are deployed and started. Otherwise metrics won't be shown."
     }
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API server status",
   "type": "stat",
   "description": "Shows API server status depending on the number of endpoints exposing metrics",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"})"
    }
   ]
  },
  {
   "title": "API Servers",
   "type": "stat",
   "description": "Shows the number of running API servers  depending on the number of endpoints exposing metrics",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"})"
    }
   ]
  },
  {
   "title": "Current Error Rate",
   "type": "stat",
   "description": "Show the current API server error rate: percentage of requests with errors out of the total number of requests",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(apiserver_request_total{cluster=\"$cluster\", code=~\"5..\", apiserver=\"openshift-apiserver\"}[5m])) / sum(rate(apiserver_request_total{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"}[5m])))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Average API Server Latency",
   "type": "stat",
   "description": "Shows the average duration of request to API server",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{cluster=\"$cluster\", apiserver=\"openshift-apiserver\", verb!=\"WATCH\"}[5m])) / sum(rate(apiserver_request_duration_seconds_count{cluster=\"$cluster\", apiserver=\"openshift-apiserver\", verb!=\"WATCH\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Etcd Requests Latency",
   "type": "stat",
   "description": "Shows the average duration of requests to Etcd",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_sum{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"}[5m])) / sum(rate(etcd_request_duration_seconds_count{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"}[5m]))"
    }
   ]
  },
  {
   "title": "Current Controller work queue Depth",
   "type": "stat",
   "description": "Show the current depth of controller work queue",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"})"
    }
   ]
  },
  {
   "title": "API server nodes status",
   "type": "flant-statusmap-panel",
   "description": "Shows API server nodes status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "up{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"} * on(pod) group_left(node) (kube_pod_info{pod=~\"apiserver-.*\", cluster=\"$cluster\", host_network=\"false\"})\r\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Shows the number of requests per second by each API server instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(apiserver_request_total{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])) * on(pod) group_left(node) (kube_pod_info{pod=~\"apiserver-.*\", cluster=\"$cluster\", host_network=\"false\"})\r\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request rate by resource and verbs",
     "type": "timeseries",
     "description": "Shows the number of requests per second by verb and resource",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(20, sum(rate(apiserver_request_total{apiserver=\"openshift-apiserver\", cluster=~\"$cluster\", resource!=\"\"}[5m])) by(resource,verb))",
       "legendFormat": "{{ verb}}:{{resource}}"
      }
     ]
    },
    {
     "title": "Request Rate by resource and group",
     "type": "graph",
     "description": "Shows the number of requests per second by resource and its API group in format: API/resource",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by(group, resource) (rate(apiserver_request_total{cluster=\"$cluster\", apiserver=\"openshift-apiserver\"}[5m]))",
       "legendFormat": "{{group}}/{{resource}}"
      }
     ]
    },
    {
     "title": "Request Read and Write",
     "type": "timeseries",
     "description": "Shows rate of request separated by read and write",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\", apiserver=\"openshift-apiserver\",verb=~\"POST|PUT|PATCH|UPDATE|DELETE\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\", apiserver=\"openshift-apiserver\",verb=~\"LIST|GET\"}[5m]))",
       "legendFormat": "Read"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request duration 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", apiserver=\"openshift-apiserver\", verb!=\"WATCH\"}[5m])))",
       "legendFormat": "Request duration 0.99 quantile"
      }
     ]
    },
    {
     "title": "Request duration by verb 0.99  quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile by verb: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", apiserver=\"openshift-apiserver\", verb!=\"WATCH\"}[5m])) by (verb, le))\r\n",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "Request duration by resource and group 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the request duration  0.99 quantile by resource type and its API group: 99% of requests  . Format: API/resource\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (resource, group, le) (rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\", apiserver=\"openshift-apiserver\", verb!=\"WATCH\"}[5m])) )\r\n",
       "legendFormat": "{{group}}/{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API Server error percentage",
     "type": "timeseries",
     "description": "Shows the percentage of requests failed with 5xx error by each API server instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum by (pod) (rate(apiserver_request_total{code=~\"[4,5]..\", apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])) / sum by (pod) (rate(apiserver_request_total{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m]))  * 100)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Error request rate by verb",
     "type": "timeseries",
     "description": "Show the number of requests per second failed with 5xx or 4xx code grouped by verb",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(verb) (rate(apiserver_request_total{code=~\"[4,5]..\", apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[10m]))",
       "legendFormat": "{{group}}"
      }
     ]
    },
    {
     "title": "Error request rate by code",
     "type": "timeseries",
     "description": "Show the number of requests per second failed with 5xx or 4xx code grouped by code",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (code) (rate(apiserver_request_total{code=~\"[4,5]..\", apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[10m]))",
       "legendFormat": "{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Work Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Adds to work queue per second",
     "type": "timeseries",
     "description": "Shows the number of adds to controller work queue per second",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (name)(rate(workqueue_adds_total{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Work queue depth",
     "type": "timeseries",
     "description": "Shows the current depth of controller work queue. It should be near 0",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (name)(workqueue_depth{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Item processing time 0.99  quantile",
     "type": "timeseries",
     "description": "Shows 0.99 duration quantile of the item processed from work queue: 99% of items has equal or less processing time",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(workqueue_work_duration_seconds_bucket{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "Processing time 0.99  quantile"
      }
     ]
    },
    {
     "title": "Item queue time 0.99 quantile",
     "type": "timeseries",
     "description": "Shows 0.99 duration quantile of the item stay work queue: 99% of items has equal or less staying time",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(workqueue_queue_duration_seconds_bucket{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "Queue time 0.99  quantile"
      }
     ]
    },
    {
     "title": "Unfinished work time",
     "type": "timeseries",
     "description": "Show time of unfinished item processing.  Large values indicate stuck threads",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (workqueue_unfinished_work_seconds{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "Unfinished work time"
      }
     ]
    },
    {
     "title": "Longest running processor time",
     "type": "timeseries",
     "description": "Show longest time of item processing",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (workqueue_longest_running_processor_seconds{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "Longest running processor time"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Etcd request rate",
     "type": "timeseries",
     "description": "Shows the number of requests per second sent to Etcd",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type)(rate(etcd_request_duration_seconds_count{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Etcd request duration 0.99 quantile",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(etcd_request_duration_seconds_bucket{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "Request duration 0.99 quantile"
      }
     ]
    },
    {
     "title": "Request duration 0.99 quantile by operation",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile by operation: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (operation, le) (rate(etcd_request_duration_seconds_bucket{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Request duration 0.99 quantile by object type",
     "type": "timeseries",
     "description": "Shows the Etcd request duration  0.99 quantile by object type: 99% of requests has equal or less duration ",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (type, le) (rate(etcd_request_duration_seconds_bucket{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m])))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Objects stored in etcd",
     "type": "timeseries",
     "description": "Shows the number of objects stored in Etcd",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (resource)((apiserver_storage_objects{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Shows the CPU usage by each API server instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod)(rate(process_cpu_seconds_total{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Shows the number of goroutines by each API server instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Resident memory",
     "type": "timeseries",
     "description": "Show the resident memory usage by each API server instance",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Allocated memory",
     "type": "timeseries",
     "description": "Shows the allocated  memory  by each API server instance",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (go_memstats_alloc_bytes{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"})",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Allocations per second",
     "type": "timeseries",
     "description": "Shows the memory allocations per second by each instance",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod)(rate(go_memstats_alloc_bytes_total{apiserver=\"openshift-apiserver\", cluster=\"$cluster\"}[5m]))",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  }
 ]
}