{
 "title": "Openshift / State metrics",
 "description": "Dashboards shows openshift-state-metrics specific metrics",
 "tags": [
  "openshift-state-metrics",
  "openshift"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openshift / State metrics",
     "type": "text",
     "description": "Describes some specific use cases for panels",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# This dashboard is designed for Openshift 4.5 and higher\n\n* Platform monitoring is adapted to collect metrics from Openshift 4.5 and higher. \n* Please note, panels don't work in OpenShift v3.11.\n* This dashboard shows metrics of \"openshift-state-metrics\" exporter. By default this exporter is deployed in \"openshift-monitoring\" namespace as a deployment. Please make sure that this exporter is deployed and started. Otherwise metrics won't be shown."
     }
    }
   ]
  },
  { "title": "Deploymentconfigs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Deploymentconfigs",
   "type": "stat",
   "description": "Shows the counts of running/not running deploymentconfigs in the cluster",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openshift_deploymentconfig_status_replicas_available{cluster=\"$cluster\"} > 0) or vector(0)",
     "legendFormat": "Rinning"
    },
    {
     "expr": "count(openshift_deploymentconfig_status_replicas_unavailable{cluster=\"$cluster\"} > 0) or vector(0)",
     "legendFormat": "Not Running"
    }
   ]
  },
  {
   "title": "Deploymentconfigs list",
   "type": "table",
   "description": "Shows list of all deployment configs in the $cluster",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "sum by (deploymentconfig, instance, namespace, container) (openshift_deploymentconfig_spec_replicas{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Quotas Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Percent CPU used vs request quota",
     "type": "timeseries",
     "description": "Shows  CPU used vs request quota in percents",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (name, kube_cluster_name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"used\", cluster=\"$cluster\"}) / sum by (name, kube_cluster_name) (openshift_clusterresourcequota_usage{resource=\"requests.cpu\", type=\"hard\", cluster=\"$cluster\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percent Memory Used vs Request Quota",
     "type": "timeseries",
     "description": "Shows memory used vs Request quota in percent",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"used\", cluster=\"$cluster\"}) / sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"requests.memory\", type=\"hard\", cluster=\"$cluster\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Quotas Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Percent CPU Used vs Limit Quota",
     "type": "timeseries",
     "description": "Shows CPU Used vs Limit Quota in percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"limits.cpu\", type=\"used\", cluster=\"$cluster\"}) / sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"limits.cpu\", type=\"hard\", cluster=\"$cluster\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percent Memory Used vs Limit Quota",
     "type": "timeseries",
     "description": "Shows t Memory Used vs Limit Quota in percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"limits.memory\", type=\"used\", cluster=\"$cluster\"}) / sum by (name, kube_cluster_name)(openshift_clusterresourcequota_usage{resource=\"limits.memory\", type=\"hard\", cluster=\"$cluster\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "List of routes",
     "type": "table",
     "description": "Shows list of all the routes present in the cluster, aggregated by host and namespace",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route, host, namespace) (openshift_route_info{cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duplicated routes",
     "type": "table",
     "description": "Shows duplicated routes",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "openshift_route_info{cluster=\"$cluster\"} * on (host) group_left(host_name) label_replace((sum by (host) (openshift_route_info{cluster=\"$cluster\"}) > 1), \"host_name\", \"$0\", \"host\", \".+\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Routes with errors",
     "type": "table",
     "description": "Shows openshift routes with errors",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "openshift_route_status{status=~'False', cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "New Builds",
     "type": "table",
     "description": "Shows New Builds by Processing Time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "time() - (openshift_build_created_timestamp_seconds{cluster=\"$cluster\"}) * on (build) group_left(build_phase) (openshift_build_status_phase_total{build_phase=\"new\", cluster=\"$cluster\"} == 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Builds with Errors",
     "type": "table",
     "description": "Show openshift builds with error",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (build, buildconfig, kube_namespace_name, kube_cluster_name) (openshift_build_status_phase_total{build_phase=~\"failed|error\", cluster=\"$cluster\"}) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}