{
 "title": "Overall Cloud Status",
 "description": "Dashboard shows health status of applications are deployed into cloud platform, k8s/OpenShift nodes, applications are deployed out of cloud.",
 "tags": [
  "k8s",
  "cluster"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API server status",
   "type": "stat",
   "description": "Shows status of Kubernetes API server.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\",job=\"kube-apiserver\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "API servers",
   "type": "stat",
   "description": "Shows number of API servers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{cluster=\"$cluster\", service=\"kubernetes\", job=\"kube-apiserver\"})"
    }
   ]
  },
  {
   "title": "API server requests",
   "type": "stat",
   "description": "Shows count of requests to API server, requests per minute.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\"}[2m]))"
    },
    {
     "expr": "sum(rate(apiserver_request_count{cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "API server errors",
   "type": "stat",
   "description": "Shows errors in requests to API server.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_total{code=~\"[4,5]..\",cluster=\"$cluster\"}[5m])) / sum by(instance) (rate(apiserver_request_total{cluster=\"$cluster\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "ETCD status",
   "type": "stat",
   "description": "Show status of etcd cluster. May contain no data for PaaS clouds.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ETCD servers",
   "type": "stat",
   "description": "Shows number of  active ETCD servers. May contain no data for PaaS clouds.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"etcd\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ETCD requests",
   "type": "stat",
   "description": "Shows number of requests per second to ETCD servers. May contain no data for PaaS clouds.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\", job=\"etcd\", service=\"etcd\",cluster=\"$cluster\"}[5m]))"
    }
   ]
  },
  {
   "title": "ETCD server request error",
   "type": "stat",
   "description": "Shows percent of error requests to ETCD server. May contain no data for PaaS clouds.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",job=\"etcd\",cluster=\"$cluster\"}[5m])) * 100 "
    }
   ]
  },
  {
   "title": "API server nodes status",
   "type": "timeseries",
   "description": "Shows status of each API server in the cluster.  1 - OK, 0 - Problem",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    up{job=\"kube-apiserver\", cluster=\"$cluster\"},\r\n    \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:.*)*\") \r\n* on(host_ip) group_left(pod, node) (kube_pod_info{pod=~\"kube-apiserver.*\", host_network=\"true\"})\r\nor on (instance)\r\n(\r\nlabel_replace(\r\n    up{job=\"kube-apiserver\", cluster=\"$cluster\"},\r\n    \"pod\", \"$1\", \"instance\", \"(.+)\"\r\n    )\r\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "API server failed requests",
   "type": "timeseries",
   "description": "Shows errors  in requests to API server, operations per minute.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "max(changes(apiserver_request_total{code=~\"[4,5]..\",cluster=\"$cluster\"}[2m])) by (code,verb,client,resource)",
     "legendFormat": "{{resource}} / {{verb}} / {{client}} / {{code}} "
    }
   ]
  },
  {
   "title": "Etcd nodes status",
   "type": "timeseries",
   "description": "Shows status of each etcd pod in the cluster. 1 - OK, 0 - Problem.\nMay contain no data for PaaS clouds.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", endpoint=~\".*metrics\", job=\"etcd\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETCD failed requests",
   "type": "timeseries",
   "description": "Shows number  of errors per minute in requests to ETCD server. May contain no data for PaaS clouds.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",job=\"etcd\",cluster=\"$cluster\"}[5m])) by (pod, grpc_code)",
     "legendFormat": "{{pod}} / {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "bargauge",
   "description": "Shows overall CPU usage",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",cluster=\"$cluster\"}[$__range])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Total Memory usage",
   "type": "bargauge",
   "description": "Shows overall RAM usage for all nodes against total available RAM on all nodes.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\",cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"})) * 100"
    }
   ]
  },
  {
   "title": "Total Filesystem usage",
   "type": "bargauge",
   "description": "Shows summary file system usage on Kubernetes cluster nodes",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance)) - sum(avg(node_filesystem_free_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance))) * 100 / (sum(avg(node_filesystem_avail_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance)) + (sum(avg(node_filesystem_size_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance)) - sum(avg(node_filesystem_free_bytes{cluster=\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance))))"
    }
   ]
  },
  {
   "title": "Used cores",
   "type": "stat",
   "description": "Show used cores for cloud in cores (1 core = 1000 millicores)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1-irate(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\",mode=\"idle\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total cores",
   "type": "stat",
   "description": "Show total cores available for cloud",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cluster=~\"$cluster\",job=\"node-exporter\", mode='system'})"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "stat",
   "description": "Show total used memory for cloud",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"node-exporter\"}) - sum(node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "description": "Show total available memory for cloud",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\",job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "stat",
   "description": "Show sum by used space for directories and files on all nodes in cloud where `fstype == xfs | ext.`. It means that all FS like `tmpfs`, `rootfs` will be exclude from value.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) - sum(node_filesystem_avail_bytes{cluster=~\"$cluster\",job=\"node-exporter\",fstype=~\"xfs|ext.*\"})"
    }
   ]
  },
  {
   "title": "Total space",
   "type": "stat",
   "description": "Show total available space for directories and files on all nodes in cloud where `fstype == xfs | ext.`. It means that all FS like `tmpfs`, `rootfs` will be exclude from value.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{cluster=~\"$cluster\", job=\"node-exporter\",fstype=~\"xfs|ext.*\"}) by (device,instance))"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "description": "Shows number of active Kubernetes cluster nodes",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_os_info{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "description": "Shows number of unavailable nodes.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Shows the total number of running pods in cluster. Show only pods with `status = ready`",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{cluster=~\"$cluster\", condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "description": "Shows the total number of running containers in pods.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_container_count{cluster=~\"$cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node State",
     "type": "stat",
     "description": "Show running state of all nodes in selected cloud",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_node_info{cluster=\"$cluster\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Nodes Overview",
     "type": "table",
     "description": "Shows cluster nodes overview: \n  * Node Uptime\n  * Total available CPU and RAM on node\n  * Overall resources usage on node\n  * Can be grouped by node_label",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "(node_uname_info{cluster=\"$cluster\"} -0)",
       "legendFormat": "Labels"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{cluster=\"$cluster\"}) by (instance) ",
       "legendFormat": "Uptime"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - 0)",
       "legendFormat": "Memory"
      },
      {
       "expr": "count(node_cpu_seconds_total{mode='system',cluster=\"$cluster\"}) by (instance)",
       "legendFormat": "CPU"
      },
      {
       "expr": "node_load5{cluster=\"$cluster\"}",
       "legendFormat": "CPU Last 5m Load"
      },
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\"}[5m])) by (instance)) * 100",
       "legendFormat": "CPU Usage"
      },
      {
       "expr": "(1 - ((node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / (node_memory_MemTotal_bytes{cluster=\"$cluster\"})))) * 100",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}) * 100 / (node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"} + (node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"} - node_filesystem_free_bytes{fstype=~\"ext.?|xfs\",cluster=\"$cluster\",mountpoint=\"/\"}))) by (instance)",
       "legendFormat": "Disk Space Usage"
      },
      {
       "expr": "max(irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[5m])) by (instance)",
       "legendFormat": "Disk Reads / sec"
      },
      {
       "expr": "max((irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[5m]))) by (instance)",
       "legendFormat": "Disk Writes / sec"
      }
     ]
    }
   ]
  },
  {
   "title": "Applications health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total pods",
     "type": "stat",
     "description": "Shows the total number of pods in cluster.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Running pods",
     "type": "stat",
     "description": "Shows the total number of running pods in cluster. Show only pods with `status = ready`",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{cluster=~\"$cluster\", condition=\"true\"})"
      }
     ]
    },
    {
     "title": "Not runnning pods",
     "type": "stat",
     "description": "Shows the total number of not running / not healthy pods in cluster.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{cluster=~\"$cluster\", condition=\"false\"})"
      }
     ]
    },
    {
     "title": "💡Help",
     "type": "text",
     "description": "Show information about panels in current section",
     "gridPos": { "h": 4, "w": 15, "x": 9, "y": 21 },
     "options": {
      "content": "### Application health\n\nPanels in this section show only pods in not running state. We show only not running pods due on big environments we can have thousands of pods, there is no good visualization to show such count pod states."
     }
    },
    {
     "title": "Not Healthy Pods",
     "type": "table",
     "description": "Show information about the reason the container is currently in waiting or terminated state",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{cluster=~\"$cluster\"} == 1"
      },
      {
       "expr": "kube_pod_container_status_terminated_reason{cluster=~\"$cluster\",reason!=\"Completed\"} == 1"
      },
      {
       "expr": "label_replace(kube_pod_status_phase{cluster=\"$cluster\", phase=\"Pending\"}, \"reason\", \"$1\", \"phase\", \"(.*)\") == 1"
      }
     ]
    },
    {
     "title": "Last Terminated Status",
     "type": "table",
     "description": "Show information about the last reason the container was in terminated state",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{cluster=~\"$cluster\",reason!=\"Completed\"} == 1",
       "legendFormat": "{{exported_pod}}-{{exported_namespace}}"
      }
     ]
    }
   ]
  }
 ]
}