{
 "title": "Prometheus Self Monitoring",
 "tags": [
  "self-monitor",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": {
     "query": "query_result({__name__=~\"prometheus_.*_seconds\", cluster=~\"$cluster\"})"
    }
   },
   {
    "name": "RuleGroup",
    "query": {
     "query": "prometheus_rule_group_last_duration_seconds{instance=~\"$instance\"}"
    }
   },
   {
    "name": "long_term_interval",
    "query": "10m,30m,1h,6h,12h,1d,3d,1w,4w,12w,1y"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{cluster=~\"$cluster\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Show the prometheus instance uptime",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Successful Config Reload",
   "type": "stat",
   "description": "Show last successful config reload",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "Shows CPU usage for the prometheus instance",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "gauge",
   "description": "The amount of memory the Prometheus process is using from the kernel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_storage_blocks_bytes{ instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Oldest data",
   "type": "stat",
   "description": "Show the earliest saved data",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - min(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Count of Jobs",
   "type": "stat",
   "description": "Shows the number of active jobs",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (count by (job) (up{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "description": "Shows the number of active time series",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{instance=~\"$instance\"}) "
    }
   ]
  },
  {
   "title": "Points per second",
   "type": "stat",
   "description": "Show number of metrics per second stored by Prometheus as taken from the last $interval.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Build, uptime and runtime instance info",
   "type": "table",
   "description": "Prometheus instance overview",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(time() - process_start_time_seconds{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "max(prometheus_build_info{instance=~\"$instance\"}) by (instance, version)"
    },
    {
     "expr": "max(prometheus_config_last_reload_successful{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "max(sum(prometheus_rule_group_rules{instance=~\"$instance\"}) by (instance) or prometheus_build_info{instance=~\"$instance\"}*0) by (instance)"
    },
    {
     "expr": "max(sum(prometheus_sd_discovered_targets{instance=~\"$instance\", name=\"scrape\"}) by (instance) or prometheus_build_info{instance=~\"$instance\"}*0) by (instance)"
    },
    {
     "expr": "max(prometheus_tsdb_head_series{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "time() - max(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "min(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Main info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of time series",
   "type": "timeseries",
   "description": "Shows the number of active time series",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(prometheus_tsdb_head_series{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$quantile quantile of interval length between scrapes per job",
   "type": "timeseries",
   "description": "Actual amount of time between target scrapes",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{instance=~\"$instance\",quantile=\"$quantile\"}",
     "legendFormat": "{{instance}} job {{job}} should be {{interval}}"
    }
   ]
  },
  {
   "title": "Prometheus errors in $interval",
   "type": "timeseries",
   "description": "Shows the total number of Prometheus errors, including different non-default behavior. \n\nFor example, if you are sending not all the metrics to the remoteStorage, then the panel will also display the number of unsent points (prometheus_remote_storage_samples_dropped_total).",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(label_replace({__name__=~\"(:?prometheus|net_conntrack)_.*(:?fail|duplicate|out_of|error|not_found|corrupt|dropped|missed|exceeded).*_total\", instance=~\"$instance\"}, \"metric_name\", \"$1\", \"__name__\", \"(.*)\")[$interval:20s])) by (instance,metric_name,alertmanager,name,mechanism,queue) > 0",
     "legendFormat": "{{ metric_name }}"
    }
   ]
  },
  {
   "title": "Exporters/Targets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ready jobs/ All jobs",
     "type": "stat",
     "description": "Shows the number of jobs(Ready/All)",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (job) (up{cluster=~\"$cluster\"} == 1))"
      },
      {
       "expr": "count(sum by (job) (up{cluster=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "kubelet",
     "type": "stat",
     "description": "Show number of targets for kubelet",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*kubelet.*\"})"
      }
     ]
    },
    {
     "title": "node-exporter",
     "type": "stat",
     "description": "Show number of targets for node-exporter",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*node-exporter.*\"})"
      }
     ]
    },
    {
     "title": "kube-state-metrics",
     "type": "stat",
     "description": "Show number of targets for kube-state-metrics",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*kube-state-metrics.*\"})"
      }
     ]
    },
    {
     "title": "etcd",
     "type": "stat",
     "description": "Show number of targets for etcd",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*etcd.*\"})"
      }
     ]
    },
    {
     "title": "kube-apiserver",
     "type": "stat",
     "description": "Show number of targets for kube-apiserver",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*kube-apiserver.*\"})"
      }
     ]
    },
    {
     "title": "nginx-ingress",
     "type": "stat",
     "description": "Show number of targets for nginx-ingress\n\n* Works only in kubernetes",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (prometheus_target_scrape_pool_targets{cluster=~\"$cluster\",scrape_job=~\".*nginx-ingress.*\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape targets",
     "type": "timeseries",
     "description": "Show current number of targets in this scrape pool",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_target_scrape_pool_targets{cluster=~\"$cluster\"}",
       "legendFormat": "{{ scrape_job }}"
      }
     ]
    },
    {
     "title": "Discovered targets",
     "type": "timeseries",
     "description": "Show current number of discovered targets",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_sd_discovered_targets{cluster=~\"$cluster\"}",
       "legendFormat": "{{ config }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Cardinality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of series by job",
     "type": "timeseries",
     "description": "Show number of series by job",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(scrape_samples_scraped{cluster=~\"$cluster\"}) by (job)",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "New series by job",
     "type": "timeseries",
     "description": "Show how many new series were created",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(scrape_series_added{cluster=~\"$cluster\"}) by (job)\r",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Highest cardinality for $job",
     "type": "table",
     "description": "Show 10 metrics with the highest cardinality for $job target",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 39 },
     "repeat": "job",
     "targets": [
      {
       "expr": "topk(10, count by(__name__)({__name__=~\".+\",cluster=~\"$cluster\",job=~\"$job\"}))",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Count metrics for $job",
     "type": "stat",
     "description": "Show number of metrics for $job",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 39 },
     "repeat": "job",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count({cluster=~\"$cluster\",job=~\"$job\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests & queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP requests/s",
     "type": "timeseries",
     "description": "Average request duration for the last 1m.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_count{instance=~\"$instance\"}[2m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP request latency",
     "type": "timeseries",
     "description": "Latencies for HTTP requests",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{instance=~\"$instance\"}[2m]) / rate(prometheus_http_request_duration_seconds_count{instance=~\"$instance\"}[2m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Time spent in HTTP requests/s",
     "type": "timeseries",
     "description": "Time spent in HTTP requests/s",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_request_duration_seconds_sum{instance=~\"$instance\"}[2m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP request count by handler in $interval",
     "type": "timeseries",
     "description": "Counter of HTTP requests",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_requests_total{instance=~\"$instance\"}[$interval])) by (instance, handler) ",
       "legendFormat": " {{ handler }} handler on {{ instance }}"
      }
     ]
    },
    {
     "title": "$quantile quantile of HTTP request duration per handler",
     "type": "timeseries",
     "description": "HTTP request duration per handler",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_request_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (le,instance, handler))",
       "legendFormat": "{{ handler }} handler on {{instance}}"
      }
     ]
    },
    {
     "title": "$quantile of request size by handler",
     "type": "timeseries",
     "description": "Request size by handler",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(increase(prometheus_http_response_size_bytes_bucket{instance=~\"$instance\"}[$interval])) by (le,instance, handler)) > 0",
       "legendFormat": "{{ handler }} handler on {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "Shows CPU usage for the prometheus instance",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])) by (instance)",
       "legendFormat": "CPU usage of {{instance}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Resident and allocated memory size in bytes.\n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(process_resident_memory_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Resident memory of {{instance}}"
      },
      {
       "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Total allocated bytes of {{instance}}"
      }
     ]
    },
    {
     "title": "Allocations per second in $interval",
     "type": "timeseries",
     "description": "Total number of bytes allocated, even if freed",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Allocated Bytes of {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Oldest data",
     "type": "timeseries",
     "description": "Show the earliest saved data",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - min(prometheus_tsdb_lowest_timestamp_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Oldest data for {{instance}}"
      }
     ]
    },
    {
     "title": "Size of the storage",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for local storage by all blocks",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(prometheus_tsdb_storage_blocks_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Storage size of {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query engine & API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of concurent queries and it's limit",
     "type": "timeseries",
     "description": "The current and max number of queries being executed or waiting",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_engine_queries{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(prometheus_engine_queries_concurrent_max{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}} Limit"
      }
     ]
    },
    {
     "title": "$quantile quantile of query engine evaluation duration per slice",
     "type": "timeseries",
     "description": "Query engine evaluation duration per slice",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}",
       "legendFormat": "{{slice}} slice on {{instance}}"
      }
     ]
    },
    {
     "title": "Number of queries on remote read API",
     "type": "timeseries",
     "description": "The current number of remote read queries being executed or waiting",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_api_remote_read_queries{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule evaluation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
     "type": "timeseries",
     "description": "Percentage rule group evaluation duration from the rule group evaluation interval (top 20)",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20,\nmax(prometheus_rule_group_last_duration_seconds{instance=~\"$instance\"}) by (rule_group, instance) /\nmin(prometheus_rule_group_interval_seconds{instance=~\"$instance\"}) by (rule_group, instance)\n)\n",
       "legendFormat": "Percentage of {{rule_group}} group evaluation interval on {{instance}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of rule evaluation duration",
     "type": "timeseries",
     "description": "Rule evaluation duration (for quantile => 0.5)",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(prometheus_rule_evaluation_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}) by (instance, quantile)",
       "legendFormat": "evaluation duration of {{instance}}"
      }
     ]
    },
    {
     "title": "Number of rules per group (top 20 groups)",
     "type": "timeseries",
     "description": "Number of rules for the first 20 groups",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(topk(20,prometheus_rule_group_rules{instance=~\"$instance\"})) by (instance, rule_group)",
       "legendFormat": "number of rules in {{rule_group}} rule group on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notification queue size and capacity",
     "type": "timeseries",
     "description": "The number of alert notifications in the queue. And the capacity of the alert notifications queue.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_notifications_queue_length{instance=~\"$instance\"})by (instance)",
       "legendFormat": "Queue size of {{instance}}"
      },
      {
       "expr": "sum(prometheus_notifications_queue_capacity{instance=~\"$instance\"})by (instance)",
       "legendFormat": "Queue capacity of {{instance}}"
      }
     ]
    },
    {
     "title": "Number of sent notifictions per alertmanager in $interval",
     "type": "timeseries",
     "description": "Total number of alerts sent",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_notifications_sent_total{instance=~\"$instance\"}[$interval])) by (instance, alertmanager)",
       "legendFormat": "Sent notifications to {{alertmanager}} alertmanager from {{instance}}"
      }
     ]
    },
    {
     "title": "$quantile of notification latency per alertmanager",
     "type": "timeseries",
     "description": "Latency quantiles for sending alert notifications",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(prometheus_notifications_latency_seconds{instance=~\"$instance\", quantile=\"$quantile\"}) by (instance, alertmanager)",
       "legendFormat": "Latency of notifications sent to {{alertmanager}} from  {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape Interval",
     "type": "timeseries",
     "description": "Intervals between scrapes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_sum{instance=~\"$instance\"}[2m]) / rate(prometheus_target_interval_length_seconds_count{instance=~\"$instance\"}[2m])",
       "legendFormat": "{{ interval }}"
      }
     ]
    },
    {
     "title": "Number of target errors",
     "type": "timeseries",
     "description": "Number of scrapes that hit the sample limit and were rejected. And the number of samples rejected due to duplicate timestamps but different values, not being out of the expected order, timestamp falling outside of the time bounds. ",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Exceeded Sample Limit"
      },
      {
       "expr": "rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Duplicate Timestamp"
      },
      {
       "expr": "rate(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Out of Order"
      },
      {
       "expr": "rate(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[2m])",
       "legendFormat": "Out Of Bounds "
      }
     ]
    },
    {
     "title": "Metadata Cache Size",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for storing metric metadata in the cache",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_target_metadata_cache_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of discovered targets per Type and config",
     "type": "timeseries",
     "description": "Current number of discovered targets",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_sd_discovered_targets{instance=~\"$instance\", name=\"scrape\"}) by (instance,config,name)",
       "legendFormat": "Number of {{name}} type targets from config {{config}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Service discovery  sync count by mechanism in $interval",
     "type": "timeseries",
     "description": "Service discovery  sync count by mechanism",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_sd_refresh_duration_seconds_count{instance=~\"$instance\"}[$interval])) by (instance,mechanism)",
       "legendFormat": "Number of sync for {{mechanism}} SD mechanism on {{instance}}"
      },
      {
       "expr": "sum(increase(prometheus_sd_consul_rpc_duration_seconds_count{instance=~\"$instance\"}[$interval])) by (instance)",
       "legendFormat": "Number of sync for consul SD mechanism on {{instance}}"
      },
      {
       "expr": "sum(increase(prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\"}[$interval])) by (instance)",
       "legendFormat": "Number of sync for kubernetes SD mechanism on {{instance}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of refresh duration per SD mechanism",
     "type": "timeseries",
     "description": "\n",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_sd_refresh_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}",
       "legendFormat": "Duration of sync for {{mechanism}} SD mechanism on {{instance}}"
      },
      {
       "expr": "consul_rpc_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}",
       "legendFormat": "Number of sync for consul SD mechanism on {{instance}}"
      },
      {
       "expr": "prometheus_sd_file_scan_duration_seconds{instance=~\"$instance\", quantile=\"$quantile\"}",
       "legendFormat": "Duration of sync for file_scan SD mechanism on {{instance}}"
      },
      {
       "expr": "prometheus_sd_kubernetes_http_request_duration_seconds_sum{instance=~\"$instance\"} / prometheus_sd_kubernetes_http_request_duration_seconds_count{instance=~\"$instance\"}",
       "legendFormat": "AVG Duration of sync for k8s SD mechanism on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compaction and retention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$quantile quantile of compaction duration",
     "type": "timeseries",
     "description": "Duration of compaction runs",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(prometheus_tsdb_compaction_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance, le))",
       "legendFormat": "Compaction duration on {{ instance }}"
      }
     ]
    },
    {
     "title": "Number of vertical/horizontal compactions in last $interval",
     "type": "timeseries",
     "description": "Number of vertical/horizontal compactions",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_total{instance=~\"$instance\"}[$interval])) by (instance) > 0",
       "legendFormat": "Count of horizontal compactions on {{instance}}"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_vertical_compactions_total{instance=~\"$instance\"}[$interval])) by (instance) > 0",
       "legendFormat": "Count of vertical compactions  on {{instance}}"
      }
     ]
    },
    {
     "title": "Number of time/size retention cutoffs in $interval",
     "type": "timeseries",
     "description": "The number of times that blocks were deleted because the maximum time limit or number of bytes was exceeded.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_size_retentions_total{instance=~\"$instance\"}[$interval])) by (instance) > 0",
       "legendFormat": "Number of size retention cutoffs on  {{ instance }}"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_time_retentions_total{instance=~\"$instance\"}[$interval])) by (instance) > 0",
       "legendFormat": "Number of time retention cutoffs on {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$quantile quantile of WAL fsync duration",
     "type": "timeseries",
     "description": "Duration of WAL fsync ( for quantile => 0.5 )",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_wal_fsync_duration_seconds{instance=~\"$instance\",quantile=\"$quantile\"}) by (instance)",
       "legendFormat": "Duration of WAL fsync on {{instance}}"
      }
     ]
    },
    {
     "title": "Number of completed pages in $interval",
     "type": "timeseries",
     "description": "Number of completed pages",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_wal_completed_pages_total{instance=~\"$instance\"}[$interval])) by (instance)",
       "legendFormat": "Completed WAL pages count of {{instance}}"
      }
     ]
    },
    {
     "title": "Average duration of WAL truncation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_wal_truncate_duration_seconds_sum{instance=~\"$instance\"} /\nprometheus_tsdb_wal_truncate_duration_seconds_count{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Duration of WAL truncation on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of queries to remote storage per client",
     "type": "timeseries",
     "description": "Number of remote read queries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_remote_storage_remote_read_queries{instance=~\"$instance\"}) by (instance, client)",
       "legendFormat": "Number of queries to {{client}} client from {{instance}}"
      }
     ]
    },
    {
     "title": "Number of samles successfuly sent to remote storage per queue",
     "type": "timeseries",
     "description": "Total number of samples successfully sent to remote storage.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_remote_storage_succeeded_samples_total{instance=~\"$instance\"}[$interval])) by (instance, queue)",
       "legendFormat": "Number of samples sent to {{queue}}  from {{instance}}"
      }
     ]
    },
    {
     "title": "$quantile quantile of batch send call duration to remote storage",
     "type": "timeseries",
     "description": "Call duration to remote storage",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile,sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (instance, queue, le))",
       "legendFormat": "Duration of batch send to {{queue}}  from {{instance}}"
      }
     ]
    },
    {
     "title": "Number of used shards for concurrent sending of data to remote storage and it's capacity",
     "type": "timeseries",
     "description": "Number of used shards for concurrent sending of data to remote storage and it's capacity",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_remote_storage_shards{instance=~\"$instance\"}) by (instance, queue)",
       "legendFormat": "Number of shards used for {{queue}} on {{instance}}"
      },
      {
       "expr": "min(prometheus_remote_storage_shard_capacity{instance=~\"$instance\"}) by (instance, queue)",
       "legendFormat": "Limit of shards that can be used for {{queue}} on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of gorutines",
     "type": "timeseries",
     "description": "Number of goroutines that currently exist.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "Gorutines count of {{instance}}"
      }
     ]
    },
    {
     "title": "Duration of Go garbage collection",
     "type": "timeseries",
     "description": "Max duration of garbage collection cycles.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(go_gc_duration_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "GC duration on {{instance}}"
      }
     ]
    },
    {
     "title": "Go system memory allocations",
     "type": "timeseries",
     "description": "Go system memory allocations",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(go_memstats_mspan_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "mspan {{instance}}"
      },
      {
       "expr": "max(go_memstats_mcache_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "mcache {{instance}}"
      },
      {
       "expr": "max(go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "buck_hash {{instance}}"
      },
      {
       "expr": "max(go_memstats_gc_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "gc {{instance}}"
      },
      {
       "expr": "max(go_memstats_other_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "other {{instance}}"
      },
      {
       "expr": "max(go_memstats_stack_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "stack {{instance}}"
      },
      {
       "expr": "max(go_memstats_heap_sys_bytes{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "heap {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Accepted/closed inbound connections per listener",
     "type": "timeseries",
     "description": "Accepted/closed inbound connections per listener of a given name.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_listener_conn_accepted_total{instance=~\"$instance\"}[$interval])) by (instance, listener_name) > 0",
       "legendFormat": "{{listener_name}} accepted connections on {{instance}}"
      },
      {
       "expr": "sum(increase(net_conntrack_listener_conn_closed_total{instance=~\"$instance\"}[$interval])) by (instance, listener_name) > 0",
       "legendFormat": "{{listener_name}} closed connections on {{instance}}"
      }
     ]
    },
    {
     "title": "Established/closed outbound connections per dialer ",
     "type": "timeseries",
     "description": "Established/closed outbound connections per dialer a given name.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_established_total{instance=~\"$instance\"}[$interval])) by (instance, dialer_name) > 0",
       "legendFormat": "{{dialer_name}} established connections on {{instance}}"
      },
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_closed_total{instance=~\"$instance\"}[$interval])) by (instance, dialer_name) > 0",
       "legendFormat": "{{dialer_name}} closed connections on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule Group: $RuleGroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "RuleGroup",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$RuleGroup: Duration",
     "type": "timeseries",
     "description": "The interval and last duration evaluation of a rule group.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_rule_group_interval_seconds{instance=~\"$instance\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "Interval"
      },
      {
       "expr": "prometheus_rule_group_last_duration_seconds{instance=~\"$instance\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "Last Duration"
      }
     ]
    },
    {
     "title": "$RuleGroup: Rules",
     "type": "timeseries",
     "description": "The number of rules",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_rule_group_rules{instance=~\"$instance\",rule_group=~\"$RuleGroup\"}\n",
       "legendFormat": "Rules"
      }
     ]
    }
   ]
  }
 ]
}