apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  labels:
    name: vmalertmanager
    app.kubernetes.io/name: vmalertmanager
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
  name: k8s
spec:
  replicaCount: 1
  configSecret: vmalertmanager-config-secret
  resources: {}
  securityContext:
    fsGroup: 2000
    runAsUser: 2000

  # Enable discovery all CRs if labelSelectors is empty
  selectAllByDefault: true

  # Selector to discovery CRs
  # Exclude the OpenShift Monitoring configurations
  configSelector: {}
  configNamespaceSelector:
      matchExpressions:
      - key: openshift.io/cluster-monitoring
        operator: NotIn
        values: ["true"]

  # Disable top route namespace label matcher for VMAlertmanagerConfig
  disableNamespaceMatcher: true