{{- if and .Values.install .Values.global.privilegedRights .Values.rbac.createClusterRoleBinding }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "networkLatencyExporter.rbac.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "networkLatencyExporter.rbac.fullname" .) "component" "network-latency-exporter") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "networkLatencyExporter.rbac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
