{
 "title": "AWS Application ELB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_sum, availability_zone)"
    }
   },
   {
    "name": "target_group",
    "label": "Target Group",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_sum, target_group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Host Count",
   "type": "timeseries",
   "description": "The number of targets that are considered healthy.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_healthy_host_count_minimum{availability_zone=~\"$availability_zone\", target_group=~\"$target_group\"}",
     "legendFormat": "{{availability_zone}} - {{target_group}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "UnHealthy Host Count",
   "type": "timeseries",
   "description": "The number of targets that are considered unhealthy.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_unhealthy_host_count_maximum{availability_zone=~\"$availability_zone\", target_group=~\"$target_group\"}",
     "legendFormat": "{{availability_zone}} - {{target_group}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "LoadBalancer Capacity",
   "type": "timeseries",
   "description": "The number of load balancer capacity units (LCU) used by your load balancer. You pay for the number of LCUs that you use per hour.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_consumed_lcus_sum{}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "timeseries",
   "description": "\t\nThe total number of concurrent TCP connections active from clients to the load balancer and from the load balancer to targets.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Rejected Connection Count",
   "type": "timeseries",
   "description": "The number of requests processed over IPv4 and IPv6. This metric is only incremented for requests where the load balancer node was able to choose a target. Requests that are rejected before a target is chosen are not reflected in this metric.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_applicationelb_rejected_connection_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "The number of requests processed over IPv4 and IPv6. This metric is only incremented for requests where the load balancer node was able to choose a target. Requests that are rejected before a target is chosen are not reflected in this metric.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum{availability_zone=~\"$availability_zone\",target_group=~\"$target_group\"}",
     "legendFormat": "{{availability_zone}} - {{target_group}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "The total number of bytes processed by the load balancer over IPv4 and IPv6 (HTTP header and HTTP payload). This count includes traffic to and from clients and Lambda functions, and traffic from an Identity Provider (IdP) if user authentication is enabled.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_applicationelb_processed_bytes_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Httpcode 4x and 5x for Load Balancer",
   "type": "timeseries",
   "description": "The number of HTTP 4XX,5XX redirection codes that originate from the load balancer. This count does not include response codes generated by targets.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_elb_4_xx_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}} - 4xx"
    },
    {
     "expr": "aws_applicationelb_httpcode_elb_5_xx_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}} - 5xx"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth Success",
     "type": "timeseries",
     "description": "The number of authenticate actions that were successful. This metric is incremented at the end of the authentication workflow, after the load balancer has retrieved the user claims from the IdP.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_applicationelb_elb_auth_success_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Auth Latency",
     "type": "timeseries",
     "description": "The time elapsed, in milliseconds, to query the IdP for the ID token and user info. If one or more of these operations fail, this is the time to failure.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aws_applicationelb_elb_auth_latency_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Auth Error",
     "type": "timeseries",
     "description": "The number of user authentications that could not be completed because an authenticate action was misconfigured, the load balancer couldn't establish a connection with the IdP, or the load balancer couldn't complete the authentication flow due to an internal error. To get the error reason codes, check the error_reason field of the access log.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_applicationelb_elb_auth_error_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Auth Failure",
     "type": "timeseries",
     "description": "\t\nThe number of user authentications that could not be completed because the IdP denied access to the user or an authorization code was used more than once. To get the error reason codes, check the error_reason field of the access log.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_applicationelb_elb_auth_failure_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    }
   ]
  }
 ]
}