{
 "title": "AWS Cassandra",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(aws_cassandra_billable_table_size_in_bytes_average, keyspace)"
    }
   },
   {
    "name": "tableName",
    "label": "Table Name",
    "query": {
     "query": "label_values(aws_cassandra_billable_table_size_in_bytes_average, table_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max Table Level Reads",
   "type": "stat",
   "description": "The maximum number of read capacity units that can be used by a table of an account. For on-demand tables this limit caps the maximum read request units a table can use.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_cassandra_account_max_table_level_reads_maximum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Table Level Writes",
   "type": "stat",
   "description": "The maximum number of write capacity units that can be used by a table of an account. For on-demand tables this limit caps the maximum write request units a table can use.",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_cassandra_account_max_table_level_writes_maximum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Check Failed Requests",
   "type": "timeseries",
   "description": "The number of failed lightweight transaction (LWT) write requests. The INSERT, UPDATE, and DELETE operations let you provide a logical condition that must evaluate to true before the operation can proceed.",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_conditional_check_failed_requests_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\"}",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "System Errors",
   "type": "timeseries",
   "description": "The requests to Amazon Keyspaces that generate a ServerError during the specified time period. A ServerError usually indicates an internal service error.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_system_errors_sample_count{keyspace=~\"$keyspace\"}",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "User Errors",
   "type": "timeseries",
   "description": "Requests to Amazon Keyspaces that generate an InvalidRequest error during the specified time period. An InvalidRequest usually indicates a client-side error, such as an invalid combination of parameters, an attempt to update a nonexistent table, or an incorrect request signature.\n\nUserErrors represents the aggregate of invalid requests for the current AWS Region and the current AWS account.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_user_errors_sample_count{keyspace=~\"$keyspace\"}",
     "legendFormat": "{{keyspace}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "The successful requests to Amazon Keyspaces during the specified time period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aws_cassandra_successful_request_latency_sum{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"SELECT\"}",
     "legendFormat": "SELECT"
    },
    {
     "expr": "aws_cassandra_successful_request_latency_sum{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"DELETE\"}",
     "legendFormat": "DELETE"
    },
    {
     "expr": "aws_cassandra_successful_request_latency_sum{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"INSERT\"}",
     "legendFormat": "INSERT"
    },
    {
     "expr": "aws_cassandra_successful_request_latency_sum{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"UPDATE\"}",
     "legendFormat": "UPDATE"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "The number of successful requests processed over the specified time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_successful_request_count_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"SELECT\"}",
     "legendFormat": "SELECT"
    },
    {
     "expr": "aws_cassandra_successful_request_count_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"DELETE\"}",
     "legendFormat": "DELETE"
    },
    {
     "expr": "aws_cassandra_successful_request_count_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"INSERT\"}",
     "legendFormat": "INSERT"
    },
    {
     "expr": "aws_cassandra_successful_request_count_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\", operation=\"UPDATE\"}",
     "legendFormat": "UPDATE"
    }
   ]
  },
  {
   "title": "Read Throttle Events",
   "type": "timeseries",
   "description": "\t\nRequests to Amazon Keyspaces that exceed the provisioned read capacity for a table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_read_throttle_events_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\"}",
     "legendFormat": "{{keyspace}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Write Throttle Events",
   "type": "timeseries",
   "description": "Requests to Amazon Keyspaces that exceed the provisioned write capacity for a table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_cassandra_write_throttle_events_sample_count{keyspace=~\"$keyspace\", table_name=~\"$tableName\"}",
     "legendFormat": "{{keyspace}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Billable Table Size",
   "type": "timeseries",
   "description": "The billable size of the table in bytes. It is the sum of the encoded size of all rows in the table. This metric helps you track your table storage costs over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_cassandra_billable_table_size_in_bytes_average{}",
     "legendFormat": "{{keyspace}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Read/WriteCapacityUtilization",
   "type": "timeseries",
   "description": "The percentage of provisioned read/write capacity units utilized by an account.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "aws_cassandra_account_provisioned_write_capacity_utilization_average{}",
     "legendFormat": "write"
    },
    {
     "expr": "aws_cassandra_account_provisioned_read_capacity_utilization_average{}",
     "legendFormat": "read"
    }
   ]
  }
 ]
}