{
 "title": "AWS Classic ELB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(aws_elb_request_count_sum, availability_zone)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Host",
   "type": "timeseries",
   "description": "\t\nThe number of healthy instances registered with your load balancer. A newly registered instance is considered healthy after it passes the first health check. If cross-zone load balancing is enabled, the number of healthy instances for the LoadBalancerName dimension is calculated across all Availability Zones. Otherwise, it is calculated per Availability Zone.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_backend_healthy_host_count_maximum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "UnHealthy Host",
   "type": "timeseries",
   "description": "The number of unhealthy instances registered with your load balancer. An instance is considered unhealthy after it exceeds the unhealthy threshold configured for health checks. An unhealthy instance is considered healthy again after it meets the healthy threshold configured for health checks.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_backend_unhealthy_host_count_minimum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "[HTTP listener] The total time elapsed, in seconds, from the time the load balancer sent the request to a registered instance until the instance started to send the response headers.\n\n[TCP listener] The total time elapsed, in seconds, for the load balancer to successfully establish a connection to a registered instance.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aws_elb_latency_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "description": "The number of requests completed or connections made during the specified interval (1 or 5 minutes).\n\n[HTTP listener] The number of requests received and routed, including HTTP error responses from the registered instances.\n\n[TCP listener] The number of connections made to the registered instances.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_request_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}} -4xx"
    }
   ]
  },
  {
   "title": "Httpcode 4x and 5x for Load Balancer",
   "type": "timeseries",
   "description": "The number of HTTP 4XX,5XX redirection codes that originate from the load balancer. This count does not include response codes generated by targets.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_httpcode_elb_4_xx_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}} -4xx"
    },
    {
     "expr": "aws_elb_httpcode_elb_5_xx_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}} - 5xx"
    }
   ]
  },
  {
   "title": "Backend Connection Errors",
   "type": "timeseries",
   "description": "The number of connections that were not successfully established between the load balancer and the registered instances. Because the load balancer retries the connection when there are errors, this count can exceed the request rate. Note that this count also includes any connection errors related to health checks.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_backend_connection_errors_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Spillover Count",
   "type": "timeseries",
   "description": "The total number of requests that were rejected because the surge queue is full.\n\n[HTTP listener] The load balancer returns an HTTP 503 error code.\n\n[TCP listener] The load balancer closes the connection.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_elb_spillover_count_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  }
 ]
}