{
 "title": "AWS EBS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   },
   {
    "name": "volume_id",
    "label": "Volume ID",
    "query": {
     "query": "label_values(aws_ebs_volume_total_read_time_sum, volume_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "description": "Provides information on the readoperations in a specified period of time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_read_bytes_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}} "
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "description": "Provides information on the write operations in a specified period of time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_write_bytes_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "description": "The total number of read operations in a specified period of time. Note: read operations are counted on completion.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_read_ops_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "description": "The total number of write operations in a specified period of time. Note: write operations are counted on completion.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_write_ops_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}}"
    }
   ]
  },
  {
   "title": "Total Read Time",
   "type": "timeseries",
   "description": "The total number of seconds spent by all read operations that completed in a specified period of time.  For example, for a period of 1 minutes (60 seconds): if 150 operations completed during that period, and each operation took 1 second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_total_read_time_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}} "
    }
   ]
  },
  {
   "title": "Total Write Time",
   "type": "timeseries",
   "description": "The total number of seconds spent by all write operations that completed in a specified period of time.  For example, for a period of 1 minutes (60 seconds): if 150 operations completed during that period, and each operation took 1 second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_ebs_volume_total_write_time_sum{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}} "
    }
   ]
  },
  {
   "title": "Burst Balance",
   "type": "timeseries",
   "description": "Used with General Purpose SSD (gp2), Throughput Optimized HDD (st1), and Cold HDD (sc1) volumes only. Provides information about the percentage of I/O credits (for gp2) or throughput credits (for st1 and sc1) remaining in the burst bucket. Data is reported to CloudWatch only when the volume is active. If the volume is not attached, no data is reported. If the baseline performance of the volume exceeds the maximum burst performance, credits are never spent. If the volume is attached to an instance built on the Nitro System, the burst balance is not reported. For other instances, the reported burst balance is 100%. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_ebs_burst_balance_average{volume_id=~\"$volume_id\"}",
     "legendFormat": "{{volume_id}}"
    }
   ]
  }
 ]
}