{
 "title": "AWS EFS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d"
   },
   {
    "name": "file_system_id",
    "label": "File System Id",
    "query": {
     "query": "label_values(aws_efs_storage_bytes_average, file_system_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IO Limit",
   "type": "timeseries",
   "description": "Shows how close a file system is to reaching the I/O limit of the General Purpose performance mode. If this metric is at 100 percent more often than not, consider moving your application to a file system using the Max I/O performance mode.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aws_efs_percent_iolimit_average{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}}"
    }
   ]
  },
  {
   "title": "IO Bytes",
   "type": "timeseries",
   "description": "Read - The number of bytes for each file system read operation.\nWrite - The number of bytes for each file system write operation.\nMetadata - The number of bytes for each metadata operation.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_efs_data_read_iobytes_sum{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}} - read"
    },
    {
     "expr": "aws_efs_data_write_iobytes_sum{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}} - write"
    },
    {
     "expr": "aws_efs_metadata_iobytes_sum{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}} - metadata"
    },
    {
     "expr": "aws_efs_total_iobytes_sum{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}} - total"
    }
   ]
  },
  {
   "title": "ClientConnections",
   "type": "timeseries",
   "description": "The number of client connections to a file system. When using a standard client, there is one connection per mounted Amazon EC2 instance.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_efs_client_connections_sum{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}}"
    }
   ]
  },
  {
   "title": "Burst Credit Balance",
   "type": "timeseries",
   "description": "The number of burst credits that a file system has. Burst credits allow a file system to burst to throughput levels above a file system’s baseline level for periods of time. ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_efs_burst_credit_balance_average{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "description": "The size of the file system in bytes, including the amount of data stored in the EFS Standard and EFS Standard–Infrequent Access (EFS Standard-IA) storage classes. This metric is emitted every 15 minutes to CloudWatch.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_efs_storage_bytes_average{file_system_id=~\"$file_system_id\"}",
     "legendFormat": "{{file_system_id}} - {{storage_class}}"
    }
   ]
  }
 ]
}