{
 "title": "AWS Network ELB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_average,availability_zone)"
    }
   },
   {
    "name": "target_group",
    "label": "Target group",
    "query": {
     "query": "label_values(aws_networkelb_healthy_host_count_minimum, target_group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy Host Count",
   "type": "timeseries",
   "description": "The number of targets that are considered healthy. This metric does not include any Application Load Balancers registered as targets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_healthy_host_count_minimum{availability_zone=~\"$availability_zone\", target_group=~\"$target_group\"}",
     "legendFormat": "{{availability_zone}} - {{target_group}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count",
   "type": "timeseries",
   "description": "The number of targets that are considered unhealthy. This metric does not include any Application Load Balancers registered as targets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_un_healthy_host_count_maximum{availability_zone=~\"$availability_zone\", target_group=~\"$target_group\"}",
     "legendFormat": "{{availability_zone}} - {{target_group}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Packets Count",
   "type": "timeseries",
   "description": "The total number of packets processed by the load balancer. This count includes traffic to and from targets, including health check traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_packets_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "The total number of bytes processed by the load balancer, including TCP/IP headers. This count includes traffic to and from targets, minus health check traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_networkelb_processed_bytes_sum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Active Flow Count",
   "type": "timeseries",
   "description": "The total number of concurrent flows (or connections) from clients to targets. This metric includes connections in the SYN_SENT and ESTABLISHED states. TCP connections are not terminated at the load balancer, so a client opening a TCP connection to a target counts as a single flow.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_average{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "Packet Rate per Second",
   "type": "timeseries",
   "description": "Highest average packet rate (packets processed per second), calculated every 10 seconds during the sampling window. This metric includes health check traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_peak_packets_per_second_maximum{availability_zone=~\"$availability_zone\"}",
     "legendFormat": "{{availability_zone}} - {{load_balancer}}"
    }
   ]
  },
  {
   "title": "LoadBalancer Capacity",
   "type": "timeseries",
   "description": "\t\nThe number of load balancer capacity units (LCU) used by your load balancer. You pay for the number of LCUs that you use per hour.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_consumed_lcus_average{}",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Traffic",
     "type": "timeseries",
     "description": "The total number of bytes processed by TCP listeners.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_networkelb_processed_bytes_tcp_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Active TCP Flow Count",
     "type": "timeseries",
     "description": "The total number of concurrent TCP flows (or connections) from clients to targets. This metric includes connections in the SYN_SENT and ESTABLISHED state. TCP connections are not terminated at the load balancer, so a client opening a TCP connection to a target counts as a single flow.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_active_flow_count_tcp_average{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "LoadBalancer Capacity TCP",
     "type": "timeseries",
     "description": "\t\nThe number of load balancer capacity units (LCU) used by your load balancer for TCP. You pay for the number of LCUs that you use per hour. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_consumed_lcus_tcp_average{}",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP Traffic",
     "type": "timeseries",
     "description": "The total number of bytes processed by UDP listeners.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_networkelb_processed_bytes_udp_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Active UDP Flow Count",
     "type": "timeseries",
     "description": "The total number of concurrent UDP flows (or connections) from clients to targets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_active_flow_count_udp_average{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "LoadBalancer Capacity UDP",
     "type": "timeseries",
     "description": "The number of load balancer capacity units (LCU) used by your load balancer for UDP. You pay for the number of LCUs that you use per hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_consumed_lcus_udp_average{}",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS Traffic",
     "type": "timeseries",
     "description": "The total number of bytes processed by TLS listeners.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_networkelb_processed_bytes_tls_sum{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Active TLS Flow Count",
     "type": "timeseries",
     "description": "The total number of concurrent TLS flows (or connections) from clients to targets. This metric includes connections in the SYN_SENT and ESTABLISHED state.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_active_flow_count_tls_average{availability_zone=~\"$availability_zone\"}",
       "legendFormat": "{{availability_zone}} - {{load_balancer}}"
      }
     ]
    },
    {
     "title": "LoadBalancer Capacity TLS",
     "type": "timeseries",
     "description": "The number of load balancer capacity units (LCU) used by your load balancer for TLS. You pay for the number of LCUs that you use per hour.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_networkelb_consumed_lcus_tls_average{}",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    }
   ]
  }
 ]
}