{
 "title": "AWS RabbitMQ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(aws_amazonmq_rabbit_mqmem_limit_average, broker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "The volume of RAM used by a RabbitMQ broker.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_rabbit_mqmem_limit_average{node=\"\", broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Disk Free Limit",
   "type": "stat",
   "description": "The disk limit for a RabbitMQ broker. ",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_rabbit_mqdisk_free_limit_average{node=\"\", broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "stat",
   "description": "The total number of connections established on the broker.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_connection_count_average{broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Channel Count",
   "type": "stat",
   "description": "The total number of channels established on the broker.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_channel_count_average{broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "stat",
   "description": "The total number of queues configured on the broker.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_queue_count_average{broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Exchange Count",
   "type": "stat",
   "description": "The total number of exchanges configured on the broker.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_exchange_count_average{broker=~\"$broker\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Consumer Count",
   "type": "stat",
   "description": "The total number of consumers connected to the broker.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_amazonmq_consumer_count_average{broker=~\"$broker\", queue=\"\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Message Count",
   "type": "timeseries",
   "description": "The total number of messages in the queues.\nNote: The number produced is the total sum of ready and unacknowledged messages on the broker.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_amazonmq_message_ready_count_sum{broker=~\"$broker\", queue=\"\"}",
     "legendFormat": "{{broker}} - ready"
    },
    {
     "expr": "aws_amazonmq_message_unacknowledged_count_sum{broker=~\"$broker\", queue=\"\"}",
     "legendFormat": "{{broker}} - unacknowledged"
    },
    {
     "expr": "aws_amazonmq_message_count_sum{broker=~\"$broker\", queue=\"\"}",
     "legendFormat": "{{broker}} - total"
    }
   ]
  },
  { "title": "Memory/CPU/Disk/FD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "The volume of RAM used by a RabbitMQ broker.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_amazonmq_rabbit_mqmem_used_average{broker=~\"$broker\", node=\"\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "description": "The percentage of allocated Amazon EC2 compute units that the broker currently uses. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_amazonmq_system_cpu_utilization_average{broker=~\"$broker\", node=\"\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "timeseries",
   "description": "The total volume of free disk space available in a RabbitMQ broker. When disk usage goes above its limit, the cluster will block all producer connections.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_amazonmq_rabbit_mqdisk_free_average{broker=~\"$broker\", node=\"\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Fife Descriptor Used",
   "type": "timeseries",
   "description": "The volume of RAM used by a RabbitMQ broker. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_amazonmq_rabbit_mqfd_used_average{broker=~\"$broker\", node=\"\"}",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ack Rate",
     "type": "timeseries",
     "description": "The rate at which messages are being acknowledged by consumers.\nThe number produced represents the number of messages per second at the time of sampling.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_amazonmq_ack_rate_average{broker=~\"$broker\"}",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "ConfirmRate",
     "type": "timeseries",
     "description": "The rate at which the RabbitMQ server is confirming published messages. You can compare this metric with PublishRate to better understand how your broker is performing.\nThe number produced represents the number of messages per second at the time of sampling.The number produced represents the number of messages per second at the time of sampling.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_amazonmq_confirm_rate_average{broker=~\"$broker\"}",
       "legendFormat": "{{broker}}"
      }
     ]
    },
    {
     "title": "Publish Rate",
     "type": "timeseries",
     "description": "The rate at which messages are published to the broker.\nThe number produced represents the number of messages per second at the time of sampling.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aws_amazonmq_publish_rate_average{broker=~\"$broker\"}",
       "legendFormat": "{{broker}}"
      }
     ]
    }
   ]
  }
 ]
}