{
 "title": "AWS S3",
 "tags": [
  "aws",
  "S3",
  "Cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "bucket_name",
    "label": "Bucket Name",
    "query": {
     "query": "label_values(aws_s3_bucket_size_bytes_average{cluster=\"$cluster\"}, bucket_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total buckets count",
   "type": "stat",
   "description": "Total S3 buckets number",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aws_s3_bucket_size_bytes_average)",
     "legendFormat": "Total buckets"
    }
   ]
  },
  {
   "title": "Number of objects in bucket/Bucket size",
   "type": "table",
   "description": "Number of Objects in bucket/Bucket size",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "aws_s3_number_of_objects_average{}"
    },
    {
     "expr": "aws_s3_bucket_size_bytes_average{}"
    }
   ]
  },
  {
   "title": "Total Buckets",
   "type": "timeseries",
   "description": "Total S3 buckets number history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(aws_s3_bucket_size_bytes_average)",
     "legendFormat": "Buckets"
    }
   ]
  },
  {
   "title": "Buckets by Size",
   "type": "timeseries",
   "description": "Buckets by size in bytes.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (bucket_name) (aws_s3_bucket_size_bytes_average{bucket_name=~\"$bucket_name\"})",
     "legendFormat": "{{bucket_name}}"
    }
   ]
  },
  {
   "title": "Buckets by Objects",
   "type": "timeseries",
   "description": "Buckets by objects",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (bucket_name) (aws_s3_number_of_objects_average{bucket_name=~\"$bucket_name\"})",
     "legendFormat": "{{bucket_name}}"
    }
   ]
  }
 ]
}