{{- if .Values.grafana.datasource.install }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ default (printf "%s-victoriametrics" (include "monitoring-pack-two.fullname" .)) .Values.grafana.datasource.name }}
  namespace: {{ include "monitoring-pack-two.namespace" . }}
  labels:
    name: {{ default (printf "%s-victoriametrics" (include "monitoring-pack-two.fullname" .)) .Values.grafana.datasource.name }}
    app.kubernetes.io/name: {{ default (printf "%s-victoriametrics" (include "monitoring-pack-two.fullname" .)) .Values.grafana.datasource.name }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    monitoring-pack: "two"
    {{- $labelCtx := dict "commonLabels" .Values.commonLabels "componentLabels" .Values.grafana.datasource.labels }}
    {{- include "monitoring-pack-two.metadata.labels" $labelCtx | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  name: {{ .Values.grafana.datasource.spec.name }}
  datasources:
{{- $vmSingleName := default (include "monitoring-pack-two.vmsingle.baseName" .) .Values.vmSingle.name }}
{{- $namespace := include "monitoring-pack-two.namespace" . }}
{{- range .Values.grafana.datasource.spec.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      access: {{ .access }}
      editable: {{ default true .editable }}
      isDefault: {{ default false .isDefault }}
      {{- if .uid }}
      uid: {{ .uid }}
      {{- end }}
      url: {{ .url | replace "k8s-dev-vmsingle.pack-two.svc" (printf "vmsingle-%s.%s.svc" $vmSingleName $namespace) | replace "k8s-dev-vmsingle.monitoring.svc" (printf "vmsingle-%s.%s.svc" $vmSingleName $namespace) }}
      version: {{ .version }}
      {{- if .jsonData }}
      jsonData: {{ toYaml .jsonData | nindent 8 }}
      {{- end }}
      {{- if .secureJsonData }}
      secureJsonData: {{ toYaml .secureJsonData | nindent 8 }}
      {{- end }}
      {{- if .basicAuth }}
      basicAuth: {{ .basicAuth }}
      {{- end }}
      {{- if .basicAuthUser }}
      basicAuthUser: {{ .basicAuthUser }}
      {{- end }}
      {{- if .user }}
      user: {{ .user }}
      {{- end }}
      {{- if .database }}
      database: {{ .database }}
      {{- end }}
{{- end }}
{{- end }}
