{{- $vmAuthValues := .Values.vmAuth | default dict }}
{{- $vmUserValues := .Values.vmUser | default dict }}
{{- $vmUserSpec := $vmUserValues.spec | default dict }}
{{- if and $vmAuthValues.install $vmUserValues.install }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  labels:
    name: vmuser
    app.kubernetes.io/name: vmuser
    app.kubernetes.io/component: victoriametrics
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
    monitoring-pack: "two"
    {{- $labelCtx := dict "commonLabels" .Values.commonLabels "componentLabels" .Values.vmUser.labels }}
    {{- include "monitoring-pack-two.metadata.labels" $labelCtx | nindent 4 }}
  name: {{ default (printf "%s-vmuser" (include "monitoring-pack-two.fullname" .)) $vmUserValues.name }}
  namespace: {{ include "monitoring-pack-two.namespace" . }}
  {{- $annotationCtx := dict "commonAnnotations" .Values.commonAnnotations "componentAnnotations" .Values.vmUser.annotations }}
  {{- include "monitoring-pack-two.metadata.annotations" $annotationCtx | nindent 2 }}
spec:
  {{- if $vmUserSpec.username }}
  username: {{ $vmUserSpec.username }}
  {{- end }}
  {{- if $vmUserSpec.password }}
  password: {{ $vmUserSpec.password }}
  {{- end }}
  {{- if $vmUserSpec.passwordRef }}
  passwordRef: {{ toYaml $vmUserSpec.passwordRef | nindent 4 }}
  {{- end }}
  {{- if $vmUserSpec.tokenRef }}
  tokenRef: {{ toYaml $vmUserSpec.tokenRef | nindent 4 }}
  {{- end }}
  {{- if $vmUserSpec.bearerToken }}
  bearerToken: {{ $vmUserSpec.bearerToken }}
  {{- end }}
  generatePassword: {{ default false $vmUserSpec.generatePassword }}
  {{- if $vmUserSpec.targetRefs }}
  targetRefs: {{ toYaml $vmUserSpec.targetRefs | nindent 4 }}
  {{- else }}
  # Auto-generated targetRefs with host-based routing
  # Each targetRef can specify hosts to route requests from specific Ingress hosts
  # to the corresponding backend services (VMAgent, VMSingle, etc.)
  targetRefs:
    {{- $vmAgentValues := .Values.vmAgent | default dict }}
    {{- $vmSingleValues := .Values.vmSingle | default dict }}
    {{- $namespace := include "monitoring-pack-two.namespace" . }}
    {{- $ingressValues := .Values.ingress | default dict }}
    {{- if and $vmSingleValues $vmSingleValues.install }}
    # VMSingle CRD - route requests from vmsingle host through VMAuth
    - crd:
        kind: VMSingle
        name: {{ default (include "monitoring-pack-two.vmsingle.baseName" .) $vmSingleValues.name }}
        namespace: {{ $vmSingleValues.namespace | default $namespace }}
      {{- if and $ingressValues.vmSingle $ingressValues.vmSingle.host }}
      hosts:
        - {{ $ingressValues.vmSingle.host }}
      {{- end }}
      paths:
        - ""
        - "/"
        - "/vmui.*"
        - "/graph.*"
        - "/api/v1/label.*"
        - "/api/v1/query.*"
        - "/api/v1/metadata.*"
        - "/api/v1/format.*"
        - "/api/v1/series.*"
        - "/api/v1/status.*"
        - "/api/v1/export.*"
        - "/api/v1/admin/tsdb.*"
        # Allow VMUI query endpoints that hit /select/* through VMAuth
        - "/select/0/.*"
        - "/select/.*/prometheus/.*"
        - "/prometheus/graph.*"
        - "/prometheus/api/v1/label.*"
        - "/graphite.*"
        - "/prometheus/api/v1/query.*"
        - "/prometheus/api/v1/rules"
        - "/prometheus/api/v1/alerts"
        - "/prometheus/api/v1/metadata"
        - "/prometheus/api/v1/series.*"
        - "/prometheus/api/v1/status.*"
        - "/prometheus/api/v1/export.*"
        - "/prometheus/federate"
        - "/prometheus/api/v1/admin/tsdb.*"
    {{- end }}
    {{- if $vmAgentValues.install }}
    # VMAgent - route requests from vmagent host through VMAuth
    - crd:
        kind: VMAgent
        name: {{ default (printf "%s-vmagent" (include "monitoring-pack-two.fullname" .)) $vmAgentValues.name }}
        namespace: {{ $namespace }}
      {{- if and $ingressValues.vmAgent $ingressValues.vmAgent.host }}
      hosts:
        - {{ $ingressValues.vmAgent.host }}
      {{- end }}
      paths:
        - ""
        - "/"
        - "/config.*"
        - "/target.*"
        - "/service-discovery.*"
        - "/static.*"
        - "/api/v1/write"
        - "/api/v1/import.*"
        - "/api/v1/target.*"
    {{- end }}
  {{- end }}
{{- end }}
