{{- if and .Values.install .Values.installDnsDefault }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dns-default
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - openshift-dns
  selector: {}
{{- end }}
