{{- if and .Values.install .Values.installDnsOperator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
  name: dns-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: component
  selector:
    matchLabels:
      name: dns-operator
  namespaceSelector:
    matchNames: 
    - openshift-dns-operator
{{- end }}