{{- if and .Values.install .Values.installKubeApiserverOperator .Values.copyOpenshiftCerts }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver-operator-test
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      ca:
        configMap:
          key: service-ca.crt
          name: openshift-service-ca
      serverName: metrics.openshift-kube-apiserver-operator.svc
  jobLabel: app
  selector:
    matchLabels:
      app: kube-apiserver-operator
  namespaceSelector:
    matchNames:
    - openshift-kube-apiserver-operator
{{- end }}