{{- if and .Values.install .Values.installNetworkCheckSource }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
  name: network-check-source
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: check-endpoints
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
    - openshift-network-diagnostics
  selector:
    matchLabels:
      app: network-check-source
{{- end }}