{{- if .Values.copyOpenshiftCerts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  labels:
    app.kubernetes.io/name: {{ .Values.rbac.serviceAccountName }}
    app.kubernetes.io/component: openshift-copy-certs
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: Helm
{{- end -}}
