apiVersion: v2
name: qubership-monitoring-operator
description: A Helm chart for monitoring-operator

# A chart can be either an 'application' or a 'library' chart.
type: application
kubeVersion: ">=1.25.0-0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.6.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.88.0

# ~0 is equivalent to >= 0, < 1 (i.e. >=0.x.x and < 1.x.x, where x may have any number)
# Details https://github.com/Masterminds/semver#checking-version-constraints
dependencies:
  # Grafana
  - name: grafana
    condition: grafana.install
    version: ~0
    repository: "file://charts/grafana"

  # Prometheus stack
  - name: prometheus
    condition: prometheus.install
    version: ~0
    repository: "file://charts/prometheus"

  # VictoriaMetrics stack
  - name: victoriametrics
    condition: victoriametrics.vmOperator.install
    version: ~0
    repository: "file://charts/victoriametrics"

  # Autoscaling / HPA support
  - name: prometheusAdapter
    condition: prometheusAdapter.install
    version: ~0
    repository: "file://charts/prometheusAdapter"

  # Promxy (to use one backend link for some servers)
  - name: promxy
    condition: promxy.install
    version: ~0
    repository: "file://charts/promxy"

  # Common Dashboards
  - name: commonDashboards
    condition: commonDashboards.install
    version: ~0
    repository: "file://charts/commonDashboards"

  # Integration tools
  - name: graphite_remote_adapter
    condition: graphite_remote_adapter.install
    version: ~0
    repository: "file://charts/graphite_remote_adapter"

  # Exporters
  - name: blackboxExporter
    condition: blackboxExporter.install
    version: ~0
    repository: "file://charts/blackboxExporter"
  - name: certExporter
    condition: certExporter.install
    version: ~0
    repository: "file://charts/certExporter"
  - name: jsonExporter
    condition: jsonExporter.install
    version: ~0
    repository: "file://charts/jsonExporter"
  - name: networkLatencyExporter
    condition: networkLatencyExporter.install
    version: ~0
    repository: "file://charts/networkLatencyExporter"
  - name: versionExporter
    condition: versionExporter.install
    version: ~0
    repository: "file://charts/versionExporter"
  - name: cloudEventsExporter
    condition: cloudEventsExporter.install
    version: ~0
    repository: "file://charts/cloudEventsExporter"
  - name: goldpingerExporter
    condition: goldpingerExporter.install
    version: ~0
    repository: "file://charts/goldpingerExporter"
  - name: sslExporter
    condition: sslExporter.install
    version: ~0
    repository: "file://charts/sslExporter"

  # AWS CloudWatch exporter
  - name: cloudwatchExporter
    condition: cloudwatchExporter.install
    version: ~0
    repository: "file://charts/cloudwatchExporter"
  # Azure Monitor exporter
  - name: promitorAgentScraper
    condition: promitorAgentScraper.install
    version: ~0
    repository: "file://charts/promitorAgentScraper"
  - name: promitorAgentResourceDiscovery
    condition: promitorAgentResourceDiscovery.install
    version: ~0
    repository: "file://charts/promitorAgentResourceDiscovery"
  # Google Cloud Operations (Stackdriver) exporter
  - name: stackdriverExporter
    condition: stackdriverExporter.install
    version: ~0
    repository: "file://charts/stackdriverExporter"
  # Grafana resources API converter
  - name: qubership-grafana-operator-converter
    alias: grafanaConverter
    condition: grafanaConverter.install
    version: ~0
    repository: "file://charts/grafanaOperatorConverter"
