{{- if .Values.vmAgent.remoteWrite }}
{{- $top := . -}}
{{- range .Values.vmAgent.remoteWrite -}}
{{- if .basicAuth }}
{{- if .basicAuth.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .basicAuth.createSecret.secretName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" $ "name" .basicAuth.createSecret.secretName) | nindent 4 }}
stringData:
  username: {{ .basicAuth.createSecret.username }}
  password: {{ .basicAuth.createSecret.password }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
