{{- if and .Values.vmAgent.install .Values.vmAgent.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vmAgent.secretName }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.vmAgent.secretName "component" "victoriametrics") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.vmAgent.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
{{- end }}
