{{- if and .Values.tlsEnabled (not .Values.vmCluster.vmInsertTlsConfig.existingSecret) }}
{{- if .Values.vmCluster.vmInsertTlsConfig.createSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ default "vminsert-tls-secret" .Values.vmCluster.vmInsertTlsConfig.createSecret.secretName }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" (default "vminsert-tls-secret" .Values.vmCluster.vmInsertTlsConfig.createSecret.secretName) "component" "victoriametrics") | nindent 4 }}
data: {}
stringData:
  {{- if .Values.vmCluster.vmInsertTlsConfig.createSecret.ca }}
  ca.crt:
    {{- toYaml .Values.vmCluster.vmInsertTlsConfig.createSecret.ca | nindent 4 }}
  {{- end }}
  {{- if .Values.vmCluster.vmInsertTlsConfig.createSecret.cert }}
  tls.crt:
    {{- toYaml .Values.vmCluster.vmInsertTlsConfig.createSecret.cert | nindent 4 }}
  {{- end }}
  {{- if .Values.vmCluster.vmInsertTlsConfig.createSecret.key }}
  tls.key:
    {{- toYaml .Values.vmCluster.vmInsertTlsConfig.createSecret.key | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
