{{- if and .Values.install .Values.rbac.createClusterRoleBinding .Values.global.privilegedRights }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "cloudwatch-exporter.rbac.fullname" . }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" (include "cloudwatch-exporter.rbac.fullname" .) "component" "cloudwatch-exporter") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "cloudwatch-exporter.rbac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}