{{- if and .Values.install .Values.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.serviceAccount.name "component" "cloudwatch-exporter") | nindent 4 }}
  annotations:
  {{- if .Values.serviceAccount.annotations }}
    {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}