{{- if and .Values.install .Values.createServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "blackbox-exporter") | nindent 4 }}
{{- end -}}
