{{- if and .Values.install .Values.serviceMonitor.enabled }}
{{- $name := .Values.name -}}
{{- range .Values.serviceMonitor.targets }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-{{ .name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" $ "name" (printf "%s-%s" $.Values.name .name)) | nindent 4 }}
    app.kubernetes.io/processed-by-operator: victoriametrics-operator
spec:
  endpoints:
  - port: http
    scheme: {{ $.Values.serviceMonitor.scheme }}
    path: "/probe"
    interval: {{ .interval | default $.Values.serviceMonitor.defaults.interval }}
    scrapeTimeout: {{ .scrapeTimeout | default $.Values.serviceMonitor.defaults.scrapeTimeout }}
    params:
      module:
      - {{ .module | default $.Values.serviceMonitor.defaults.module }}
      target:
      - {{ .url }}
    metricRelabelings:
      - targetLabel: instance
        replacement: {{ .url }}
      - targetLabel: target
        replacement: {{ .name }}
        {{- range $targetLabel, $replacement := .additionalMetricsRelabels | default $.Values.serviceMonitor.defaults.additionalMetricsRelabels }}
      - targetLabel: {{ $targetLabel }}
        replacement: {{ $replacement }}
        {{- end }}
  jobLabel: {{ $name }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ $name }}
{{- end }}
{{- end }}
