{{- if .Values.install }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "blackbox-exporter") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
{{- end }}