{{- $name := .Values.name -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "processedByOperator" "prometheus-operator") | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
      port: http
      scheme: {{ .Values.serviceMonitor.scheme }}
  jobLabel: {{ $name }}-self
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ $name }}
