{{- if .Values.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphite-config
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" "graphite-config" "component" "graphite-remote-adapter") | nindent 4 }}
data:
  {{- if .Values.additionalGraphiteConfig }}
  additionalGraphiteConfig.yaml: |-
    {{- toYaml .Values.additionalGraphiteConfig | nindent 6 }}
  {{- else }}
  additionalGraphiteConfig.yaml: ""
  {{- end }}
{{- end }}

