{{- if .Values.install }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: graphite-remote-adapter
    app.kubernetes.io/part-of: monitoring
    {{- $image := include "graphiteRemoteAdapter.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ cat .Values.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: graphite-remote-adapter
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/version: {{ splitList ":" $image | last }}
        app.kubernetes.io/managed-by: Helm
        {{- if .Values.labels }}
          {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.annotations }}
          {{- toYaml .Values.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ template "graphiteRemoteAdapter.image" . }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /graphite-remote-adapter
          args:
            - '--config.file=/graphite-remote-adapter/additionalGraphiteConfig.yaml'
            - '--web.listen-address=0.0.0.0:9201'
            - '--graphite.write.carbon-address={{ .Values.writeCarbonAddress }}'
            - '--graphite.write.carbon-transport=tcp'
            - '--graphite.read.url={{ .Values.readUrl }}'
            - '--graphite.default-prefix={{ .Values.defaultPrefix }}'
            {{- if .Values.enableTags }}
            - '--graphite.enable-tags'
            {{- end }}
          ports:
            - containerPort: 9201
              name: http
          resources:
            {{ include "graphiteRemoteAdapter.resources" $ }}
          terminationMessagePath: /dev/termination-log
      volumes:
        - name: config
          configMap:
            name: graphite-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        {{ include "graphiteRemoteAdapter.securityContext" . }}
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ .Values.name }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
{{- end }}
