{{- if and .Values.install .Values.servicemonitor.install }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "monitoring" "processedByOperator" "prometheus-operator") | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      port: web
  jobLabel: {{ .Values.name }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - {{ .Values.name }}
{{- end }}
