{{- if and .Values.install .Values.stackdriver.serviceAccountKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common-labels.resourceLabels" (dict "ctx" . "name" .Values.name "component" "stackdriver-exporter") | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.stackdriver.serviceAccountKey | b64enc | quote }}
{{- end }}
