{{- if .Values.install }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.name "component" "stackdriver-exporter") | nindent 4 }}
    {{- if .Values.labels }}
      {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: 9255
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
{{- end }}
