{{- if and .Values.install  .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" .Values.secrets.secretName) | nindent 4 }}
type: Opaque
data:
  {{- if .Values.azureAuthentication.identity.key }}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.identity.key | b64enc | quote }}
  {{- else if .Values.azureAuthentication.appKey }}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}