{{- if and .Values.install .Values.rbac.createClusterRole .Values.global.privilegedRights }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "cloudwatch-exporter.rbac.fullname" . }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" (include "cloudwatch-exporter.rbac.fullname" .)) | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    resourceNames: ["{{ .Values.name }}"]
    verbs: ["get"]
{{- end }}
