{{- if and .Values.install (not ((.Values.aws.secret).name)) (and .Values.aws.aws_access_key_id .Values.aws.aws_secret_access_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  credentials: {{ include "cloudwatch-exporter.awsCredentialsIni" . | b64enc | quote }}
{{- end }}
