apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDataSource
metadata:
  name: simple-datasource-example
  labels:
    app.kubernetes.io/component: monitoring   # Mandatory label
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/component: grafana
  datasource:
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    type: prometheus
    url: 'http://prometheus-operated:9090'
    version: 1
