{{- if and .Values.install .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
  labels:
    {{- include "monitoring.resourceLabels" (dict "ctx" . "name" .Values.secrets.secretName "component" "promitor-agent-scraper") | nindent 4 }}
type: Opaque
data:
  {{- if .Values.azureAuthentication.identity.key}}
  {{ .Values.secrets.appKeySecret  }}: {{ .Values.azureAuthentication.identity.key | b64enc | quote }}
  {{- end }}
{{- end }}
