{{- if and .Values.install .Values.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" .Values.serviceAccount.name) | nindent 4 }}
    {{- if .Values.serviceAccount.labels }}
    {{- include "monitoring.extraLabels" (dict "ctx" . "extraLabels" .Values.serviceAccount.labels) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}
