{{- if and .Values.vmAuth.install .Values.vmAuth.extraVarsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vmAuth.secretName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" .Values.vmAuth.secretName) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.vmAuth.extraVarsSecret }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
{{- end }}
