apiVersion: v1
kind: Secret
metadata:
  name: vm-additional-scrape-configs
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "vm-additional-scrape-configs") | nindent 4 }}
type: Opaque
{{- if .Values.vmAgent.additionalScrape }}
stringData:
  prometheus-additional.yaml: |-
    {{ toYaml .Values.vmAgent.additionalScrape | nindent 4 }}
{{- else }}
data:
  prometheus-additional.yaml: ""
{{- end }}
