{{- if and .Values.tlsEnabled (not .Values.vmAlertManager.tlsConfig.existingSecret) }}
{{- if .Values.vmAlertManager.tlsConfig.createSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ default "vmalertmanager-tls-secret" .Values.vmAlertManager.tlsConfig.createSecret.secretName }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" (default "vmalertmanager-tls-secret" .Values.vmAlertManager.tlsConfig.createSecret.secretName) "component" "vmalertmanager") | nindent 4 }}
data: {}
stringData:
  {{- if .Values.vmAlertManager.tlsConfig.createSecret.ca }}
  ca.crt:
    {{- toYaml .Values.vmAlertManager.tlsConfig.createSecret.ca | nindent 4 }}
  {{- end }}
  {{- if .Values.vmAlertManager.tlsConfig.createSecret.cert }}
  tls.crt:
    {{- toYaml .Values.vmAlertManager.tlsConfig.createSecret.cert | nindent 4 }}
  {{- end }}
  {{- if .Values.vmAlertManager.tlsConfig.createSecret.key }}
  tls.key:
    {{- toYaml .Values.vmAlertManager.tlsConfig.createSecret.key | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
