apiVersion: v1
kind: Secret
metadata:
  name: vmuser-secret
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" "vmuser-secret") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.vmUser.password }}
