name: Lint and Test Helm Charts

permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/**'
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: null

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Chart Testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Copy examples for ct in /charts/qubership-monitoring-operator/ci/
        run: |
            mkdir -p charts/qubership-monitoring-operator/ci
            cp docs/examples/deploy-parameters/*.yaml charts/qubership-monitoring-operator/ci/
            cp docs/examples/deploy-parameters/**/*.yaml charts/qubership-monitoring-operator/ci/
            ls -la charts charts/qubership-monitoring-operator charts/qubership-monitoring-operator/ci

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false --chart-dirs=charts
