---
name: Check Go Modules Licenses
on:
  push:

jobs:
  check-license:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@8c6dbeb901920bae9f40d7d7b646d8d9127e1ce7 # v2.4.0
