---
name: Check Go Modules Licenses
on:
  push:

jobs:
  check-license:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@b6bee6f61fdc8b367777c1173fc852a58878a6a7 # v2.5.0
