---
name: Check Go Modules Licenses
on:
  push:

jobs:
  check-license:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/go-check-license.yaml@288a6a0d9a78e80dfdefccab1be6497a39deb746 # v2.8.0
