---
name: Test Monitoring Operator Installation

on:
  workflow_run:
    workflows: ["Build Artifacts"]
    types:
      - completed
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  kind_name: kind-cluster
  namespace: monitoring
  grafanaDashboards_install: true
  prometheusRules_install: true
  pushgateway_install: true
  commonDashboards_install: true
  prometheusAdapter_install: true
  promxy_install: true
  graphite_remote_adapter_install: true
  blackboxExporter_install: true
  jsonExporter_install: true
  networkLatencyExporter_install: true
  versionExporter_install: true
  cloudEventsExporter_install: true
  integrationTests_install: true

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kind
        run: |
          curl -sLo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/
          kind create cluster --name ${{ env.kind_name }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


      - name: Check kubectl context
        run: kubectl config current-context

      - name: Check cluster status
        run: kubectl get pods --all-namespaces

      - name: Show kubeconfig
        run: cat ~/.kube/config

      - name: Check Kind version
        run: kind version

      - name: Check kubectl version
        run: kubectl version

      - name: Install Qubership Monitoring Operator
        run: |
          helm upgrade --install qubership-monitoring-operator \
            --namespace=${{ env.namespace }} \
            --create-namespace \
            --set integrationTests.install=${{ env.integrationTests_install }} \
            --debug \
            ./charts/qubership-monitoring-operator

      - name: Check Tests Deployment Status
        run: |
          kubectl rollout status deployment/monitoring-tests -n ${{ env.namespace }} --timeout=100s

      - name: Print All Pods Info
        run: |
          kubectl get pods -n ${{ env.namespace }}

      - name: Get Logs of monitoring-tests Pod
        run: |
          POD_NAME=$(kubectl get pods -n ${{ env.namespace }} --no-headers | grep 'monitoring-tests' | awk '{print $1}')
          if [ -n "$POD_NAME" ]; then
            kubectl logs -n ${{ env.namespace }} "$POD_NAME"
          else
            echo "No pod found with name containing 'monitoring-tests'"
          fi

      - name: Cleanup
        run: |
          kind delete cluster --name ${{ env.kind_name }}
