name: 'Tests: Run monitoring integration tests'

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - .github/workflows/integration-tests.yaml
      - .github/expected-vm-cr-statuses.json
      - api/**
      - charts/**
      - cmd/**
      - controllers/**
      - test/robot-tests/**
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - .github/workflows/integration-tests.yaml
      - .github/expected-vm-cr-statuses.json
      - api/**
      - charts/**
      - cmd/**
      - controllers/**
      - test/robot-tests/**
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  Wait-for-images:
    if: |
      (
        github.event_name != 'pull_request' || (
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]' &&
          github.event.pull_request.head.repo.full_name == github.repository
        )
      )
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for build.yaml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@6a2de8d62ac5b6998e30f923613c998c263ea9f2 # v2.2.2
        id: wait
        with:
          workflow: build.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

  Monitoring-Pipeline:
    needs: [Wait-for-images]
    if: |
      needs.Wait-for-images.outputs.conclusion == 'success' &&
        (
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        )
    uses: Netcracker/qubership-test-pipelines/.github/workflows/monitoring.yaml@247c69038e00f2a9e283412e902555f84b16dab2 # v1.8.0
    with:
      service_branch: ${{ github.sha }}
      pipeline_branch: '5e867049c9bc60651f53611cdcf167dc0c7f8ff4' # this value must match the value after '@' in 'uses'
      repository_name: '${{ github.repository_owner }}/qubership-monitoring-operator'
      kind-layout: 'single-node'
