---
name: Link Checker

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'docs/**'
      - '*.md'
  push:
    branches:
      - main
    paths:
        - 'docs/**'
        - '*.md'
  workflow_dispatch: null

permissions:
  contents: read

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Restore lychee cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: restore-cache
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 #v2.7.0
        with:
          args: >-
            './**/*.md'
            --verbose
            --no-progress
            --user-agent 'Mozilla/5.0 (X11; Linux x86_64) Chrome/134.0.0.0'
            --retry-wait-time 60
            --max-retries 8
            --accept 100..=103,200..=299,429
            --cookie-jar cookies.json
            --exclude-all-private
            --max-concurrency 4
            --cache
            --cache-exclude-status '429, 500..502'
            --max-cache-age 1d
          format: markdown
          fail: true
