name: Run Monitoring Pipeline

on:
  push
#  pull_request:
#    types: [opened, synchronize, reopened]
#    branches: [main]


jobs:
  Monitoring-Pipeline:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    uses: Netcracker/qubership-test-pipelines/.github/workflows/monitoring.yaml@monitoring
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      versions_file: '.github/versions.yaml'
      pipeline_branch: 'monitoring' #this value must match the value after '@' in 'uses'
