kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: platform-monitoring-grafana-operator
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: monitoring-operator
rules:
  - apiGroups:
      - "integreatly.org"
    resources:
      - grafanadashboards
      - grafanadashboards/status
      - grafanadatasources
      - grafanadatasources/status
      - grafanafolders
      - grafanafolders/status
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
  - apiGroups:
      - "grafana.integreatly.org"
    resources:
      - grafanadashboards
      - grafanadashboards/status
      - grafanadatasources
      - grafanadatasources/status
      - grafanas
      - grafanas/status
      - grafanafolders
      - grafanafolders/status
      - grafanacontactpoints
      - grafanacontactpoints/status
      - grafanaalertrulegroups
      - grafanaalertrulegroups/status
      - grafananotificationpolicies
      - grafananotificationpolicies/status
      - grafananotificationtemplates
      - grafananotificationtemplates/status
      - grafanamutetimings
      - grafanamutetimings/status
      - grafananotificationpolicyroutes
      - grafananotificationpolicyroutes/status
      - grafanalibrarypanels
      - grafanalibrarypanels/status
      - grafanaserviceaccounts
      - grafanaserviceaccounts/status
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - secrets
      - serviceaccounts
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
