{{- if and .Values.install .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "monitoring.labels" (dict "ctx" . "name" .Values.serviceAccount.name) | nindent 4 }}
    {{- include "monitoring.extraLabels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
